var namespacepocketmine_1_1command =
[
    [ "defaults", null, [
      [ "BanCommand", "da/d23/classpocketmine_1_1command_1_1defaults_1_1_ban_command.html", "da/d23/classpocketmine_1_1command_1_1defaults_1_1_ban_command" ],
      [ "BanIpCommand", "d1/d73/classpocketmine_1_1command_1_1defaults_1_1_ban_ip_command.html", "d1/d73/classpocketmine_1_1command_1_1defaults_1_1_ban_ip_command" ],
      [ "BanListCommand", "d7/d21/classpocketmine_1_1command_1_1defaults_1_1_ban_list_command.html", "d7/d21/classpocketmine_1_1command_1_1defaults_1_1_ban_list_command" ],
      [ "DefaultGamemodeCommand", "d5/d93/classpocketmine_1_1command_1_1defaults_1_1_default_gamemode_command.html", "d5/d93/classpocketmine_1_1command_1_1defaults_1_1_default_gamemode_command" ],
      [ "DeopCommand", "dc/dd8/classpocketmine_1_1command_1_1defaults_1_1_deop_command.html", "dc/dd8/classpocketmine_1_1command_1_1defaults_1_1_deop_command" ],
      [ "DifficultyCommand", "d0/d74/classpocketmine_1_1command_1_1defaults_1_1_difficulty_command.html", "d0/d74/classpocketmine_1_1command_1_1defaults_1_1_difficulty_command" ],
      [ "GamemodeCommand", "d7/de4/classpocketmine_1_1command_1_1defaults_1_1_gamemode_command.html", "d7/de4/classpocketmine_1_1command_1_1defaults_1_1_gamemode_command" ],
      [ "GiveCommand", "d8/d3e/classpocketmine_1_1command_1_1defaults_1_1_give_command.html", "d8/d3e/classpocketmine_1_1command_1_1defaults_1_1_give_command" ],
      [ "HelpCommand", "da/d3a/classpocketmine_1_1command_1_1defaults_1_1_help_command.html", "da/d3a/classpocketmine_1_1command_1_1defaults_1_1_help_command" ],
      [ "KickCommand", "d7/dce/classpocketmine_1_1command_1_1defaults_1_1_kick_command.html", "d7/dce/classpocketmine_1_1command_1_1defaults_1_1_kick_command" ],
      [ "KillCommand", "dc/d6e/classpocketmine_1_1command_1_1defaults_1_1_kill_command.html", "dc/d6e/classpocketmine_1_1command_1_1defaults_1_1_kill_command" ],
      [ "ListCommand", "d3/d0a/classpocketmine_1_1command_1_1defaults_1_1_list_command.html", "d3/d0a/classpocketmine_1_1command_1_1defaults_1_1_list_command" ],
      [ "MeCommand", "d7/d87/classpocketmine_1_1command_1_1defaults_1_1_me_command.html", "d7/d87/classpocketmine_1_1command_1_1defaults_1_1_me_command" ],
      [ "OpCommand", "df/d64/classpocketmine_1_1command_1_1defaults_1_1_op_command.html", "df/d64/classpocketmine_1_1command_1_1defaults_1_1_op_command" ],
      [ "PardonCommand", "d2/dea/classpocketmine_1_1command_1_1defaults_1_1_pardon_command.html", "d2/dea/classpocketmine_1_1command_1_1defaults_1_1_pardon_command" ],
      [ "PardonIpCommand", "dc/da7/classpocketmine_1_1command_1_1defaults_1_1_pardon_ip_command.html", "dc/da7/classpocketmine_1_1command_1_1defaults_1_1_pardon_ip_command" ],
      [ "PluginsCommand", "d8/d56/classpocketmine_1_1command_1_1defaults_1_1_plugins_command.html", "d8/d56/classpocketmine_1_1command_1_1defaults_1_1_plugins_command" ],
      [ "ReloadCommand", "d6/db3/classpocketmine_1_1command_1_1defaults_1_1_reload_command.html", "d6/db3/classpocketmine_1_1command_1_1defaults_1_1_reload_command" ],
      [ "SaveCommand", "d6/ddd/classpocketmine_1_1command_1_1defaults_1_1_save_command.html", "d6/ddd/classpocketmine_1_1command_1_1defaults_1_1_save_command" ],
      [ "SaveOffCommand", "d7/daf/classpocketmine_1_1command_1_1defaults_1_1_save_off_command.html", "d7/daf/classpocketmine_1_1command_1_1defaults_1_1_save_off_command" ],
      [ "SaveOnCommand", "d7/d8d/classpocketmine_1_1command_1_1defaults_1_1_save_on_command.html", "d7/d8d/classpocketmine_1_1command_1_1defaults_1_1_save_on_command" ],
      [ "SayCommand", "d5/d3c/classpocketmine_1_1command_1_1defaults_1_1_say_command.html", "d5/d3c/classpocketmine_1_1command_1_1defaults_1_1_say_command" ],
      [ "SeedCommand", "d3/da8/classpocketmine_1_1command_1_1defaults_1_1_seed_command.html", "d3/da8/classpocketmine_1_1command_1_1defaults_1_1_seed_command" ],
      [ "SetWorldSpawnCommand", "df/d66/classpocketmine_1_1command_1_1defaults_1_1_set_world_spawn_command.html", "df/d66/classpocketmine_1_1command_1_1defaults_1_1_set_world_spawn_command" ],
      [ "SpawnpointCommand", "d0/d2f/classpocketmine_1_1command_1_1defaults_1_1_spawnpoint_command.html", "d0/d2f/classpocketmine_1_1command_1_1defaults_1_1_spawnpoint_command" ],
      [ "StatusCommand", "db/dce/classpocketmine_1_1command_1_1defaults_1_1_status_command.html", "db/dce/classpocketmine_1_1command_1_1defaults_1_1_status_command" ],
      [ "StopCommand", "d2/d16/classpocketmine_1_1command_1_1defaults_1_1_stop_command.html", "d2/d16/classpocketmine_1_1command_1_1defaults_1_1_stop_command" ],
      [ "TeleportCommand", "d3/d02/classpocketmine_1_1command_1_1defaults_1_1_teleport_command.html", "d3/d02/classpocketmine_1_1command_1_1defaults_1_1_teleport_command" ],
      [ "TellCommand", "d7/d4c/classpocketmine_1_1command_1_1defaults_1_1_tell_command.html", "d7/d4c/classpocketmine_1_1command_1_1defaults_1_1_tell_command" ],
      [ "TimeCommand", "dc/d55/classpocketmine_1_1command_1_1defaults_1_1_time_command.html", "dc/d55/classpocketmine_1_1command_1_1defaults_1_1_time_command" ],
      [ "TimingsCommand", "d6/d17/classpocketmine_1_1command_1_1defaults_1_1_timings_command.html", "d6/d17/classpocketmine_1_1command_1_1defaults_1_1_timings_command" ],
      [ "VanillaCommand", "d5/dfa/classpocketmine_1_1command_1_1defaults_1_1_vanilla_command.html", "d5/dfa/classpocketmine_1_1command_1_1defaults_1_1_vanilla_command" ],
      [ "VersionCommand", "d1/d1c/classpocketmine_1_1command_1_1defaults_1_1_version_command.html", "d1/d1c/classpocketmine_1_1command_1_1defaults_1_1_version_command" ],
      [ "WhitelistCommand", "d5/d43/classpocketmine_1_1command_1_1defaults_1_1_whitelist_command.html", "d5/d43/classpocketmine_1_1command_1_1defaults_1_1_whitelist_command" ]
    ] ],
    [ "Command", "d6/df1/classpocketmine_1_1command_1_1_command.html", "d6/df1/classpocketmine_1_1command_1_1_command" ],
    [ "CommandExecutor", "d4/d5f/interfacepocketmine_1_1command_1_1_command_executor.html", "d4/d5f/interfacepocketmine_1_1command_1_1_command_executor" ],
    [ "CommandMap", "de/d06/interfacepocketmine_1_1command_1_1_command_map.html", "de/d06/interfacepocketmine_1_1command_1_1_command_map" ],
    [ "CommandReader", "dd/de2/classpocketmine_1_1command_1_1_command_reader.html", "dd/de2/classpocketmine_1_1command_1_1_command_reader" ],
    [ "CommandSender", "d6/d9d/interfacepocketmine_1_1command_1_1_command_sender.html", "d6/d9d/interfacepocketmine_1_1command_1_1_command_sender" ],
    [ "ConsoleCommandSender", "d4/d42/classpocketmine_1_1command_1_1_console_command_sender.html", "d4/d42/classpocketmine_1_1command_1_1_console_command_sender" ],
    [ "FormattedCommandAlias", "d7/d80/classpocketmine_1_1command_1_1_formatted_command_alias.html", "d7/d80/classpocketmine_1_1command_1_1_formatted_command_alias" ],
    [ "PluginCommand", "d7/d63/classpocketmine_1_1command_1_1_plugin_command.html", "d7/d63/classpocketmine_1_1command_1_1_plugin_command" ],
    [ "PluginIdentifiableCommand", "d4/d58/interfacepocketmine_1_1command_1_1_plugin_identifiable_command.html", "d4/d58/interfacepocketmine_1_1command_1_1_plugin_identifiable_command" ],
    [ "RemoteConsoleCommandSender", "d8/dd0/classpocketmine_1_1command_1_1_remote_console_command_sender.html", "d8/dd0/classpocketmine_1_1command_1_1_remote_console_command_sender" ],
    [ "SimpleCommandMap", "d9/dce/classpocketmine_1_1command_1_1_simple_command_map.html", "d9/dce/classpocketmine_1_1command_1_1_simple_command_map" ]
];