PocketMine-MP: pocketmine\Server Class Reference
pocketmine\Server Class Reference
Public Member Functions
getName ()
isRunning ()
getPocketMineVersion ()
getCodename ()
getVersion ()
getApiVersion ()
getFilePath ()
getDataPath ()
getPluginPath ()
getMaxPlayers ()
getPort ()
getViewDistance ()
getIp ()
getServerName ()
getLevelType ()
getGenerateStructures ()
getGamemode ()
getForceGamemode ()
getDifficulty ()
hasWhitelist ()
getSpawnRadius ()
getAllowFlight ()
isHardcore ()
getDefaultGamemode ()
getMotd ()
getLoader ()
getLogger ()
getEntityMetadata ()
getPlayerMetadata ()
getLevelMetadata ()
getUpdater ()
getPluginManager ()
getCraftingManager ()
getScheduler ()
getGenerationManager ()
getTick ()
getTicksPerSecond ()
getInterfaces ()
addInterface (SourceInterface $interface)
removeInterface (SourceInterface $interface)
sendPacket ($address, $port, $payload)
handlePacket ($address, $port, $payload)
getCommandMap ()
getOnlinePlayers ()
addRecipe (Recipe $recipe)
getOfflinePlayer ($name)
getOfflinePlayerData ($name)
saveOfflinePlayerData ($name, Compound $nbtTag)
getPlayer ($name)
getPlayerExact ($name)
matchPlayer ($partialName)
removePlayer (Player $player)
getLevels ()
getDefaultLevel ()
setDefaultLevel ($level)
isLevelLoaded ($name)
getLevel ($levelId)
getLevelByName ($name)
unloadLevel (Level $level, $forceUnload=false)
loadLevel ($name)
isLevelGenerated ($name)
getConfigString ($variable, $defaultValue="")
getProperty ($variable, $defaultValue=null)
setConfigString ($variable, $value)
getConfigInt ($variable, $defaultValue=0)
setConfigInt ($variable, $value)
getConfigBoolean ($variable, $defaultValue=false)
setConfigBool ($variable, $value)
getPluginCommand ($name)
getNameBans ()
getIPBans ()
addOp ($name)
removeOp ($name)
addWhitelist ($name)
removeWhitelist ($name)
isWhitelisted ($name)
isOp ($name)
getWhitelisted ()
getOPs ()
reloadWhitelist ()
getCommandAliases ()
__construct (\SplClassLoader $autoloader,\ThreadedLogger $logger, $filePath, $dataPath, $pluginPath)
broadcastMessage ($message)
enablePlugins ($type)
loadPlugin (Plugin $plugin)
disablePlugins ()
checkConsole ()
dispatchCommand (CommandSender $sender, $commandLine)
reload ()
shutdown ()
forceShutdown ()
start ()
checkTicks ()
checkMemory ()
exceptionHandler (\Exception $e)
crashDump ()
addPlayer ($identifier, Player $player)
doAutoSave ()
doLevelGC ()
sendUsage ()
tick ()
Static Public Member Functions
static getGamemodeString ($mode)
static getGamemodeFromString ($str)
static getDifficultyFromString ($str)
static getInstance ()
static broadcastPacket (array $players, DataPacket $packet)
Public Attributes
const BROADCAST_CHANNEL_ADMINISTRATIVE = "pocketmine.broadcast.admin"
const BROADCAST_CHANNEL_USERS = "pocketmine.broadcast.user"
Detailed Description
The class that manages everything
Definition at line 90 of file Server.php.
Constructor & Destructor Documentation
pocketmine\Server::__construct (\SplClassLoader $autoloader, \ThreadedLogger $logger, $filePath, $dataPath, $pluginPath)
Parameters
\SplClassLoader $autoloader
\ThreadedLogger $logger
string $filePath
string $dataPath
string $pluginPath
Definition at line 1386 of file Server.php.
Member Function Documentation
pocketmine\Server::addInterface (SourceInterface $interface)
Parameters
SourceInterface $interface
Definition at line 553 of file Server.php.
pocketmine\Server::addOp ($name)
Parameters
string $name
Definition at line 1277 of file Server.php.
pocketmine\Server::addWhitelist ($name)
Parameters
string $name
Definition at line 1301 of file Server.php.
pocketmine\Server::broadcastMessage ($message)
Parameters
$message
Returns
int
Definition at line 1602 of file Server.php.
static pocketmine\Server::broadcastPacket (array $players, DataPacket $packet) static
Broadcasts a Minecraft packet to a list of players
Parameters
Player[] $players
DataPacket $packet
Definition at line 1636 of file Server.php.
Referenced by pocketmine\inventory\ChestInventory\onClose(), and pocketmine\inventory\ChestInventory\onOpen().
pocketmine\Server::dispatchCommand (CommandSender $sender, $commandLine)
Executes a command from a CommandSender
Parameters
CommandSender $sender
string $commandLine
Returns
bool
Definition at line 1689 of file Server.php.
References pocketmine\command\CommandSender\sendMessage().
pocketmine\Server::enablePlugins ($type)
Parameters
int $type
Definition at line 1646 of file Server.php.
pocketmine\Server::getAllowFlight ()
Returns
bool
Definition at line 432 of file Server.php.
pocketmine\Server::getApiVersion ()
Returns
string
Definition at line 235 of file Server.php.
pocketmine\Server::getCodename ()
Returns
string
Definition at line 221 of file Server.php.
pocketmine\Server::getCommandAliases ()
Returns
string[]
Definition at line 1353 of file Server.php.
pocketmine\Server::getCommandMap ()
Returns
SimpleCommandMap
Definition at line 588 of file Server.php.
pocketmine\Server::getConfigBoolean ($variable, $defaultValue = false)
Parameters
string $variable
boolean $defaultValue
Returns
boolean
Definition at line 1217 of file Server.php.
pocketmine\Server::getConfigInt ($variable, $defaultValue = 0)
Parameters
string $variable
int $defaultValue
Returns
int
Definition at line 1194 of file Server.php.
pocketmine\Server::getConfigString ($variable, $defaultValue = "")
Parameters
string $variable
string $defaultValue
Returns
string
Definition at line 1144 of file Server.php.
pocketmine\Server::getCraftingManager ()
Returns
CraftingManager
Definition at line 509 of file Server.php.
pocketmine\Server::getDataPath ()
Returns
string
Definition at line 249 of file Server.php.
pocketmine\Server::getDefaultGamemode ()
Returns
int
Definition at line 446 of file Server.php.
pocketmine\Server::getDefaultLevel ()
Returns
Level
Definition at line 818 of file Server.php.
pocketmine\Server::getDifficulty ()
Returns
int
Definition at line 411 of file Server.php.
static pocketmine\Server::getDifficultyFromString ($str) static
Parameters
string $str
Returns
int
Definition at line 383 of file Server.php.
pocketmine\Server::getEntityMetadata ()
Returns
EntityMetadataStore
Definition at line 474 of file Server.php.
pocketmine\Server::getFilePath ()
Returns
string
Definition at line 242 of file Server.php.
pocketmine\Server::getForceGamemode ()
Returns
bool
Definition at line 319 of file Server.php.
pocketmine\Server::getGamemode ()
Returns
int
Definition at line 312 of file Server.php.
static pocketmine\Server::getGamemodeFromString ($str) static
Parses a string and returns a gamemode integer, -1 if not found
Parameters
string $str
Returns
int
Definition at line 352 of file Server.php.
static pocketmine\Server::getGamemodeString ($mode) static
Returns the gamemode text name
Parameters
int $mode
Returns
string
Definition at line 330 of file Server.php.
pocketmine\Server::getGenerateStructures ()
Returns
bool
Definition at line 305 of file Server.php.
pocketmine\Server::getGenerationManager ()
Returns
GenerationRequestManager
Definition at line 523 of file Server.php.
static pocketmine\Server::getInstance () static
Returns
Server
Definition at line 1375 of file Server.php.
Referenced by pocketmine\permission\Permission\addParent(), pocketmine\command\Command\broadcastCommandMessage(), pocketmine\permission\PermissibleBase\calculateChildPermissions(), pocketmine\inventory\PlayerInventory\clear(), pocketmine\inventory\BaseInventory\clear(), pocketmine\inventory\CraftingTransactionGroup\execute(), pocketmine\inventory\SimpleTransactionGroup\execute(), pocketmine\inventory\CraftingTransactionGroup\getMatchingRecipe(), pocketmine\permission\Permission\getPermissibles(), pocketmine\command\ConsoleCommandSender\getServer(), pocketmine\permission\PermissibleBase\hasPermission(), pocketmine\plugin\PluginLogger\log(), pocketmine\permission\PermissibleBase\recalculatePermissions(), pocketmine\permission\DefaultPermissions\registerPermission(), pocketmine\inventory\BaseInventory\setItem(), and pocketmine\inventory\PlayerInventory\setItem().
pocketmine\Server::getInterfaces ()
Returns
SourceInterface[]
Definition at line 546 of file Server.php.
pocketmine\Server::getIp ()
Returns
string
Definition at line 284 of file Server.php.
pocketmine\Server::getIPBans ()
Returns
BanList
Definition at line 1270 of file Server.php.
pocketmine\Server::getLevel ($levelId)
Parameters
int $levelId
Returns
Level
Definition at line 849 of file Server.php.
pocketmine\Server::getLevelByName ($name)
Parameters
$name
Returns
Level
Definition at line 862 of file Server.php.
pocketmine\Server::getLevelMetadata ()
Returns
LevelMetadataStore
Definition at line 488 of file Server.php.
pocketmine\Server::getLevels ()
Returns
Level[]
Definition at line 811 of file Server.php.
pocketmine\Server::getLevelType ()
Returns
string
Definition at line 298 of file Server.php.
pocketmine\Server::getLoader ()
Returns
Definition at line 460 of file Server.php.
Referenced by pocketmine\level\generator\GenerationRequestManager\__construct().
pocketmine\Server::getLogger ()
Returns
Definition at line 467 of file Server.php.
Referenced by pocketmine\level\generator\GenerationRequestManager\__construct().
pocketmine\Server::getMaxPlayers ()
Returns
int
Definition at line 263 of file Server.php.
pocketmine\Server::getMotd ()
Returns
string
Definition at line 453 of file Server.php.
pocketmine\Server::getName ()
Returns
string
Definition at line 200 of file Server.php.
pocketmine\Server::getNameBans ()
Returns
BanList
Definition at line 1263 of file Server.php.
pocketmine\Server::getOfflinePlayer ($name)
Parameters
string $name
Returns
OfflinePlayer|Player
Definition at line 608 of file Server.php.
pocketmine\Server::getOfflinePlayerData ($name)
Parameters
string $name
Returns
Compound
Definition at line 624 of file Server.php.
Referenced by pocketmine\OfflinePlayer\__construct().
pocketmine\Server::getOnlinePlayers ()
Returns
Player[]
Definition at line 595 of file Server.php.
pocketmine\Server::getOPs ()
Returns
Config
Definition at line 1342 of file Server.php.
pocketmine\Server::getPlayer ($name)
Parameters
string $name
Returns
Player
Definition at line 745 of file Server.php.
pocketmine\Server::getPlayerExact ($name)
Parameters
string $name
Returns
Player
Definition at line 770 of file Server.php.
pocketmine\Server::getPlayerMetadata ()
Returns
PlayerMetadataStore
Definition at line 481 of file Server.php.
pocketmine\Server::getPluginCommand ($name)
Parameters
string $name
Returns
PluginIdentifiableCommand
Definition at line 1252 of file Server.php.
pocketmine\Server::getPluginManager ()
Returns
PluginManager
Definition at line 502 of file Server.php.
pocketmine\Server::getPluginPath ()
Returns
string
Definition at line 256 of file Server.php.
pocketmine\Server::getPocketMineVersion ()
Returns
string
Definition at line 214 of file Server.php.
pocketmine\Server::getPort ()
Returns
int
Definition at line 270 of file Server.php.
pocketmine\Server::getProperty ($variable, $defaultValue = null)
Parameters
string $variable
mixed $defaultValue
Returns
mixed
Definition at line 1159 of file Server.php.
pocketmine\Server::getScheduler ()
Returns
ServerScheduler
Definition at line 516 of file Server.php.
pocketmine\Server::getServerName ()
Returns
string
Definition at line 291 of file Server.php.
pocketmine\Server::getSpawnRadius ()
Returns
int
Definition at line 425 of file Server.php.
pocketmine\Server::getTick ()
Returns
int
Definition at line 530 of file Server.php.
pocketmine\Server::getTicksPerSecond ()
Returns the last server TPS measure
Returns
float
Definition at line 539 of file Server.php.
pocketmine\Server::getUpdater ()
Returns
AutoUpdater
Definition at line 495 of file Server.php.
pocketmine\Server::getVersion ()
Returns
string
Definition at line 228 of file Server.php.
pocketmine\Server::getViewDistance ()
Returns
int
Definition at line 277 of file Server.php.
pocketmine\Server::getWhitelisted ()
Returns
Config
Definition at line 1335 of file Server.php.
pocketmine\Server::handlePacket ($address, $port, $payload)
Parameters
string $address
int $port
string $payload
Definition at line 579 of file Server.php.
pocketmine\Server::hasWhitelist ()
Returns
bool
Definition at line 418 of file Server.php.
pocketmine\Server::isHardcore ()
Returns
bool
Definition at line 439 of file Server.php.
pocketmine\Server::isLevelGenerated ($name)
Parameters
string $name
Returns
bool
Definition at line 1115 of file Server.php.
pocketmine\Server::isLevelLoaded ($name)
Parameters
string $name
Returns
bool
Definition at line 840 of file Server.php.
pocketmine\Server::isOp ($name)
Parameters
string $name
Returns
bool
Definition at line 1328 of file Server.php.
pocketmine\Server::isRunning ()
Returns
bool
Definition at line 207 of file Server.php.
pocketmine\Server::isWhitelisted ($name)
Parameters
string $name
Returns
bool
Definition at line 1319 of file Server.php.
pocketmine\Server::loadLevel ($name)
Loads a level from the data directory
Parameters
string $name
Returns
bool
Exceptions
Exception
Definition at line 897 of file Server.php.
pocketmine\Server::loadPlugin (Plugin $plugin)
Parameters
Plugin $plugin
Definition at line 1662 of file Server.php.
pocketmine\Server::matchPlayer ($partialName)
Parameters
string $partialName
Returns
Player[]
Definition at line 786 of file Server.php.
pocketmine\Server::removeInterface (SourceInterface $interface)
Parameters
SourceInterface $interface
Definition at line 560 of file Server.php.
pocketmine\Server::removeOp ($name)
Parameters
string $name
Definition at line 1289 of file Server.php.
pocketmine\Server::removePlayer (Player $player)
Parameters
Player $player
Definition at line 804 of file Server.php.
References pocketmine\Player\getAddress(), and pocketmine\Player\getPort().
pocketmine\Server::removeWhitelist ($name)
Parameters
string $name
Definition at line 1309 of file Server.php.
pocketmine\Server::saveOfflinePlayerData ($name, Compound $nbtTag)
Parameters
string $name
Compound $nbtTag
Definition at line 734 of file Server.php.
pocketmine\Server::sendPacket ($address, $port, $payload)
Parameters
string $address
int $port
string $payload
Definition at line 570 of file Server.php.
pocketmine\Server::setConfigBool ($variable, $value)
Parameters
string $variable
bool $value
Definition at line 1243 of file Server.php.
pocketmine\Server::setConfigInt ($variable, $value)
Parameters
string $variable
int $value
Definition at line 1207 of file Server.php.
pocketmine\Server::setConfigString ($variable, $value)
Parameters
string $variable
string $value
Definition at line 1184 of file Server.php.
pocketmine\Server::setDefaultLevel ($level)
Sets the default level to a different level This won't change the level-name property, it only affects the server on runtime
Parameters
Level $level
Definition at line 829 of file Server.php.
pocketmine\Server::shutdown ()
Shutdowns the server correctly
Definition at line 1749 of file Server.php.
pocketmine\Server::start ()
Starts the PocketMine-MP server and starts processing ticks and packets
Definition at line 1794 of file Server.php.
pocketmine\Server::tick ()
Tries to execute a server tick
Definition at line 2031 of file Server.php.
pocketmine\Server::unloadLevel (Level $level, $forceUnload = false)
Parameters
Level $level
bool $forceUnload
Returns
bool
Definition at line 878 of file Server.php.
References pocketmine\level\Level\getFolderName(), pocketmine\level\Level\getID(), and pocketmine\level\Level\unload().
The documentation for this class was generated from the following file:
Server.php