PocketMine-MP: pocketmine\event\entity\EntityDamageEvent Class Reference
pocketmine\event\entity\EntityDamageEvent Class Reference
Public Member Functions
__construct (Entity $entity, $cause, $damage)
getCause ()
getOriginalDamage ($type=self::MODIFIER_BASE)
getDamage ($type=self::MODIFIER_BASE)
setDamage ($damage, $type=self::MODIFIER_BASE)
isApplicable ($type)
getFinalDamage ()
getEntity ()
getEventName ()
isCancelled ()
setCancelled ($value=true)
getHandlers ()
isCancelled ()
setCancelled ($forceCancel=false)
Public Attributes
const MODIFIER_BASE = 0
const MODIFIER_ARMOR = 1
const CAUSE_CONTACT = 0
const CAUSE_ENTITY_ATTACK = 1
const CAUSE_PROJECTILE = 2
const CAUSE_SUFFOCATION = 3
const CAUSE_FALL = 4
const CAUSE_FIRE = 5
const CAUSE_FIRE_TICK = 6
const CAUSE_LAVA = 7
const CAUSE_DROWNING = 8
const CAUSE_BLOCK_EXPLOSION = 9
const CAUSE_ENTITY_EXPLOSION = 10
const CAUSE_VOID = 11
const CAUSE_SUICIDE = 12
const CAUSE_MAGIC = 13
const CAUSE_CUSTOM = 14
Static Public Attributes
static $handlerList = null
Protected Attributes
$entity
$eventName = null
Detailed Description
Definition at line 27 of file EntityDamageEvent.php.
Constructor & Destructor Documentation
pocketmine\event\entity\EntityDamageEvent::__construct (Entity $entity, $cause, $damage)
Parameters
Entity $entity
int $cause
int|int[] $damage
Exceptions
Exception
Definition at line 63 of file EntityDamageEvent.php.
Member Function Documentation
pocketmine\event\entity\EntityDamageEvent::getCause ()
Returns
int
Definition at line 84 of file EntityDamageEvent.php.
pocketmine\event\entity\EntityDamageEvent::getDamage ($type = self::MODIFIER_BASE)
Parameters
int $type
Returns
int
Definition at line 106 of file EntityDamageEvent.php.
pocketmine\event\Event::getEventName () final inherited
Returns
string
Definition at line 43 of file Event.php.
References pocketmine\event\Event\$eventName.
pocketmine\event\entity\EntityDamageEvent::getFinalDamage ()
Returns
int
Definition at line 139 of file EntityDamageEvent.php.
pocketmine\event\Event::getHandlers () inherited
Returns
HandlerList
Definition at line 77 of file Event.php.
pocketmine\event\entity\EntityDamageEvent::getOriginalDamage ($type = self::MODIFIER_BASE)
Parameters
int $type
Returns
int
Definition at line 93 of file EntityDamageEvent.php.
pocketmine\event\entity\EntityDamageEvent::isApplicable ($type)
Parameters
int $type
Returns
bool
Definition at line 132 of file EntityDamageEvent.php.
pocketmine\event\Event::isCancelled () inherited
Returns
bool
Exceptions
BadMethodCallException
Definition at line 52 of file Event.php.
Referenced by pocketmine\plugin\RegisteredListener\callEvent(), and pocketmine\event\Event\setCancelled().
pocketmine\event\Event::setCancelled ($value = true) inherited
Parameters
bool $value
Returns
bool
Exceptions
BadMethodCallException
Definition at line 67 of file Event.php.
References pocketmine\event\Event\isCancelled().
pocketmine\event\entity\EntityDamageEvent::setDamage ($damage, $type = self::MODIFIER_BASE)
Parameters
float $damage
int $type
Exceptions
UnexpectedValueException
Definition at line 120 of file EntityDamageEvent.php.
Member Data Documentation
pocketmine\event\Event::$eventName = null protected inherited
Any callable event must declare the static variable
public static $handlerList = null;
Not doing so will deny the proper event initialization
Definition at line 37 of file Event.php.
Referenced by pocketmine\event\Event\getEventName().
The documentation for this class was generated from the following file:
EntityDamageEvent.php