PocketMine-MP: pocketmine\command\CommandSender Interface Reference
pocketmine\command\CommandSender Interface Reference
Public Member Functions
sendMessage ($message)
getServer ()
getName ()
Detailed Description
Definition at line 26 of file CommandSender.php.
Member Function Documentation
pocketmine\command\CommandSender::getName ()
Returns:
string
Implemented in pocketmine\command\ConsoleCommandSender, and pocketmine\command\RemoteConsoleCommandSender.
Referenced by pocketmine\command\Command\broadcastCommandMessage(), pocketmine\command\defaults\MeCommand\execute(), pocketmine\command\defaults\BanCommand\execute(), pocketmine\command\defaults\SayCommand\execute(), pocketmine\command\defaults\TellCommand\execute(), pocketmine\command\defaults\DeopCommand\execute(), pocketmine\command\defaults\OpCommand\execute(), pocketmine\command\defaults\SpawnpointCommand\execute(), pocketmine\command\defaults\GiveCommand\execute(), pocketmine\command\defaults\GamemodeCommand\execute(), pocketmine\command\defaults\SetWorldSpawnCommand\execute(), and pocketmine\command\defaults\TeleportCommand\execute().
pocketmine\command\CommandSender::getServer ()
Returns:
Implemented in pocketmine\command\ConsoleCommandSender.
Referenced by pocketmine\command\defaults\BanListCommand\execute(), pocketmine\command\defaults\StatusCommand\execute(), pocketmine\command\defaults\DefaultGamemodeCommand\execute(), pocketmine\command\defaults\ReloadCommand\execute(), pocketmine\command\defaults\SaveCommand\execute(), pocketmine\command\defaults\SaveOffCommand\execute(), pocketmine\command\defaults\StopCommand\execute(), pocketmine\command\defaults\SaveOnCommand\execute(), pocketmine\command\defaults\ListCommand\execute(), pocketmine\command\defaults\SeedCommand\execute(), pocketmine\command\defaults\WhitelistCommand\execute(), pocketmine\command\defaults\DifficultyCommand\execute(), pocketmine\command\defaults\MeCommand\execute(), pocketmine\command\defaults\PardonCommand\execute(), pocketmine\command\defaults\TimeCommand\execute(), pocketmine\command\defaults\PardonIpCommand\execute(), pocketmine\command\defaults\BanIpCommand\execute(), pocketmine\command\defaults\TellCommand\execute(), pocketmine\command\defaults\BanCommand\execute(), pocketmine\command\defaults\SayCommand\execute(), pocketmine\command\defaults\DeopCommand\execute(), pocketmine\command\defaults\KickCommand\execute(), pocketmine\command\defaults\OpCommand\execute(), pocketmine\command\defaults\HelpCommand\execute(), pocketmine\command\defaults\VersionCommand\execute(), pocketmine\command\defaults\GamemodeCommand\execute(), pocketmine\command\defaults\SpawnpointCommand\execute(), pocketmine\command\defaults\GiveCommand\execute(), pocketmine\command\defaults\SetWorldSpawnCommand\execute(), and pocketmine\command\defaults\TeleportCommand\execute().
pocketmine\command\CommandSender::sendMessage ($ message)
Parameters:
string $message
Implemented in pocketmine\command\ConsoleCommandSender, and pocketmine\command\RemoteConsoleCommandSender.
Referenced by pocketmine\command\Command\broadcastCommandMessage(), pocketmine\command\defaults\BanListCommand\execute(), pocketmine\command\defaults\StatusCommand\execute(), pocketmine\command\defaults\DifficultyCommand\execute(), pocketmine\command\defaults\MeCommand\execute(), pocketmine\command\FormattedCommandAlias\execute(), pocketmine\command\defaults\PardonCommand\execute(), pocketmine\command\defaults\PardonIpCommand\execute(), pocketmine\command\defaults\PluginsCommand\execute(), pocketmine\command\defaults\SeedCommand\execute(), pocketmine\command\defaults\DefaultGamemodeCommand\execute(), pocketmine\command\defaults\ListCommand\execute(), pocketmine\command\defaults\TimeCommand\execute(), pocketmine\command\defaults\WhitelistCommand\execute(), pocketmine\command\defaults\DeopCommand\execute(), pocketmine\command\defaults\OpCommand\execute(), pocketmine\command\defaults\KillCommand\execute(), pocketmine\command\defaults\BanIpCommand\execute(), pocketmine\command\defaults\SayCommand\execute(), pocketmine\command\defaults\KickCommand\execute(), pocketmine\command\defaults\TellCommand\execute(), pocketmine\command\defaults\BanCommand\execute(), pocketmine\command\defaults\SetWorldSpawnCommand\execute(), pocketmine\command\defaults\VersionCommand\execute(), pocketmine\command\defaults\SpawnpointCommand\execute(), pocketmine\command\defaults\GiveCommand\execute(), pocketmine\command\defaults\GamemodeCommand\execute(), pocketmine\command\defaults\HelpCommand\execute(), pocketmine\command\defaults\TeleportCommand\execute(), pocketmine\command\PluginCommand\execute(), and pocketmine\command\Command\testPermission().
The documentation for this interface was generated from the following file:
CommandSender.php