PocketMine-MP: pocketmine\plugin\PluginBase Class Reference
pocketmine\plugin\PluginBase Class Reference
Public Member Functions
onLoad ()
onEnable ()
onDisable ()
isEnabled ()
setEnabled ($boolean=true)
isDisabled ()
getDataFolder ()
getDescription ()
init (PluginLoader $loader, Server $server, PluginDescription $description, $dataFolder, $file)
getLogger ()
isInitialized ()
getCommand ($name)
onCommand (CommandSender $sender, Command $command, $label, array $args)
getResource ($filename)
saveResource ($filename, $replace=false)
getResources ()
getConfig ()
saveConfig ()
saveDefaultConfig ()
reloadConfig ()
getServer ()
getName ()
getFullName ()
getPluginLoader ()
Protected Member Functions
isPhar ()
getFile ()
Detailed Description
Definition at line 30 of file PluginBase.php.
Member Function Documentation
pocketmine\plugin\PluginBase::getCommand ($name)
Parameters
string $name
Returns
PluginIdentifiableCommand
Definition at line 140 of file PluginBase.php.
References pocketmine\command\PluginIdentifiableCommand\getPlugin(), and pocketmine\plugin\PluginBase\getServer().
pocketmine\plugin\PluginBase::getConfig ()
Returns
Config
Implements pocketmine\plugin\Plugin.
Definition at line 234 of file PluginBase.php.
pocketmine\plugin\PluginBase::getDataFolder () final
Gets the plugin's data folder to save files and configuration
Implements pocketmine\plugin\Plugin.
Definition at line 100 of file PluginBase.php.
pocketmine\plugin\PluginBase::getDescription () final
Returns
PluginDescription
Implements pocketmine\plugin\Plugin.
Definition at line 104 of file PluginBase.php.
pocketmine\plugin\PluginBase::getFullName () final
Returns
string
Definition at line 278 of file PluginBase.php.
pocketmine\plugin\PluginBase::getLogger ()
Returns
PluginLogger
Implements pocketmine\plugin\Plugin.
Definition at line 124 of file PluginBase.php.
pocketmine\plugin\PluginBase::getName () final
Returns
string
Implements pocketmine\plugin\Plugin.
Definition at line 271 of file PluginBase.php.
pocketmine\plugin\PluginBase::getPluginLoader ()
Returns
PluginLoader
Implements pocketmine\plugin\Plugin.
Definition at line 289 of file PluginBase.php.
pocketmine\plugin\PluginBase::getResource ($filename)
Gets an embedded resource on the plugin file.
Parameters
string $filename
Returns
resource Resource data, or null
Implements pocketmine\plugin\Plugin.
Definition at line 179 of file PluginBase.php.
Referenced by pocketmine\plugin\PluginBase\saveResource().
pocketmine\plugin\PluginBase::getResources ()
Returns all the resources incrusted on the plugin
Returns
string[]
Implements pocketmine\plugin\Plugin.
Definition at line 220 of file PluginBase.php.
pocketmine\plugin\PluginBase::getServer () final
Returns
Server
Implements pocketmine\plugin\Plugin.
Definition at line 264 of file PluginBase.php.
Referenced by pocketmine\plugin\PluginBase\getCommand().
pocketmine\plugin\PluginBase::isDisabled () final
Returns
bool
Implements pocketmine\plugin\Plugin.
Definition at line 96 of file PluginBase.php.
References pocketmine\plugin\PluginBase\isEnabled().
pocketmine\plugin\PluginBase::isEnabled () final
Returns
bool
Implements pocketmine\plugin\Plugin.
Definition at line 75 of file PluginBase.php.
Referenced by pocketmine\plugin\PluginBase\isDisabled(), and pocketmine\plugin\PluginBase\setEnabled().
pocketmine\plugin\PluginBase::isInitialized () final
Returns
bool
Definition at line 131 of file PluginBase.php.
pocketmine\plugin\PluginBase::isPhar () protected
Returns
bool
Definition at line 168 of file PluginBase.php.
pocketmine\plugin\PluginBase::onCommand (CommandSender $sender, Command $command, $label, array $args)
Parameters
CommandSender $sender
Command $command
string $label
array $args
Returns
bool
Implements pocketmine\command\CommandExecutor.
Definition at line 161 of file PluginBase.php.
pocketmine\plugin\PluginBase::onDisable ()
Called when the plugin is disabled Use this to free open things and finish actions
Implements pocketmine\plugin\Plugin.
Definition at line 68 of file PluginBase.php.
Referenced by pocketmine\plugin\PluginBase\setEnabled().
pocketmine\plugin\PluginBase::onEnable ()
Called when the plugin is enabled
Implements pocketmine\plugin\Plugin.
Definition at line 64 of file PluginBase.php.
Referenced by pocketmine\plugin\PluginBase\setEnabled().
pocketmine\plugin\PluginBase::onLoad ()
Called when the plugin is loaded, before calling onEnable()
Implements pocketmine\plugin\Plugin.
Definition at line 60 of file PluginBase.php.
pocketmine\plugin\PluginBase::saveResource ($filename, $replace = false)
Parameters
string $filename
bool $replace
Returns
bool
Implements pocketmine\plugin\Plugin.
Definition at line 194 of file PluginBase.php.
References pocketmine\plugin\PluginBase\getResource().
pocketmine\plugin\PluginBase::setEnabled ($boolean = true) final
Parameters
bool $boolean
Definition at line 82 of file PluginBase.php.
References pocketmine\plugin\PluginBase\isEnabled(), pocketmine\plugin\PluginBase\onDisable(), and pocketmine\plugin\PluginBase\onEnable().
The documentation for this class was generated from the following file:
PluginBase.php