PocketMine-MP: pocketmine\inventory\CraftingManager Class Reference
pocketmine\inventory\CraftingManager Class Reference
Public Member Functions
sort (Item $i1, Item $i2)
getRecipes ()
getFurnaceRecipes ()
matchFurnaceRecipe (Item $input)
registerShapedRecipe (ShapedRecipe $recipe)
registerShapelessRecipe (ShapelessRecipe $recipe)
registerFurnaceRecipe (FurnaceRecipe $recipe)
matchTransaction (CraftingTransactionGroup $ts)
registerRecipe (Recipe $recipe)
Public Attributes
$recipes = []
$furnaceRecipes = []
Protected Member Functions
registerFurnace ()
registerStonecutter ()
registerFood ()
registerArmor ()
registerWeapons ()
registerTools ()
registerDyes ()
registerIngots ()
Protected Attributes
$recipeLookup = []
Detailed Description
Definition at line 30 of file CraftingManager.php.
Member Function Documentation
pocketmine\inventory\CraftingManager::getFurnaceRecipes ()
Returns
FurnaceRecipe[]
Definition at line 323 of file CraftingManager.php.
pocketmine\inventory\CraftingManager::getRecipes ()
Returns
Recipe[]
Definition at line 316 of file CraftingManager.php.
pocketmine\inventory\CraftingManager::matchFurnaceRecipe (Item $input)
Parameters
Item $input
Returns
FurnaceRecipe
Definition at line 332 of file CraftingManager.php.
pocketmine\inventory\CraftingManager::matchTransaction (CraftingTransactionGroup $ts)
Parameters
CraftingTransactionGroup $ts
Returns
Recipe
Definition at line 377 of file CraftingManager.php.
References pocketmine\inventory\CraftingTransactionGroup\getRecipe(), and pocketmine\inventory\CraftingTransactionGroup\getResult().
pocketmine\inventory\CraftingManager::registerFurnaceRecipe (FurnaceRecipe $recipe)
Parameters
FurnaceRecipe $recipe
Definition at line 367 of file CraftingManager.php.
References pocketmine\inventory\FurnaceRecipe\getInput().
Referenced by pocketmine\inventory\CraftingManager\registerRecipe().
pocketmine\inventory\CraftingManager::registerRecipe (Recipe $recipe)
Parameters
Recipe $recipe
Definition at line 451 of file CraftingManager.php.
References pocketmine\inventory\CraftingManager\registerFurnaceRecipe(), pocketmine\inventory\CraftingManager\registerShapedRecipe(), and pocketmine\inventory\CraftingManager\registerShapelessRecipe().
pocketmine\inventory\CraftingManager::registerShapedRecipe (ShapedRecipe $recipe)
Parameters
ShapedRecipe $recipe
Definition at line 345 of file CraftingManager.php.
Referenced by pocketmine\inventory\CraftingManager\registerRecipe().
pocketmine\inventory\CraftingManager::registerShapelessRecipe (ShapelessRecipe $recipe)
Parameters
ShapelessRecipe $recipe
Definition at line 352 of file CraftingManager.php.
References pocketmine\inventory\ShapelessRecipe\getIngredientList(), and pocketmine\inventory\ShapelessRecipe\getResult().
Referenced by pocketmine\inventory\CraftingManager\registerRecipe().
The documentation for this class was generated from the following file:
CraftingManager.php