PocketMine-MP: pocketmine\level\format\generic\BaseChunk Class Reference
pocketmine\level\format\generic\BaseChunk Class Reference
Public Member Functions
getBlock ($x, $y, $z, &$blockId, &$meta=null)
getFullBlock ($x, $y, $z)
setBlock ($x, $y, $z, $blockId=null, $meta=null)
getBlockId ($x, $y, $z)
setBlockId ($x, $y, $z, $id)
getBlockData ($x, $y, $z)
setBlockData ($x, $y, $z, $data)
getBlockSkyLight ($x, $y, $z)
setBlockSkyLight ($x, $y, $z, $data)
getBlockLight ($x, $y, $z)
setBlockLight ($x, $y, $z, $data)
getBlockIdColumn ($x, $z)
getBlockDataColumn ($x, $z)
getBlockSkyLightColumn ($x, $z)
getBlockLightColumn ($x, $z)
isSectionEmpty ($fY)
getSection ($fY)
setSection ($fY, ChunkSection $section)
load ($generate=true)
getBlockIdArray ()
getBlockDataArray ()
getBlockSkyLightArray ()
getBlockLightArray ()
getSections ()
initChunk ()
getX ()
getZ ()
setX ($x)
setZ ($z)
getLevel ()
getProvider ()
setProvider (LevelProvider $provider)
getBiomeId ($x, $z)
setBiomeId ($x, $z, $biomeId)
getBiomeColor ($x, $z)
setBiomeColor ($x, $z, $R, $G, $B)
getHeightMap ($x, $z)
setHeightMap ($x, $z, $value)
getHighestBlockAt ($x, $z)
addEntity (Entity $entity)
removeEntity (Entity $entity)
addTile (Tile $tile)
removeTile (Tile $tile)
getEntities ()
getTiles ()
getTile ($x, $y, $z)
isLoaded ()
unload ($save=true, $safe=true)
getBiomeIdArray ()
getBiomeColorArray ()
getHeightMapArray ()
hasChanged ()
setChanged ($changed=true)
isPopulated ()
setPopulated ($value=1)
isGenerated ()
setGenerated ($value=1)
toBinary ()
Static Public Member Functions
static fromBinary ($data, LevelProvider $provider=null)
Public Attributes
const SECTION_COUNT = 8
Protected Member Functions
__construct ($provider, $x, $z, array $sections, $biomeIds=null, array $biomeColors=[], array $heightMap=[], array $entities=[], array $tiles=[])
Protected Attributes
$sections = []
$entities = []
$tiles = []
$tileList = []
$biomeIds
$biomeColors
$blocks
$data
$skyLight
$blockLight
$heightMap
$NBTtiles
$NBTentities
$provider
$x
$z
$hasChanged = false
Detailed Description
Definition at line 33 of file BaseChunk.php.
Constructor & Destructor Documentation
pocketmine\level\format\generic\BaseChunk::__construct ($provider, $x, $z, array $sections, $biomeIds = null, array $biomeColors = [], array $heightMap = [], array $entities = [], array $tiles = []) protected
Parameters
LevelProvider $provider
int $x
int $z
ChunkSection[] $sections
string $biomeIds
int[] $biomeColors
int[] $heightMap
Compound[] $entities
Compound[] $tiles
Exceptions
ChunkException
Definition at line 51 of file BaseChunk.php.
Member Function Documentation
pocketmine\level\format\generic\BaseFullChunk::addEntity (Entity $entity) inherited
Parameters
Entity $entity
Implements pocketmine\level\format\FullChunk.
Definition at line 245 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseFullChunk::addTile (Tile $tile) inherited
Parameters
Tile $tile
Implements pocketmine\level\format\FullChunk.
Definition at line 255 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\hasChanged().
static pocketmine\level\format\FullChunk::fromBinary ($data, LevelProvider $provider = null) static inherited
Parameters
string $data
LevelProvider $provider
Returns
FullChunk
Implemented in pocketmine\level\format\mcregion\Chunk, pocketmine\level\format\leveldb\Chunk, and pocketmine\level\format\anvil\Chunk.
pocketmine\level\format\generic\BaseFullChunk::getBiomeColor ($x, $z) inherited
Parameters
int $x
int $z
Returns
int[] RGB bytes
Implements pocketmine\level\format\FullChunk.
Definition at line 215 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getBiomeColorArray () inherited
Returns
int[]
Implements pocketmine\level\format\FullChunk.
Definition at line 340 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getBiomeId ($x, $z) inherited
Parameters
int $x 0-15
int $z 0-15
Returns
int 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 206 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getBiomeIdArray () inherited
Returns
string[]
Implements pocketmine\level\format\FullChunk.
Definition at line 336 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlock ($x, $y, $z, & $blockId, & $meta = null)
Modifies $blockId and $meta
Deprecated:
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int &$blockId
int &$meta
Implements pocketmine\level\format\FullChunk.
Definition at line 89 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlockData ($x, $y, $z)
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 125 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlockId ($x, $y, $z)
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 110 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlockLight ($x, $y, $z)
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 155 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlockSkyLight ($x, $y, $z)
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 140 of file BaseChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getEntities () inherited
Returns
[]
Implements pocketmine\level\format\FullChunk.
Definition at line 270 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseChunk::getFullBlock ($x, $y, $z)
Gets block and meta in one go
Parameters
int $x 0-15
int $y 0-15
int $z 0-15
Returns
int bitmap, (id << 4) | data
Implements pocketmine\level\format\FullChunk.
Definition at line 95 of file BaseChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getHeightMap ($x, $z) inherited
Parameters
int $x 0-15
int $z 0-15
Returns
int 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 226 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getHeightMapArray () inherited
Returns
int[]
Implements pocketmine\level\format\FullChunk.
Definition at line 344 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getHighestBlockAt ($x, $z) inherited
Parameters
int $x 0-15
int $z 0-15
Returns
int 0-127
Implements pocketmine\level\format\FullChunk.
Definition at line 234 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getLevel () inherited
Returns
LevelProvider
Deprecated:
Definition at line 191 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider().
pocketmine\level\format\generic\BaseFullChunk::getProvider () inherited
Returns
LevelProvider
Implements pocketmine\level\format\FullChunk.
Definition at line 198 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\getLevel(), pocketmine\level\format\generic\BaseFullChunk\isLoaded(), pocketmine\level\format\generic\BaseChunk\load(), pocketmine\level\format\generic\BaseFullChunk\load(), pocketmine\level\format\generic\BaseChunk\setBlock(), pocketmine\level\format\generic\BaseChunk\setBlockData(), pocketmine\level\format\generic\BaseChunk\setBlockId(), pocketmine\level\format\generic\BaseChunk\setBlockLight(), pocketmine\level\format\generic\BaseChunk\setBlockSkyLight(), and pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseChunk::getSection ($fY)
Parameters
int $fY 0-7
Returns
ChunkSection
Implements pocketmine\level\format\Chunk.
Definition at line 210 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getSections ()
Returns
ChunkSection[]
Implements pocketmine\level\format\Chunk.
Definition at line 271 of file BaseChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getTile ($x, $y, $z) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 278 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getTiles () inherited
Returns
[]
Implements pocketmine\level\format\FullChunk.
Definition at line 274 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseFullChunk::getX () inherited
Returns
int
Implements pocketmine\level\format\FullChunk.
Definition at line 170 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\isLoaded(), pocketmine\level\format\generic\BaseChunk\load(), pocketmine\level\format\generic\BaseFullChunk\load(), and pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseFullChunk::getZ () inherited
Returns
int
Implements pocketmine\level\format\FullChunk.
Definition at line 174 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\isLoaded(), pocketmine\level\format\generic\BaseChunk\load(), pocketmine\level\format\generic\BaseFullChunk\load(), and pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseFullChunk::hasChanged () inherited
Returns
boolean
Implements pocketmine\level\format\FullChunk.
Definition at line 348 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\addEntity(), pocketmine\level\format\generic\BaseFullChunk\addTile(), pocketmine\level\format\generic\BaseFullChunk\removeEntity(), pocketmine\level\format\generic\BaseFullChunk\removeTile(), pocketmine\level\format\generic\BaseFullChunk\setBiomeColor(), pocketmine\level\format\generic\BaseFullChunk\setBiomeId(), pocketmine\level\format\generic\BaseChunk\setBlock(), pocketmine\level\format\leveldb\Chunk\setBlock(), pocketmine\level\format\mcregion\Chunk\setBlock(), pocketmine\level\format\leveldb\Chunk\setBlockData(), pocketmine\level\format\mcregion\Chunk\setBlockData(), pocketmine\level\format\generic\BaseChunk\setBlockData(), pocketmine\level\format\leveldb\Chunk\setBlockId(), pocketmine\level\format\mcregion\Chunk\setBlockId(), pocketmine\level\format\generic\BaseChunk\setBlockId(), pocketmine\level\format\generic\BaseChunk\setBlockLight(), pocketmine\level\format\leveldb\Chunk\setBlockLight(), pocketmine\level\format\mcregion\Chunk\setBlockLight(), pocketmine\level\format\generic\BaseChunk\setBlockSkyLight(), pocketmine\level\format\leveldb\Chunk\setBlockSkyLight(), pocketmine\level\format\mcregion\Chunk\setBlockSkyLight(), pocketmine\level\format\generic\BaseFullChunk\setChanged(), pocketmine\level\format\generic\BaseChunk\setSection(), and pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseFullChunk::isLoaded () inherited
Returns
bool
Implements pocketmine\level\format\FullChunk.
Definition at line 283 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider(), pocketmine\level\format\generic\BaseFullChunk\getX(), and pocketmine\level\format\generic\BaseFullChunk\getZ().
pocketmine\level\format\generic\BaseChunk::isSectionEmpty ($fY)
Tests whether a section (mini-chunk) is empty
Parameters
$fY 0-7, (Y / 16)
Returns
bool
Implements pocketmine\level\format\Chunk.
Definition at line 206 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::load ($generate = true)
Loads the chunk
Parameters
bool $generate If the chunk does not exist, generate it
Returns
bool
Implements pocketmine\level\format\FullChunk.
Definition at line 228 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider(), pocketmine\level\format\generic\BaseFullChunk\getX(), and pocketmine\level\format\generic\BaseFullChunk\getZ().
pocketmine\level\format\generic\BaseFullChunk::removeEntity (Entity $entity) inherited
Parameters
Entity $entity
Implements pocketmine\level\format\FullChunk.
Definition at line 250 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseFullChunk::removeTile (Tile $tile) inherited
Parameters
Tile $tile
Implements pocketmine\level\format\FullChunk.
Definition at line 264 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseFullChunk::setBiomeColor ($x, $z, $R, $G, $B) inherited
Parameters
int $x 0-15
int $z 0-15
int $R 0-255
int $G 0-255
int $B 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 221 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseFullChunk::setBiomeId ($x, $z, $biomeId) inherited
Parameters
int $x 0-15
int $z 0-15
int $biomeId 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 210 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseChunk::setBlock ($x, $y, $z, $blockId = null, $meta = null)
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $blockId,if null, do not change
int $meta 0-15, if null, do not change
Implements pocketmine\level\format\FullChunk.
Definition at line 99 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider(), and pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseChunk::setBlockData ($x, $y, $z, $data)
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $data 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 129 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider(), and pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseChunk::setBlockId ($x, $y, $z, $id)
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $id 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 114 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider(), and pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseChunk::setBlockLight ($x, $y, $z, $level)
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $level 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 159 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider(), and pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseChunk::setBlockSkyLight ($x, $y, $z, $level)
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $level 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 144 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider(), and pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseFullChunk::setChanged ($changed = true) inherited
Parameters
bool $changed
Implements pocketmine\level\format\FullChunk.
Definition at line 352 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseFullChunk::setHeightMap ($x, $z, $value) inherited
Parameters
int $x 0-15
int $z 0-15
$value 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 230 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::setProvider (LevelProvider $provider) inherited
Parameters
LevelProvider $provider
Implements pocketmine\level\format\FullChunk.
Definition at line 202 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseChunk::setSection ($fY, ChunkSection $section)
Parameters
int $fY 0-7
ChunkSection $section
Returns
boolean
Implements pocketmine\level\format\Chunk.
Definition at line 214 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\hasChanged().
pocketmine\level\format\generic\BaseFullChunk::unload ($save = true, $safe = true) inherited
Parameters
bool $save
bool $safe If false, unload the chunk even if players are nearby
Returns
bool
Implements pocketmine\level\format\FullChunk.
Definition at line 291 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getEntities(), pocketmine\level\format\generic\BaseFullChunk\getProvider(), pocketmine\level\format\generic\BaseFullChunk\getTiles(), pocketmine\level\format\generic\BaseFullChunk\getX(), pocketmine\level\format\generic\BaseFullChunk\getZ(), and pocketmine\level\format\generic\BaseFullChunk\hasChanged().
The documentation for this class was generated from the following file:
BaseChunk.php