PocketMine-MP: raklib\Binary Class Reference
raklib\Binary Class Reference
Static Public Member Functions
static readTriad ($str)
static writeTriad ($value)
static readBool ($b)
static writeBool ($b)
static readByte ($c, $signed=true)
static writeByte ($c)
static readShort ($str, $signed=true)
static writeShort ($value)
static readLShort ($str, $signed=true)
static writeLShort ($value)
static readInt ($str)
static writeInt ($value)
static readLInt ($str)
static writeLInt ($value)
static readFloat ($str)
static writeFloat ($value)
static readLFloat ($str)
static writeLFloat ($value)
static readDouble ($str)
static writeDouble ($value)
static readLDouble ($str)
static writeLDouble ($value)
static readLong ($x, $signed=true)
static writeLong ($value)
static readLLong ($str)
static writeLLong ($value)
Public Attributes
const BIG_ENDIAN = 0x00
const LITTLE_ENDIAN = 0x01
Detailed Description
Definition at line 20 of file raklib/raklib/Binary.php.
Member Function Documentation
static raklib\Binary::readBool ($b) static
Reads a byte boolean
Parameters
$b
Returns
bool
Definition at line 56 of file raklib/raklib/Binary.php.
static raklib\Binary::readByte ($c, $signed = true) static
Reads an unsigned/signed byte
Parameters
string $c
bool $signed
Returns
int
Definition at line 79 of file raklib/raklib/Binary.php.
static raklib\Binary::readLShort ($str, $signed = true) static
Reads a 16-bit signed/unsigned little-endian number
Parameters
$str
bool $signed
Returns
int
Definition at line 143 of file raklib/raklib/Binary.php.
static raklib\Binary::readShort ($str, $signed = true) static
Reads a 16-bit signed/unsigned big-endian number
Parameters
$str
bool $signed
Returns
int
Definition at line 111 of file raklib/raklib/Binary.php.
Referenced by raklib\protocol\EncapsulatedPacket\fromBinary(), and raklib\server\ServerHandler\handlePacket().
static raklib\Binary::readTriad ($str) static
Reads a 3-byte big-endian number
Parameters
$str
Returns
mixed
Definition at line 32 of file raklib/raklib/Binary.php.
Referenced by raklib\protocol\EncapsulatedPacket\fromBinary().
static raklib\Binary::writeBool ($b) static
Writes a byte boolean
Parameters
$b
Returns
bool|string
Definition at line 67 of file raklib/raklib/Binary.php.
static raklib\Binary::writeByte ($c) static
Writes an unsigned/signed byte
Parameters
$c
Returns
string
Definition at line 95 of file raklib/raklib/Binary.php.
static raklib\Binary::writeLShort ($value) static
Writes a 16-bit signed/unsigned little-endian number
Parameters
$value
Returns
string
Definition at line 159 of file raklib/raklib/Binary.php.
static raklib\Binary::writeShort ($value) static
Writes a 16-bit signed/unsigned big-endian number
Parameters
$value
Returns
string
Definition at line 127 of file raklib/raklib/Binary.php.
Referenced by raklib\protocol\EncapsulatedPacket\toBinary().
static raklib\Binary::writeTriad ($value) static
Writes a 3-byte big-endian number
Parameters
$value
Returns
string
Definition at line 45 of file raklib/raklib/Binary.php.
Referenced by raklib\protocol\EncapsulatedPacket\toBinary().
The documentation for this class was generated from the following file:
raklib/raklib/Binary.php