PocketMine-MP: pocketmine\level\generator\GenerationInstanceManager Class Reference
pocketmine\level\generator\GenerationInstanceManager Class Reference
Public Member Functions
__construct (Server $server)
process ()
shutdown ()
openLevel (Level $level, $generator, array $options=[])
closeLevel (Level $level)
addNamespace ($namespace, $path)
requestChunk (Level $level, $chunkX, $chunkZ)
getChunk ($levelID, $chunkX, $chunkZ)
receiveChunk ($levelID, FullChunk $chunk)
Protected Member Functions
sendChunk ($levelID, FullChunk $chunk)
handleRequest ($levelID, $chunkX, $chunkZ)
Protected Attributes
$server
$generationManager
$generationThread
Detailed Description
Definition at line 29 of file GenerationInstanceManager.php.
Constructor & Destructor Documentation
pocketmine\level\generator\GenerationInstanceManager::__construct (Server $server)
Parameters
Server $server
Definition at line 39 of file GenerationInstanceManager.php.
Member Function Documentation
pocketmine\level\generator\GenerationInstanceManager::closeLevel (Level $level)
Parameters
Level $level
Definition at line 64 of file GenerationInstanceManager.php.
References pocketmine\level\Level\getId().
pocketmine\level\generator\GenerationInstanceManager::openLevel (Level $level, $generator, array $options = [])
Parameters
Level $level
string $generator
array $options
Definition at line 57 of file GenerationInstanceManager.php.
References pocketmine\level\Level\getId(), and pocketmine\level\Level\getSeed().
The documentation for this class was generated from the following file:
GenerationInstanceManager.php