PocketMine-MP: pocketmine\plugin\PharPluginLoader Class Reference
pocketmine\plugin\PharPluginLoader Class Reference
Public Member Functions
__construct (Server $server)
loadPlugin ($file)
getPluginDescription ($file)
getPluginFilters ()
enablePlugin (Plugin $plugin)
disablePlugin (Plugin $plugin)
Detailed Description
Handles different types of plugins
Definition at line 31 of file PharPluginLoader.php.
Constructor & Destructor Documentation
pocketmine\plugin\PharPluginLoader::__construct (Server $server)
Parameters
Server $server
Definition at line 39 of file PharPluginLoader.php.
Member Function Documentation
pocketmine\plugin\PharPluginLoader::disablePlugin (Plugin $plugin)
Parameters
Plugin $plugin
Implements pocketmine\plugin\PluginLoader.
Definition at line 133 of file PharPluginLoader.php.
References pocketmine\plugin\Plugin\getDescription().
pocketmine\plugin\PharPluginLoader::enablePlugin (Plugin $plugin)
Parameters
Plugin $plugin
Implements pocketmine\plugin\PluginLoader.
Definition at line 120 of file PharPluginLoader.php.
References pocketmine\plugin\Plugin\getDescription().
pocketmine\plugin\PharPluginLoader::getPluginDescription ($file)
Gets the PluginDescription from the file
Parameters
string $file
Returns
PluginDescription
Implements pocketmine\plugin\PluginLoader.
Definition at line 85 of file PharPluginLoader.php.
Referenced by pocketmine\plugin\PharPluginLoader\loadPlugin().
pocketmine\plugin\PharPluginLoader::getPluginFilters ()
Returns the filename patterns that this loader accepts
Returns
array
Implements pocketmine\plugin\PluginLoader.
Definition at line 102 of file PharPluginLoader.php.
pocketmine\plugin\PharPluginLoader::loadPlugin ($file)
Loads the plugin contained in $file
Parameters
string $file
Returns
Plugin
Exceptions
Exception
Implements pocketmine\plugin\PluginLoader.
Definition at line 52 of file PharPluginLoader.php.
References pocketmine\plugin\PharPluginLoader\getPluginDescription().
The documentation for this class was generated from the following file:
PharPluginLoader.php