var annotated =
[
    [ "pocketmine", "d2/d69/namespacepocketmine.html", "d2/d69/namespacepocketmine" ],
    [ "raklib", null, [
      [ "protocol", null, [
        [ "ACK", "d9/d87/classraklib_1_1protocol_1_1_a_c_k.html", "d9/d87/classraklib_1_1protocol_1_1_a_c_k" ],
        [ "AcknowledgePacket", "d1/dac/classraklib_1_1protocol_1_1_acknowledge_packet.html", "d1/dac/classraklib_1_1protocol_1_1_acknowledge_packet" ],
        [ "ADVERTISE_SYSTEM", "dd/dba/classraklib_1_1protocol_1_1_a_d_v_e_r_t_i_s_e___s_y_s_t_e_m.html", "dd/dba/classraklib_1_1protocol_1_1_a_d_v_e_r_t_i_s_e___s_y_s_t_e_m" ],
        [ "CLIENT_CONNECT_DataPacket", "d6/d33/classraklib_1_1protocol_1_1_c_l_i_e_n_t___c_o_n_n_e_c_t___data_packet.html", "d6/d33/classraklib_1_1protocol_1_1_c_l_i_e_n_t___c_o_n_n_e_c_t___data_packet" ],
        [ "CLIENT_DISCONNECT_DataPacket", "d3/d83/classraklib_1_1protocol_1_1_c_l_i_e_n_t___d_i_s_c_o_n_n_e_c_t___data_packet.html", "d3/d83/classraklib_1_1protocol_1_1_c_l_i_e_n_t___d_i_s_c_o_n_n_e_c_t___data_packet" ],
        [ "CLIENT_HANDSHAKE_DataPacket", "d3/d5d/classraklib_1_1protocol_1_1_c_l_i_e_n_t___h_a_n_d_s_h_a_k_e___data_packet.html", "d3/d5d/classraklib_1_1protocol_1_1_c_l_i_e_n_t___h_a_n_d_s_h_a_k_e___data_packet" ],
        [ "DATA_PACKET_0", "de/dc2/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__0.html", "de/dc2/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__0" ],
        [ "DATA_PACKET_1", "d9/d17/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__1.html", "d9/d17/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__1" ],
        [ "DATA_PACKET_2", "d0/ddd/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__2.html", "d0/ddd/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__2" ],
        [ "DATA_PACKET_3", "da/d26/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__3.html", "da/d26/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__3" ],
        [ "DATA_PACKET_4", "db/d37/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__4.html", "db/d37/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__4" ],
        [ "DATA_PACKET_5", "d4/d14/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__5.html", "d4/d14/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__5" ],
        [ "DATA_PACKET_6", "d2/d4c/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__6.html", "d2/d4c/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__6" ],
        [ "DATA_PACKET_7", "d2/d63/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__7.html", "d2/d63/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__7" ],
        [ "DATA_PACKET_8", "d0/dc3/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__8.html", "d0/dc3/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__8" ],
        [ "DATA_PACKET_9", "dd/dfb/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__9.html", "dd/dfb/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t__9" ],
        [ "DATA_PACKET_A", "d4/db9/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___a.html", "d4/db9/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___a" ],
        [ "DATA_PACKET_B", "de/d1c/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___b.html", "de/d1c/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___b" ],
        [ "DATA_PACKET_C", "dd/d3e/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___c.html", "dd/d3e/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___c" ],
        [ "DATA_PACKET_D", "db/d9b/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___d.html", "db/d9b/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___d" ],
        [ "DATA_PACKET_E", "d1/d91/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___e.html", "d1/d91/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___e" ],
        [ "DATA_PACKET_F", "dd/d66/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___f.html", "dd/d66/classraklib_1_1protocol_1_1_d_a_t_a___p_a_c_k_e_t___f" ],
        [ "DataPacket", "dc/d27/classraklib_1_1protocol_1_1_data_packet.html", "dc/d27/classraklib_1_1protocol_1_1_data_packet" ],
        [ "EncapsulatedPacket", "d2/df9/classraklib_1_1protocol_1_1_encapsulated_packet.html", "d2/df9/classraklib_1_1protocol_1_1_encapsulated_packet" ],
        [ "NACK", "d4/d24/classraklib_1_1protocol_1_1_n_a_c_k.html", "d4/d24/classraklib_1_1protocol_1_1_n_a_c_k" ],
        [ "OPEN_CONNECTION_REPLY_1", "d9/dca/classraklib_1_1protocol_1_1_o_p_e_n___c_o_n_n_e_c_t_i_o_n___r_e_p_l_y__1.html", "d9/dca/classraklib_1_1protocol_1_1_o_p_e_n___c_o_n_n_e_c_t_i_o_n___r_e_p_l_y__1" ],
        [ "OPEN_CONNECTION_REPLY_2", "d8/d85/classraklib_1_1protocol_1_1_o_p_e_n___c_o_n_n_e_c_t_i_o_n___r_e_p_l_y__2.html", "d8/d85/classraklib_1_1protocol_1_1_o_p_e_n___c_o_n_n_e_c_t_i_o_n___r_e_p_l_y__2" ],
        [ "OPEN_CONNECTION_REQUEST_1", "d4/d8f/classraklib_1_1protocol_1_1_o_p_e_n___c_o_n_n_e_c_t_i_o_n___r_e_q_u_e_s_t__1.html", "d4/d8f/classraklib_1_1protocol_1_1_o_p_e_n___c_o_n_n_e_c_t_i_o_n___r_e_q_u_e_s_t__1" ],
        [ "OPEN_CONNECTION_REQUEST_2", "d4/d11/classraklib_1_1protocol_1_1_o_p_e_n___c_o_n_n_e_c_t_i_o_n___r_e_q_u_e_s_t__2.html", "d4/d11/classraklib_1_1protocol_1_1_o_p_e_n___c_o_n_n_e_c_t_i_o_n___r_e_q_u_e_s_t__2" ],
        [ "Packet", "d6/d53/classraklib_1_1protocol_1_1_packet.html", "d6/d53/classraklib_1_1protocol_1_1_packet" ],
        [ "SERVER_HANDSHAKE_DataPacket", "d3/dd6/classraklib_1_1protocol_1_1_s_e_r_v_e_r___h_a_n_d_s_h_a_k_e___data_packet.html", "d3/dd6/classraklib_1_1protocol_1_1_s_e_r_v_e_r___h_a_n_d_s_h_a_k_e___data_packet" ],
        [ "UNCONNECTED_PING", "d8/dc5/classraklib_1_1protocol_1_1_u_n_c_o_n_n_e_c_t_e_d___p_i_n_g.html", "d8/dc5/classraklib_1_1protocol_1_1_u_n_c_o_n_n_e_c_t_e_d___p_i_n_g" ],
        [ "UNCONNECTED_PING_OPEN_CONNECTIONS", "d2/d7f/classraklib_1_1protocol_1_1_u_n_c_o_n_n_e_c_t_e_d___p_i_n_g___o_p_e_n___c_o_n_n_e_c_t_i_o_n_s.html", "d2/d7f/classraklib_1_1protocol_1_1_u_n_c_o_n_n_e_c_t_e_d___p_i_n_g___o_p_e_n___c_o_n_n_e_c_t_i_o_n_s" ],
        [ "UNCONNECTED_PONG", "d7/dc6/classraklib_1_1protocol_1_1_u_n_c_o_n_n_e_c_t_e_d___p_o_n_g.html", "d7/dc6/classraklib_1_1protocol_1_1_u_n_c_o_n_n_e_c_t_e_d___p_o_n_g" ]
      ] ],
      [ "server", null, [
        [ "RakLibServer", "d1/d8d/classraklib_1_1server_1_1_rak_lib_server.html", "d1/d8d/classraklib_1_1server_1_1_rak_lib_server" ],
        [ "ServerHandler", "d2/d6e/classraklib_1_1server_1_1_server_handler.html", "d2/d6e/classraklib_1_1server_1_1_server_handler" ],
        [ "ServerInstance", "d5/d5d/interfaceraklib_1_1server_1_1_server_instance.html", "d5/d5d/interfaceraklib_1_1server_1_1_server_instance" ],
        [ "Session", "d6/d53/classraklib_1_1server_1_1_session.html", "d6/d53/classraklib_1_1server_1_1_session" ],
        [ "SessionManager", "d7/d20/classraklib_1_1server_1_1_session_manager.html", "d7/d20/classraklib_1_1server_1_1_session_manager" ],
        [ "UDPServerSocket", "d4/d79/classraklib_1_1server_1_1_u_d_p_server_socket.html", "d4/d79/classraklib_1_1server_1_1_u_d_p_server_socket" ]
      ] ],
      [ "Binary", "d5/db2/classraklib_1_1_binary.html", "d5/db2/classraklib_1_1_binary" ],
      [ "RakLib", "d8/df8/classraklib_1_1_rak_lib.html", "d8/df8/classraklib_1_1_rak_lib" ]
    ] ],
    [ "AttachableLogger", "d9/d4f/interface_attachable_logger.html", "d9/d4f/interface_attachable_logger" ],
    [ "AttachableThreadedLogger", "d3/db3/class_attachable_threaded_logger.html", "d3/db3/class_attachable_threaded_logger" ],
    [ "Cond", "de/d5c/class_cond.html", "de/d5c/class_cond" ],
    [ "Logger", "d4/d00/interface_logger.html", "d4/d00/interface_logger" ],
    [ "LoggerAttachment", "d9/d7d/interface_logger_attachment.html", "d9/d7d/interface_logger_attachment" ],
    [ "LogLevel", "dd/de7/interface_log_level.html", "dd/de7/interface_log_level" ],
    [ "Mutex", "d4/de8/class_mutex.html", "d4/de8/class_mutex" ],
    [ "Pool", "de/da2/class_pool.html", "de/da2/class_pool" ],
    [ "ServerSuiteTest", "d9/d4c/class_server_suite_test.html", "d9/d4c/class_server_suite_test" ],
    [ "SplAutoloader", "d3/dce/interface_spl_autoloader.html", "d3/dce/interface_spl_autoloader" ],
    [ "Thread", "d8/d18/class_thread.html", "d8/d18/class_thread" ],
    [ "Threaded", "d0/d82/class_threaded.html", "d0/d82/class_threaded" ],
    [ "ThreadedLogger", "d0/d55/class_threaded_logger.html", "d0/d55/class_threaded_logger" ],
    [ "ThreadedLoggerAttachment", "d2/d6c/class_threaded_logger_attachment.html", "d2/d6c/class_threaded_logger_attachment" ],
    [ "WeakMap", "d5/db9/class_weak_map.html", "d5/db9/class_weak_map" ],
    [ "WeakRef", "d6/d37/class_weak_ref.html", "d6/d37/class_weak_ref" ],
    [ "Worker", "d3/d0a/class_worker.html", "d3/d0a/class_worker" ]
];