var namespaces =
[
    [ "pocketmine", "d2/d69/namespacepocketmine.html", "d2/d69/namespacepocketmine" ],
    [ "pocketmine\\block", "d0/dc3/namespacepocketmine_1_1block.html", "d0/dc3/namespacepocketmine_1_1block" ],
    [ "pocketmine\\command", "da/d0c/namespacepocketmine_1_1command.html", "da/d0c/namespacepocketmine_1_1command" ],
    [ "pocketmine\\entity", "d7/db9/namespacepocketmine_1_1entity.html", "d7/db9/namespacepocketmine_1_1entity" ],
    [ "pocketmine\\event", "d3/daf/namespacepocketmine_1_1event.html", "d3/daf/namespacepocketmine_1_1event" ],
    [ "pocketmine\\event\\block", "d0/d1c/namespacepocketmine_1_1event_1_1block.html", "d0/d1c/namespacepocketmine_1_1event_1_1block" ],
    [ "pocketmine\\event\\entity", "d9/d86/namespacepocketmine_1_1event_1_1entity.html", "d9/d86/namespacepocketmine_1_1event_1_1entity" ],
    [ "pocketmine\\event\\inventory", "da/db8/namespacepocketmine_1_1event_1_1inventory.html", "da/db8/namespacepocketmine_1_1event_1_1inventory" ],
    [ "pocketmine\\event\\level", "d7/df3/namespacepocketmine_1_1event_1_1level.html", "d7/df3/namespacepocketmine_1_1event_1_1level" ],
    [ "pocketmine\\event\\player", "de/d7b/namespacepocketmine_1_1event_1_1player.html", "de/d7b/namespacepocketmine_1_1event_1_1player" ],
    [ "pocketmine\\event\\plugin", "d9/d61/namespacepocketmine_1_1event_1_1plugin.html", "d9/d61/namespacepocketmine_1_1event_1_1plugin" ],
    [ "pocketmine\\event\\server", "db/d28/namespacepocketmine_1_1event_1_1server.html", "db/d28/namespacepocketmine_1_1event_1_1server" ],
    [ "pocketmine\\inventory", "db/d9b/namespacepocketmine_1_1inventory.html", "db/d9b/namespacepocketmine_1_1inventory" ],
    [ "pocketmine\\item", "d0/dec/namespacepocketmine_1_1item.html", "d0/dec/namespacepocketmine_1_1item" ],
    [ "pocketmine\\level", "d1/d22/namespacepocketmine_1_1level.html", "d1/d22/namespacepocketmine_1_1level" ],
    [ "pocketmine\\level\\format\\pmf", "d8/d82/namespacepocketmine_1_1level_1_1format_1_1pmf.html", "d8/d82/namespacepocketmine_1_1level_1_1format_1_1pmf" ],
    [ "pocketmine\\level\\generator", "d6/dc6/namespacepocketmine_1_1level_1_1generator.html", "d6/dc6/namespacepocketmine_1_1level_1_1generator" ],
    [ "pocketmine\\level\\generator\\noise", "d0/d8f/namespacepocketmine_1_1level_1_1generator_1_1noise.html", "d0/d8f/namespacepocketmine_1_1level_1_1generator_1_1noise" ],
    [ "pocketmine\\level\\generator\\object", "d8/dd3/namespacepocketmine_1_1level_1_1generator_1_1object.html", "d8/dd3/namespacepocketmine_1_1level_1_1generator_1_1object" ],
    [ "pocketmine\\level\\generator\\populator", "d2/de9/namespacepocketmine_1_1level_1_1generator_1_1populator.html", "d2/de9/namespacepocketmine_1_1level_1_1generator_1_1populator" ],
    [ "pocketmine\\math", "d8/db3/namespacepocketmine_1_1math.html", "d8/db3/namespacepocketmine_1_1math" ],
    [ "pocketmine\\metadata", "d0/d83/namespacepocketmine_1_1metadata.html", "d0/d83/namespacepocketmine_1_1metadata" ],
    [ "pocketmine\\nbt", "d0/d59/namespacepocketmine_1_1nbt.html", "d0/d59/namespacepocketmine_1_1nbt" ],
    [ "pocketmine\\nbt\\tag", "dc/da8/namespacepocketmine_1_1nbt_1_1tag.html", "dc/da8/namespacepocketmine_1_1nbt_1_1tag" ],
    [ "pocketmine\\network", "db/dd0/namespacepocketmine_1_1network.html", "db/dd0/namespacepocketmine_1_1network" ],
    [ "pocketmine\\network\\protocol", "d2/dfe/namespacepocketmine_1_1network_1_1protocol.html", "d2/dfe/namespacepocketmine_1_1network_1_1protocol" ],
    [ "pocketmine\\network\\query", "d9/df5/namespacepocketmine_1_1network_1_1query.html", "d9/df5/namespacepocketmine_1_1network_1_1query" ],
    [ "pocketmine\\network\\rcon", "d4/d77/namespacepocketmine_1_1network_1_1rcon.html", "d4/d77/namespacepocketmine_1_1network_1_1rcon" ],
    [ "pocketmine\\network\\upnp", "dd/db6/namespacepocketmine_1_1network_1_1upnp.html", "dd/db6/namespacepocketmine_1_1network_1_1upnp" ],
    [ "pocketmine\\permission", "d6/dc0/namespacepocketmine_1_1permission.html", "d6/dc0/namespacepocketmine_1_1permission" ],
    [ "pocketmine\\plugin", "d1/dd8/namespacepocketmine_1_1plugin.html", "d1/dd8/namespacepocketmine_1_1plugin" ],
    [ "pocketmine\\scheduler", "d3/d75/namespacepocketmine_1_1scheduler.html", "d3/d75/namespacepocketmine_1_1scheduler" ],
    [ "pocketmine\\tile", "d7/db1/namespacepocketmine_1_1tile.html", "d7/db1/namespacepocketmine_1_1tile" ],
    [ "pocketmine\\utils", "dc/db6/namespacepocketmine_1_1utils.html", "dc/db6/namespacepocketmine_1_1utils" ],
    [ "pocketmine\\wizard", "d1/d0f/namespacepocketmine_1_1wizard.html", "d1/d0f/namespacepocketmine_1_1wizard" ]
];