PocketMine-MP: pocketmine\command\defaults\SaveOnCommand Class Reference
pocketmine\command\defaults\SaveOnCommand Class Reference
Public Member Functions
__construct ($name)
execute (CommandSender $sender, $currentAlias, array $args)
getName ()
getPermission ()
setPermission ($permission)
testPermission (CommandSender $target)
testPermissionSilent (CommandSender $target)
getLabel ()
setLabel ($name)
register (CommandMap $commandMap)
unregister (CommandMap $commandMap)
isRegistered ()
getAliases ()
getPermissionMessage ()
getDescription ()
getUsage ()
setAliases (array $aliases)
setDescription ($description)
setPermissionMessage ($permissionMessage)
setUsage ($usage)
__toString ()
Static Public Member Functions
static broadcastCommandMessage (CommandSender $source, $message, $sendToSource=true)
Public Attributes
const MAX_COORD = 30000000
const MIN_COORD = -30000000
Protected Member Functions
getInteger (CommandSender $sender, $value, $min=self::MIN_COORD, $max=self::MAX_COORD)
getRelativeDouble ($original, CommandSender $sender, $input, $min=self::MIN_COORD, $max=self::MAX_COORD)
getDouble (CommandSender $sender, $value, $min=self::MIN_COORD, $max=self::MAX_COORD)
Protected Attributes
$description = ""
$usageMessage
Detailed Description
Definition at line 28 of file SaveOnCommand.php.
Member Function Documentation
pocketmine\command\Command::__toString () [inherited]
Returns:
string
Definition at line 306 of file Command.php.
static pocketmine\command\Command::broadcastCommandMessage (CommandSender $ source, $ message, $ sendToSource = true) [static, inherited]
Parameters:
CommandSender $source
string $message
bool $sendToSource
Definition at line 281 of file Command.php.
References pocketmine\command\CommandSender\getName(), and pocketmine\command\CommandSender\sendMessage().
pocketmine\command\defaults\SaveOnCommand::execute (CommandSender $ sender, $ commandLabel, array $ args)
Parameters:
CommandSender $sender
string $commandLabel
string[] $args
Returns:
mixed
Reimplemented from pocketmine\command\Command.
Definition at line 39 of file SaveOnCommand.php.
References pocketmine\command\CommandSender\getServer().
pocketmine\command\Command::getAliases () [inherited]
Returns:
string[]
Definition at line 220 of file Command.php.
pocketmine\command\Command::getDescription () [inherited]
Returns:
string
Definition at line 234 of file Command.php.
pocketmine\command\Command::getLabel () [inherited]
Returns:
string
Definition at line 152 of file Command.php.
pocketmine\command\Command::getName () [inherited]
Returns:
string
Definition at line 93 of file Command.php.
pocketmine\command\Command::getPermission () [inherited]
Returns:
string
Definition at line 100 of file Command.php.
pocketmine\command\Command::getPermissionMessage () [inherited]
Returns:
string
Definition at line 227 of file Command.php.
pocketmine\command\Command::getUsage () [inherited]
Returns:
string
Definition at line 241 of file Command.php.
pocketmine\command\Command::isRegistered () [inherited]
Returns:
bool
Definition at line 213 of file Command.php.
pocketmine\command\Command::register (CommandMap $ commandMap) [inherited]
Registers the command into a Command map
Parameters:
CommandMap $commandMap
Returns:
bool
Definition at line 174 of file Command.php.
pocketmine\command\Command::setAliases (array $ aliases) [inherited]
Parameters:
string[] $aliases
Definition at line 248 of file Command.php.
pocketmine\command\Command::setDescription ($ description) [inherited]
Parameters:
string $description
Definition at line 258 of file Command.php.
pocketmine\command\Command::setPermission ($ permission) [inherited]
Parameters:
string | null $permission
Definition at line 107 of file Command.php.
pocketmine\command\Command::setPermissionMessage ($ permissionMessage) [inherited]
Parameters:
string $permissionMessage
Definition at line 265 of file Command.php.
pocketmine\command\Command::setUsage ($ usage) [inherited]
Parameters:
string $usage
Definition at line 272 of file Command.php.
pocketmine\command\Command::testPermission (CommandSender $ target) [inherited]
Parameters:
CommandSender $target
Returns:
bool
Definition at line 116 of file Command.php.
References pocketmine\command\CommandSender\sendMessage().
pocketmine\command\Command::testPermissionSilent (CommandSender $ target) [inherited]
Parameters:
CommandSender $target
Returns:
bool
Definition at line 135 of file Command.php.
pocketmine\command\Command::unregister (CommandMap $ commandMap) [inherited]
Parameters:
CommandMap $commandMap
Returns:
bool
Definition at line 189 of file Command.php.
The documentation for this class was generated from the following file:
SaveOnCommand.php