PocketMine-MP: pocketmine\tile\Tile Class Reference
pocketmine\tile\Tile Class Reference
Public Member Functions
__construct (FullChunk $chunk, Compound $nbt)
getID ()
saveNBT ()
onUpdate ()
scheduleUpdate ()
close ()
getName ()
getLevel ()
setLevel (Level $level, $strong=false)
isValid ()
setStrong ()
setWeak ()
getSide ($side, $step=1)
distance (Vector3 $pos)
__toString ()
getX ()
getY ()
getZ ()
getFloorX ()
getFloorY ()
getFloorZ ()
getRight ()
getUp ()
getForward ()
getSouth ()
getWest ()
add ($x, $y=0, $z=0)
subtract ($x=0, $y=0, $z=0)
multiply ($number)
divide ($number)
ceil ()
floor ()
round ()
abs ()
distanceSquared (Vector3 $pos)
maxPlainDistance ($x=0, $z=0)
length ()
lengthSquared ()
normalize ()
dot (Vector3 $v)
cross (Vector3 $v)
Static Public Member Functions
static fromObject (Vector3 $pos, Level $level, $strong=false)
Public Attributes
const SIGN = "Sign"
const CHEST = "Chest"
const FURNACE = "Furnace"
$chunk
$name
$id
$x
$y
$z
$attach
$metadata
$closed
$namedtag
$tickTimer
$level = null
Static Public Attributes
static $tileCount = 1
static $needUpdate = []
Protected Attributes
$lastUpdate
$server
Detailed Description
Definition at line 35 of file Tile.php.
Member Function Documentation
pocketmine\math\Vector3::add ($x, $y = 0, $z = 0) inherited
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 90 of file Vector3.php.
Referenced by pocketmine\math\Vector3\subtract(), and pocketmine\level\Level\useBreakOn().
pocketmine\level\Position::distance (Vector3 $pos) inherited
Returns the distance between two points or objects
Parameters
Vector3 $pos
Returns
float
Definition at line 120 of file Position.php.
References pocketmine\level\Position\getLevel().
pocketmine\level\Position::getLevel () inherited
Returns
Level
Definition at line 55 of file Position.php.
Referenced by pocketmine\level\Level\addEntity(), pocketmine\level\Level\addTile(), pocketmine\entity\Entity\checkBlockCollision(), pocketmine\level\Position\distance(), pocketmine\block\Block\getMetadata(), pocketmine\tile\Chest\getPair(), pocketmine\level\Position\getSide(), pocketmine\block\Block\getSide(), pocketmine\Player\getSpawn(), pocketmine\block\Block\hasMetadata(), pocketmine\level\Level\removeEntity(), pocketmine\block\Block\removeMetadata(), pocketmine\level\Level\removeTile(), pocketmine\Player\save(), pocketmine\block\Block\setMetadata(), and pocketmine\Player\spawnTo().
pocketmine\level\Position::getSide ($side, $step = 1) inherited
Returns a side Vector
Parameters
int $side
int $step
Returns
Position
Exceptions
RuntimeException
Definition at line 105 of file Position.php.
References pocketmine\level\Position\getLevel(), and pocketmine\level\Position\isValid().
pocketmine\level\Position::isValid () inherited
Checks if this object has a valid reference to a Level
Returns
bool
Definition at line 71 of file Position.php.
Referenced by pocketmine\level\Position\getSide(), and pocketmine\block\Block\getSide().
pocketmine\level\Position::setStrong () inherited
Marks the level reference as strong so it won't be collected by the garbage collector.
Returns
bool
Definition at line 81 of file Position.php.
pocketmine\level\Position::setWeak () inherited
Marks the level reference as weak so it won't have effect against the garbage collector decision.
Returns
bool
Definition at line 91 of file Position.php.
pocketmine\math\Vector3::subtract ($x = 0, $y = 0, $z = 0) inherited
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 105 of file Vector3.php.
References pocketmine\math\Vector3\add().
The documentation for this class was generated from the following file:
Tile.php