PocketMine-MP: raklib\protocol\EncapsulatedPacket Class Reference
raklib\protocol\EncapsulatedPacket Class Reference
Public Member Functions
getTotalLength ()
toBinary ($internal=false)
__toString ()
Static Public Member Functions
static fromBinary ($binary, $internal=false, &$offset=null)
Public Attributes
$reliability
$hasSplit = false
$length = 0
$messageIndex = null
$orderIndex = null
$orderChannel = null
$splitCount = null
$splitID = null
$splitIndex = null
$buffer
$needACK = false
$identifierACK = null
Detailed Description
Definition at line 26 of file EncapsulatedPacket.php.
Member Function Documentation
static raklib\protocol\EncapsulatedPacket::fromBinary ($binary, $internal = false, & $offset = null) static
Parameters
string $binary
bool $internal
int &$offset
Returns
EncapsulatedPacket
Definition at line 47 of file EncapsulatedPacket.php.
References raklib\Binary\readShort(), and raklib\Binary\readTriad().
Referenced by raklib\server\ServerHandler\handlePacket().
raklib\protocol\EncapsulatedPacket::toBinary ($internal = false)
Parameters
bool $internal
Returns
string
Definition at line 123 of file EncapsulatedPacket.php.
References raklib\Binary\writeShort(), and raklib\Binary\writeTriad().
The documentation for this class was generated from the following file:
EncapsulatedPacket.php