var searchData=
[
  ['fallable',['Fallable',['../d2/d77/classpocketmine_1_1block_1_1_fallable.html',1,'pocketmine::block']]],
  ['fallingblock',['FallingBlock',['../d6/d6f/classpocketmine_1_1entity_1_1_falling_block.html',1,'pocketmine::entity']]],
  ['farmland',['Farmland',['../dc/d4a/classpocketmine_1_1block_1_1_farmland.html',1,'pocketmine::block']]],
  ['feather',['Feather',['../db/df0/classpocketmine_1_1item_1_1_feather.html',1,'pocketmine::item']]],
  ['fence',['Fence',['../dd/d68/classpocketmine_1_1block_1_1_fence.html',1,'pocketmine::block']]],
  ['fencegate',['FenceGate',['../d7/dd3/classpocketmine_1_1block_1_1_fence_gate.html',1,'pocketmine::block']]],
  ['fire',['Fire',['../da/d18/classpocketmine_1_1block_1_1_fire.html',1,'pocketmine::block']]],
  ['flat',['Flat',['../de/dee/classpocketmine_1_1level_1_1generator_1_1_flat.html',1,'pocketmine::level::generator']]],
  ['flintsteel',['FlintSteel',['../d5/db8/classpocketmine_1_1item_1_1_flint_steel.html',1,'pocketmine::item']]],
  ['float',['Float',['../d6/de7/classpocketmine_1_1nbt_1_1tag_1_1_float.html',1,'pocketmine::nbt::tag']]],
  ['flowable',['Flowable',['../d3/d1e/classpocketmine_1_1block_1_1_flowable.html',1,'pocketmine::block']]],
  ['formattedcommandalias',['FormattedCommandAlias',['../d7/d80/classpocketmine_1_1command_1_1_formatted_command_alias.html',1,'pocketmine::command']]],
  ['fuel',['Fuel',['../dd/d62/classpocketmine_1_1inventory_1_1_fuel.html',1,'pocketmine::inventory']]],
  ['fullchunkdatapacket',['FullChunkDataPacket',['../df/d7e/classpocketmine_1_1network_1_1protocol_1_1_full_chunk_data_packet.html',1,'pocketmine::network::protocol']]],
  ['furnace',['Furnace',['../d4/d66/classpocketmine_1_1block_1_1_furnace.html',1,'pocketmine::block']]],
  ['furnace',['Furnace',['../d7/d7c/classpocketmine_1_1tile_1_1_furnace.html',1,'pocketmine::tile']]],
  ['furnaceinventory',['FurnaceInventory',['../dc/d34/classpocketmine_1_1inventory_1_1_furnace_inventory.html',1,'pocketmine::inventory']]],
  ['furnacerecipe',['FurnaceRecipe',['../db/db2/classpocketmine_1_1inventory_1_1_furnace_recipe.html',1,'pocketmine::inventory']]]
];
