PocketMine-MP: pocketmine\command\SimpleCommandMap Class Reference
pocketmine\command\SimpleCommandMap Class Reference
Public Member Functions
__construct (Server $server)
registerAll ($fallbackPrefix, array $commands)
register ($fallbackPrefix, Command $command, $label=null)
dispatch (CommandSender $sender, $commandLine)
clearCommands ()
getCommand ($name)
getCommands ()
registerServerAliases ()
Protected Attributes
$knownCommands = []
Detailed Description
Definition at line 60 of file SimpleCommandMap.php.
Member Function Documentation
pocketmine\command\SimpleCommandMap::clearCommands ()
Returns
void
Implements pocketmine\command\CommandMap.
Definition at line 187 of file SimpleCommandMap.php.
pocketmine\command\SimpleCommandMap::dispatch (CommandSender $sender, $cmdLine)
Parameters
CommandSender $sender
string $cmdLine
Returns
boolean
Implements pocketmine\command\CommandMap.
Definition at line 166 of file SimpleCommandMap.php.
References pocketmine\command\SimpleCommandMap\getCommand().
pocketmine\command\SimpleCommandMap::getCommand ($name)
Parameters
string $name
Returns
Command
Implements pocketmine\command\CommandMap.
Definition at line 195 of file SimpleCommandMap.php.
Referenced by pocketmine\command\SimpleCommandMap\dispatch(), and pocketmine\command\SimpleCommandMap\registerServerAliases().
pocketmine\command\SimpleCommandMap::getCommands ()
Returns
Command[]
Definition at line 206 of file SimpleCommandMap.php.
pocketmine\command\SimpleCommandMap::register ($fallbackPrefix, Command $command, $label = null)
Parameters
string $fallbackPrefix
Command $command
string $label
Implements pocketmine\command\CommandMap.
Definition at line 121 of file SimpleCommandMap.php.
pocketmine\command\SimpleCommandMap::registerAll ($fallbackPrefix, array $commands)
Parameters
string $fallbackPrefix
Command[] $commands
Implements pocketmine\command\CommandMap.
Definition at line 115 of file SimpleCommandMap.php.
pocketmine\command\SimpleCommandMap::registerServerAliases ()
Returns
void
Definition at line 214 of file SimpleCommandMap.php.
References pocketmine\command\SimpleCommandMap\getCommand().
The documentation for this class was generated from the following file:
SimpleCommandMap.php