PocketMine-MP: pocketmine\math\Vector3 Class Reference
pocketmine\math\Vector3 Class Reference
Public Member Functions
__construct ($x=0, $y=0, $z=0)
getX ()
getY ()
getZ ()
getFloorX ()
getFloorY ()
getFloorZ ()
getRight ()
getUp ()
getForward ()
getSouth ()
getWest ()
add ($x, $y=0, $z=0)
subtract ($x=0, $y=0, $z=0)
multiply ($number)
divide ($number)
ceil ()
floor ()
round ()
abs ()
getSide ($side, $step=1)
distance (Vector3 $pos)
distanceSquared (Vector3 $pos)
maxPlainDistance ($x=0, $z=0)
length ()
lengthSquared ()
normalize ()
dot (Vector3 $v)
cross (Vector3 $v)
__toString ()
Public Attributes
$x
$y
$z
Detailed Description
WARNING: This class is available on the PocketMine-MP Zephir project. If this class is modified, remember to modify the PHP C extension.
Definition at line 28 of file Vector3.php.
Member Function Documentation
pocketmine\math\Vector3::add ($x, $y = 0, $z = 0)
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 90 of file Vector3.php.
Referenced by pocketmine\math\Vector3\subtract(), and pocketmine\level\Level\useBreakOn().
pocketmine\math\Vector3::subtract ($x = 0, $y = 0, $z = 0)
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 105 of file Vector3.php.
References pocketmine\math\Vector3\add().
The documentation for this class was generated from the following file:
Vector3.php