PocketMine-MP: pocketmine\plugin\PluginManager Class Reference
pocketmine\plugin\PluginManager Class Reference
Public Member Functions
__construct (Server $server, SimpleCommandMap $commandMap)
getPlugin ($name)
registerInterface ($loaderName)
getPlugins ()
loadPlugin ($path, $loaders=null)
loadPlugins ($directory, $newLoaders=null)
getPermission ($name)
addPermission (Permission $permission)
removePermission ($permission)
getDefaultPermissions ($op)
recalculatePermissionDefaults (Permission $permission)
subscribeToPermission ($permission, Permissible $permissible)
unsubscribeFromPermission ($permission, Permissible $permissible)
subscribeToDefaultPerms ($op, Permissible $permissible)
unsubscribeFromDefaultPerms ($op, Permissible $permissible)
getPermissions ()
isPluginEnabled (Plugin $plugin)
enablePlugin (Plugin $plugin)
disablePlugins ()
disablePlugin (Plugin $plugin)
clearPlugins ()
callEvent (Event $event)
registerEvents (Listener $listener, Plugin $plugin)
registerEvent ($event, Listener $listener, $priority, EventExecutor $executor, Plugin $plugin, $ignoreCancelled=false)
useTimings ()
setUseTimings ($use)
Static Public Attributes
static $pluginParentTimer
static $useTimings = false
Protected Member Functions
parseYamlCommands (Plugin $plugin)
Protected Attributes
$plugins = []
$permissions = []
$defaultPerms = []
$defaultPermsOp = []
$permSubs = []
$defSubs = []
$defSubsOp = []
$fileAssociations = []
Detailed Description
Manages all the plugins, Permissions and Permissibles
Definition at line 39 of file PluginManager.php.
Constructor & Destructor Documentation
pocketmine\plugin\PluginManager::__construct (Server $server, SimpleCommandMap $commandMap)
Parameters
Server $server
SimpleCommandMap $commandMap
Definition at line 96 of file PluginManager.php.
Member Function Documentation
pocketmine\plugin\PluginManager::addPermission (Permission $permission)
Parameters
Permission $permission
Returns
bool
Definition at line 349 of file PluginManager.php.
References pocketmine\permission\Permission\getName().
Referenced by pocketmine\plugin\PluginManager\enablePlugin().
pocketmine\plugin\PluginManager::callEvent (Event $event)
Calls an event
Parameters
Event $event
Definition at line 637 of file PluginManager.php.
pocketmine\plugin\PluginManager::disablePlugin (Plugin $plugin)
Parameters
Plugin $plugin
Definition at line 612 of file PluginManager.php.
References pocketmine\plugin\Plugin\getDescription(), pocketmine\plugin\Plugin\getPluginLoader(), pocketmine\plugin\PluginManager\removePermission(), and pocketmine\event\HandlerList\unregisterAll().
pocketmine\plugin\PluginManager::enablePlugin (Plugin $plugin)
Parameters
Plugin $plugin
Definition at line 541 of file PluginManager.php.
References pocketmine\plugin\PluginManager\addPermission(), pocketmine\plugin\Plugin\getDescription(), and pocketmine\plugin\Plugin\getPluginLoader().
pocketmine\plugin\PluginManager::getDefaultPermissions ($op)
Parameters
boolean $op
Returns
Permission[]
Definition at line 376 of file PluginManager.php.
pocketmine\plugin\PluginManager::getPermission ($name)
Parameters
string $name
Returns
null|Permission
Definition at line 336 of file PluginManager.php.
pocketmine\plugin\PluginManager::getPermissions ()
Returns
Permission[]
Definition at line 521 of file PluginManager.php.
pocketmine\plugin\PluginManager::getPlugin ($name)
Parameters
string $name
Returns
null|Plugin
Definition at line 106 of file PluginManager.php.
Referenced by pocketmine\plugin\PluginManager\loadPlugins().
pocketmine\plugin\PluginManager::getPlugins ()
Returns
Plugin[]
Definition at line 134 of file PluginManager.php.
pocketmine\plugin\PluginManager::isPluginEnabled (Plugin $plugin)
Parameters
Plugin $plugin
Returns
bool
Definition at line 530 of file PluginManager.php.
References pocketmine\plugin\Plugin\getDescription().
pocketmine\plugin\PluginManager::loadPlugin ($path, $loaders = null)
Parameters
string $path
PluginLoader[] $loaders
Returns
Plugin
Definition at line 144 of file PluginManager.php.
References pocketmine\plugin\PluginManager\parseYamlCommands().
Referenced by pocketmine\plugin\PluginManager\loadPlugins().
pocketmine\plugin\PluginManager::loadPlugins ($directory, $newLoaders = null)
Parameters
string $directory
array $newLoaders
Returns
Plugin[]
Definition at line 173 of file PluginManager.php.
References pocketmine\plugin\PluginManager\getPlugin(), and pocketmine\plugin\PluginManager\loadPlugin().
pocketmine\plugin\PluginManager::parseYamlCommands (Plugin $plugin) protected
Parameters
Plugin $plugin
Returns
PluginCommand[]
Definition at line 557 of file PluginManager.php.
References pocketmine\plugin\Plugin\getDescription().
Referenced by pocketmine\plugin\PluginManager\loadPlugin().
pocketmine\plugin\PluginManager::recalculatePermissionDefaults (Permission $permission)
Parameters
Permission $permission
Definition at line 387 of file PluginManager.php.
References pocketmine\permission\Permission\getName().
pocketmine\plugin\PluginManager::registerEvent ($event, Listener $listener, $priority, EventExecutor $executor, Plugin $plugin, $ignoreCancelled = false)
Parameters
string $event Class name that extends Event
Listener $listener
int $priority
EventExecutor $executor
Plugin $plugin
bool $ignoreCancelled
Exceptions
Exception
Definition at line 709 of file PluginManager.php.
References pocketmine\plugin\Plugin\getDescription().
Referenced by pocketmine\plugin\PluginManager\registerEvents().
pocketmine\plugin\PluginManager::registerEvents (Listener $listener, Plugin $plugin)
Registers all the events in the given Listener class
Parameters
Listener $listener
Plugin $plugin
Exceptions
Exception
Definition at line 661 of file PluginManager.php.
References pocketmine\event\EventPriority\NORMAL, and pocketmine\plugin\PluginManager\registerEvent().
pocketmine\plugin\PluginManager::registerInterface ($loaderName)
Parameters
string $loaderName A PluginLoader class name
Returns
boolean
Definition at line 119 of file PluginManager.php.
pocketmine\plugin\PluginManager::removePermission ($permission)
Parameters
string | Permission $permission
Definition at line 363 of file PluginManager.php.
Referenced by pocketmine\plugin\PluginManager\disablePlugin().
pocketmine\plugin\PluginManager::setUseTimings ($use)
Parameters
bool $use
Definition at line 746 of file PluginManager.php.
pocketmine\plugin\PluginManager::subscribeToDefaultPerms ($op, Permissible $permissible)
Parameters
boolean $op
Permissible $permissible
Definition at line 467 of file PluginManager.php.
pocketmine\plugin\PluginManager::subscribeToPermission ($permission, Permissible $permissible)
Parameters
string $permission
Permissible $permissible
Definition at line 423 of file PluginManager.php.
pocketmine\plugin\PluginManager::unsubscribeFromDefaultPerms ($op, Permissible $permissible)
Parameters
boolean $op
Permissible $permissible
Definition at line 479 of file PluginManager.php.
pocketmine\plugin\PluginManager::unsubscribeFromPermission ($permission, Permissible $permissible)
Parameters
string $permission
Permissible $permissible
Definition at line 434 of file PluginManager.php.
pocketmine\plugin\PluginManager::useTimings ()
Returns
bool
Definition at line 739 of file PluginManager.php.
The documentation for this class was generated from the following file:
PluginManager.php