PocketMine-MP: pocketmine\event\Timings Class Reference
pocketmine\event\Timings Class Reference
Static Public Member Functions
static init ()
static getPluginTaskTimings (TaskHandler $task, $period)
static getEntityTimings (Entity $entity)
static getTileEntityTimings (Tile $tile)
Static Public Attributes
static $serverTickTimer
static $playerListTimer
static $connectionTimer
static $tickablesTimer
static $schedulerTimer
static $chunkIOTickTimer
static $timeUpdateTimer
static $serverCommandTimer
static $worldSaveTimer
static $entityMoveTimer
static $tickEntityTimer
static $activatedEntityTimer
static $tickTileEntityTimer
static $timerEntityBaseTick
static $timerEntityAI
static $timerEntityAICollision
static $timerEntityAIMove
static $timerEntityTickRest
static $processQueueTimer
static $schedulerSyncTimer
static $playerCommandTimer
static $entityTypeTimingMap = []
static $tileEntityTypeTimingMap = []
static $pluginTaskTimingMap = []
Detailed Description
Definition at line 31 of file Timings.php.
Member Function Documentation
static pocketmine\event\Timings::getEntityTimings (Entity $entity) static
Parameters
Entity $entity
Returns
TimingsHandler
Definition at line 158 of file Timings.php.
static pocketmine\event\Timings::getPluginTaskTimings (TaskHandler $task, $period) static
Parameters
TaskHandler $task
$period
Returns
TimingsHandler
Definition at line 126 of file Timings.php.
References pocketmine\scheduler\PluginTask\getOwner(), pocketmine\scheduler\TaskHandler\getTask(), and pocketmine\scheduler\TaskHandler\getTaskName().
Referenced by pocketmine\scheduler\TaskHandler\__construct().
static pocketmine\event\Timings::getTileEntityTimings (Tile $tile) static
Parameters
Tile $tile
Returns
TimingsHandler
Definition at line 172 of file Timings.php.
The documentation for this class was generated from the following file:
Timings.php