PocketMine-MP: pocketmine\command\defaults\ReloadCommand Class Reference
pocketmine\command\defaults\ReloadCommand Class Reference
Public Member Functions
__construct ($name)
execute (CommandSender $sender, $currentAlias, array $args)
getName ()
getPermission ()
setPermission ($permission)
testPermission (CommandSender $target)
testPermissionSilent (CommandSender $target)
getLabel ()
setLabel ($name)
register (CommandMap $commandMap)
unregister (CommandMap $commandMap)
isRegistered ()
getAliases ()
getPermissionMessage ()
getDescription ()
getUsage ()
setAliases (array $aliases)
setDescription ($description)
setPermissionMessage ($permissionMessage)
setUsage ($usage)
__toString ()
Static Public Member Functions
static broadcastCommandMessage (CommandSender $source, $message, $sendToSource=true)
Public Attributes
const MAX_COORD = 30000000
const MIN_COORD = -30000000
$timings
Protected Member Functions
getInteger (CommandSender $sender, $value, $min=self::MIN_COORD, $max=self::MAX_COORD)
getRelativeDouble ($original, CommandSender $sender, $input, $min=self::MIN_COORD, $max=self::MAX_COORD)
getDouble (CommandSender $sender, $value, $min=self::MIN_COORD, $max=self::MAX_COORD)
Protected Attributes
$description = ""
$usageMessage
Detailed Description
Definition at line 28 of file ReloadCommand.php.
Member Function Documentation
pocketmine\command\Command::__toString () inherited
Returns
string
Definition at line 312 of file Command.php.
static pocketmine\command\Command::broadcastCommandMessage (CommandSender $source, $message, $sendToSource = true) static inherited
Parameters
CommandSender $source
string $message
bool $sendToSource
Definition at line 287 of file Command.php.
References pocketmine\Server\getInstance(), pocketmine\command\CommandSender\getName(), and pocketmine\command\CommandSender\sendMessage().
pocketmine\command\Command::getAliases () inherited
Returns
string[]
Definition at line 226 of file Command.php.
pocketmine\command\Command::getDescription () inherited
Returns
string
Definition at line 240 of file Command.php.
pocketmine\command\Command::getLabel () inherited
Returns
string
Definition at line 157 of file Command.php.
pocketmine\command\Command::getName () inherited
Returns
string
Definition at line 98 of file Command.php.
pocketmine\command\Command::getPermission () inherited
Returns
string
Definition at line 105 of file Command.php.
pocketmine\command\Command::getPermissionMessage () inherited
Returns
string
Definition at line 233 of file Command.php.
pocketmine\command\Command::getUsage () inherited
Returns
string
Definition at line 247 of file Command.php.
pocketmine\command\Command::isRegistered () inherited
Returns
bool
Definition at line 219 of file Command.php.
Referenced by pocketmine\command\Command\setAliases().
pocketmine\command\Command::register (CommandMap $commandMap) inherited
Registers the command into a Command map
Parameters
CommandMap $commandMap
Returns
bool
Definition at line 180 of file Command.php.
pocketmine\command\Command::setAliases (array $aliases) inherited
Parameters
string[] $aliases
Definition at line 254 of file Command.php.
References pocketmine\command\Command\isRegistered().
pocketmine\command\Command::setDescription ($description) inherited
Parameters
string $description
Definition at line 264 of file Command.php.
pocketmine\command\Command::setPermission ($permission) inherited
Parameters
string | null $permission
Definition at line 112 of file Command.php.
pocketmine\command\Command::setPermissionMessage ($permissionMessage) inherited
Parameters
string $permissionMessage
Definition at line 271 of file Command.php.
pocketmine\command\Command::setUsage ($usage) inherited
Parameters
string $usage
Definition at line 278 of file Command.php.
pocketmine\command\Command::testPermission (CommandSender $target) inherited
Parameters
CommandSender $target
Returns
bool
Definition at line 121 of file Command.php.
References pocketmine\command\CommandSender\sendMessage(), and pocketmine\command\Command\testPermissionSilent().
pocketmine\command\Command::testPermissionSilent (CommandSender $target) inherited
Parameters
CommandSender $target
Returns
bool
Definition at line 140 of file Command.php.
References pocketmine\permission\Permissible\hasPermission().
Referenced by pocketmine\command\Command\testPermission().
pocketmine\command\Command::unregister (CommandMap $commandMap) inherited
Parameters
CommandMap $commandMap
Returns
bool
Definition at line 195 of file Command.php.
The documentation for this class was generated from the following file:
ReloadCommand.php