PocketMine-MP: pocketmine\block\WallSign Class Reference
pocketmine\block\WallSign Class Reference
Public Member Functions
__construct ($meta=0)
onUpdate ($type)
place (Item $item, Block $block, Block $target, $face, $fx, $fy, $fz, Player $player=null)
onBreak (Item $item)
getDrops (Item $item)
isBreakable (Item $item)
onActivate (Item $item, Player $player=null)
getHardness ()
getName ()
getID ()
getDamage ()
setDamage ($meta)
position (Position $v)
getBreakTime (Item $item)
getSide ($side, $step=1)
__toString ()
collidesWithBB (AxisAlignedBB $bb, &$list=array())
getBoundingBox ()
setMetadata ($metadataKey, MetadataValue $metadataValue)
getMetadata ($metadataKey)
hasMetadata ($metadataKey)
removeMetadata ($metadataKey, Plugin $plugin)
Static Public Member Functions
static init ()
static get ($id, $meta=0, Position $pos=null)
Public Attributes
const AIR = 0
const STONE = 1
const GRASS = 2
const DIRT = 3
const COBBLESTONE = 4
const COBBLE = 4
const PLANK = 5
const PLANKS = 5
const WOODEN_PLANK = 5
const WOODEN_PLANKS = 5
const SAPLING = 6
const SAPLINGS = 6
const BEDROCK = 7
const WATER = 8
const STILL_WATER = 9
const LAVA = 10
const STILL_LAVA = 11
const SAND = 12
const GRAVEL = 13
const GOLD_ORE = 14
const IRON_ORE = 15
const COAL_ORE = 16
const WOOD = 17
const TRUNK = 17
const LOG = 17
const LEAVES = 18
const LEAVE = 18
const SPONGE = 19
const GLASS = 20
const LAPIS_ORE = 21
const LAPIS_BLOCK = 22
const SANDSTONE = 24
const BED_BLOCK = 26
const COBWEB = 30
const TALL_GRASS = 31
const BUSH = 32
const DEAD_BUSH = 32
const WOOL = 35
const DANDELION = 37
const ROSE = 38
const POPPY = 38
const BROWN_MUSHROOM = 39
const RED_MUSHROOM = 40
const GOLD_BLOCK = 41
const IRON_BLOCK = 42
const DOUBLE_SLAB = 43
const DOUBLE_SLABS = 43
const SLAB = 44
const SLABS = 44
const BRICKS = 45
const BRICKS_BLOCK = 45
const TNT = 46
const BOOKSHELF = 47
const MOSS_STONE = 48
const MOSSY_STONE = 48
const OBSIDIAN = 49
const TORCH = 50
const FIRE = 51
const WOOD_STAIRS = 53
const WOODEN_STAIRS = 53
const OAK_WOOD_STAIRS = 53
const OAK_WOODEN_STAIRS = 53
const CHEST = 54
const DIAMOND_ORE = 56
const DIAMOND_BLOCK = 57
const CRAFTING_TABLE = 58
const WORKBENCH = 58
const WHEAT_BLOCK = 59
const FARMLAND = 60
const FURNACE = 61
const BURNING_FURNACE = 62
const LIT_FURNACE = 62
const SIGN_POST = 63
const DOOR_BLOCK = 64
const WOODEN_DOOR_BLOCK = 64
const WOOD_DOOR_BLOCK = 64
const LADDER = 65
const COBBLE_STAIRS = 67
const COBBLESTONE_STAIRS = 67
const WALL_SIGN = 68
const IRON_DOOR_BLOCK = 71
const REDSTONE_ORE = 73
const GLOWING_REDSTONE_ORE = 74
const LIT_REDSTONE_ORE = 74
const SNOW = 78
const SNOW_LAYER = 78
const ICE = 79
const SNOW_BLOCK = 80
const CACTUS = 81
const CLAY_BLOCK = 82
const REEDS = 83
const SUGARCANE_BLOCK = 83
const FENCE = 85
const PUMPKIN = 86
const NETHERRACK = 87
const SOUL_SAND = 88
const GLOWSTONE = 89
const GLOWSTONE_BLOCK = 89
const LIT_PUMPKIN = 91
const JACK_O_LANTERN = 91
const CAKE_BLOCK = 92
const TRAPDOOR = 96
const STONE_BRICKS = 98
const STONE_BRICK = 98
const IRON_BAR = 101
const IRON_BARS = 101
const GLASS_PANE = 102
const GLASS_PANEL = 102
const MELON_BLOCK = 103
const PUMPKIN_STEM = 104
const MELON_STEM = 105
const FENCE_GATE = 107
const BRICK_STAIRS = 108
const STONE_BRICK_STAIRS = 109
const NETHER_BRICKS = 112
const NETHER_BRICK_BLOCK = 112
const NETHER_BRICKS_STAIRS = 114
const SANDSTONE_STAIRS = 128
const EMERALD_ORE = 129
const EMERALD_BLOCK = 133
const SPRUCE_WOOD_STAIRS = 134
const SPRUCE_WOODEN_STAIRS = 134
const BIRCH_WOOD_STAIRS = 135
const BIRCH_WOODEN_STAIRS = 135
const JUNGLE_WOOD_STAIRS = 136
const JUNGLE_WOODEN_STAIRS = 136
const COBBLE_WALL = 139
const STONE_WALL = 139
const COBBLESTONE_WALL = 139
const CARROT_BLOCK = 141
const POTATO_BLOCK = 142
const QUARTZ_BLOCK = 155
const QUARTZ_STAIRS = 156
const DOUBLE_WOOD_SLAB = 157
const DOUBLE_WOODEN_SLAB = 157
const DOUBLE_WOOD_SLABS = 157
const DOUBLE_WOODEN_SLABS = 157
const WOOD_SLAB = 158
const WOODEN_SLAB = 158
const WOOD_SLABS = 158
const WOODEN_SLABS = 158
const STAINED_CLAY = 159
const STAINED_HARDENED_CLAY = 159
const LEAVES2 = 161
const LEAVE2 = 161
const WOOD2 = 162
const TRUNK2 = 162
const LOG2 = 162
const ACACIA_WOOD_STAIRS = 163
const ACACIA_WOODEN_STAIRS = 163
const DARK_OAK_WOOD_STAIRS = 164
const DARK_OAK_WOODEN_STAIRS = 164
const HAY_BALE = 170
const CARPET = 171
const HARDENED_CLAY = 172
const COAL_BLOCK = 173
const BEETROOT_BLOCK = 244
const STONECUTTER = 245
const GLOWING_OBSIDIAN = 246
const NETHER_REACTOR = 247
$isActivable = false
$breakable = true
$isFlowable = false
$isSolid = true
$isTransparent = false
$isReplaceable = false
$isPlaceable = true
$hasPhysics = false
$isLiquid = false
$isFullBlock = true
$x = 0
$y = 0
$z = 0
$frictionFactor = 0.6
Static Public Attributes
static $creative
static $list = []
Protected Attributes
$id
$meta
$name
$breakTime
$hardness
Detailed Description
Definition at line 25 of file WallSign.php.
Member Function Documentation
pocketmine\block\Block::__toString () [final, inherited]
Returns:
string
Definition at line 790 of file block/Block.php.
pocketmine\block\Block::collidesWithBB (AxisAlignedBB $ bb, &$ list = array()) [inherited]
Checks for collision against an AxisAlignedBB
Parameters:
AxisAlignedBB $bb
Block[] $list
Definition at line 818 of file block/Block.php.
static pocketmine\block\Block::get ($ id, $ meta = 0, Position $ pos = null) [static, inherited]
Parameters:
int $id
int $meta
Position $pos
Returns:
Block
Definition at line 663 of file block/Block.php.
pocketmine\block\Block::getBoundingBox () [inherited]
Returns:
AxisAlignedBB
Reimplemented in pocketmine\block\Air.
Definition at line 828 of file block/Block.php.
pocketmine\block\Block::getBreakTime (Item $ item) [inherited]
Returns the seconds that this block takes to be broken using an specific Item
Parameters:
Item $item
Returns:
float
Reimplemented in pocketmine\block\Slab, pocketmine\block\BurningFurnace, pocketmine\block\WoodSlab, pocketmine\block\StainedClay, pocketmine\block\Stone, pocketmine\block\GlowingRedstoneOre, pocketmine\block\DoubleSlab, pocketmine\block\DoubleWoodSlab, pocketmine\block\StoneBricks, pocketmine\block\Ice, pocketmine\block\Quartz, pocketmine\block\Sandstone, pocketmine\block\IronDoor, pocketmine\block\Bricks, pocketmine\block\Coal, pocketmine\block\CoalOre, pocketmine\block\Cobblestone, pocketmine\block\Diamond, pocketmine\block\DiamondOre, pocketmine\block\Emerald, pocketmine\block\EmeraldOre, pocketmine\block\Gold, pocketmine\block\GoldOre, pocketmine\block\HardenedClay, pocketmine\block\Iron, pocketmine\block\IronOre, pocketmine\block\Lapis, pocketmine\block\LapisOre, pocketmine\block\MossStone, pocketmine\block\NetherBrick, pocketmine\block\Netherrack, pocketmine\block\Obsidian, and pocketmine\block\WoodStairs.
Definition at line 766 of file block/Block.php.
pocketmine\block\Block::getDamage () [final, inherited]
Returns:
int
Definition at line 714 of file block/Block.php.
Referenced by pocketmine\block\Chest\place(), pocketmine\block\WoodSlab\place(), and pocketmine\block\Slab\place().
pocketmine\block\SignPost::getDrops (Item $ item) [inherited]
Returns an array of Item objects to be dropped
Parameters:
Item $item
Returns:
array
Reimplemented from pocketmine\block\Block.
Definition at line 80 of file SignPost.php.
pocketmine\block\Block::getHardness () [final, inherited]
Returns:
int
Definition at line 693 of file block/Block.php.
pocketmine\block\Block::getID () [final, inherited]
Returns:
int
Definition at line 707 of file block/Block.php.
Referenced by pocketmine\block\Trapdoor\place(), pocketmine\block\WoodSlab\place(), and pocketmine\block\Slab\place().
pocketmine\block\Block::getName () [final, inherited]
Returns:
string
Definition at line 700 of file block/Block.php.
pocketmine\block\Block::getSide ($ side, $ step = 1) [inherited]
Returns the Block on the side $side, works like Vector3::side()
Parameters:
int $side
int $step
Returns:
Block
Definition at line 778 of file block/Block.php.
pocketmine\block\Generic::isBreakable (Item $ item) [inherited]
Returns if the item can be broken with an specific Item
Parameters:
Item $item
Returns:
bool
Reimplemented from pocketmine\block\Block.
Reimplemented in pocketmine\block\Bedrock.
Definition at line 44 of file Generic.php.
pocketmine\block\Generic::onActivate (Item $ item, Player $ player = null) [inherited]
Do actions when activated by Item. Returns if it has done anything
Parameters:
Item $item
Player $player
Returns:
bool
Reimplemented from pocketmine\block\Block.
Reimplemented in pocketmine\block\Chest, pocketmine\block\Door, pocketmine\block\PumpkinStem, pocketmine\block\MelonStem, pocketmine\block\BurningFurnace, pocketmine\block\Trapdoor, pocketmine\block\Cake, pocketmine\block\Sapling, pocketmine\block\Grass, pocketmine\block\FenceGate, pocketmine\block\Beetroot, pocketmine\block\Carrot, pocketmine\block\Potato, pocketmine\block\Wheat, pocketmine\block\Sugarcane, pocketmine\block\Bed, pocketmine\block\Workbench, pocketmine\block\Dirt, pocketmine\block\Stonecutter, and pocketmine\block\TNT.
Definition at line 76 of file Generic.php.
pocketmine\block\SignPost::onBreak (Item $ item) [inherited]
Do the actions needed so the block is broken with the Item
Parameters:
Item $item
Returns:
mixed
Reimplemented from pocketmine\block\Generic.
Definition at line 74 of file SignPost.php.
pocketmine\block\WallSign::onUpdate ($ type)
Fires a block update on the Block
Parameters:
int $type
Returns:
void
Reimplemented from pocketmine\block\SignPost.
Definition at line 30 of file WallSign.php.
pocketmine\block\SignPost::place (Item $ item, Block $ block, Block $ target, $ face, $ fx, $ fy, $ fz, Player $ player = null) [inherited]
Places the Block, using block space and block target, and side. Returns if the block has been placed.
Parameters:
Item $item
Block $block
Block $target
int $face
float $fx
float $fy
float $fz
Player $player = null
Returns:
bool
Reimplemented from pocketmine\block\Generic.
Definition at line 36 of file SignPost.php.
pocketmine\block\Block::position (Position $ v) [final, inherited]
Sets the block position to a new Position object
Parameters:
Position $v
Exceptions:
\RuntimeException
Definition at line 732 of file block/Block.php.
pocketmine\block\Block::setDamage ($ meta) [final, inherited]
Parameters:
int $meta
Definition at line 721 of file block/Block.php.
The documentation for this class was generated from the following file:
WallSign.php