PocketMine-MP: pocketmine\level\format\Chunk Interface Reference
pocketmine\level\format\Chunk Interface Reference
Public Member Functions
isSectionEmpty ($fY)
getSection ($fY)
setSection ($fY, ChunkSection $section)
getSections ()
getX ()
getZ ()
setX ($x)
setZ ($z)
getProvider ()
setProvider (LevelProvider $provider)
getBlock ($x, $y, $z, &$blockId, &$meta=null)
setBlock ($x, $y, $z, $blockId=null, $meta=null)
getBlockId ($x, $y, $z)
setBlockId ($x, $y, $z, $id)
getBlockData ($x, $y, $z)
setBlockData ($x, $y, $z, $data)
getBlockSkyLight ($x, $y, $z)
setBlockSkyLight ($x, $y, $z, $level)
getBlockLight ($x, $y, $z)
setBlockLight ($x, $y, $z, $level)
getHighestBlockAt ($x, $z)
getBiomeId ($x, $z)
setBiomeId ($x, $z, $biomeId)
getBiomeColor ($x, $z)
getBlockIdColumn ($x, $z)
getBlockDataColumn ($x, $z)
getBlockSkyLightColumn ($x, $z)
getBlockLightColumn ($x, $z)
setBiomeColor ($x, $z, $R, $G, $B)
isPopulated ()
setPopulated ($value=1)
isGenerated ()
setGenerated ($value=1)
addEntity (Entity $entity)
removeEntity (Entity $entity)
addTile (Tile $tile)
removeTile (Tile $tile)
getEntities ()
getTiles ()
isLoaded ()
load ($generate=true)
unload ($save=true, $safe=true)
getBiomeIdArray ()
getBiomeColorArray ()
getBlockIdArray ()
getBlockDataArray ()
getBlockSkyLightArray ()
getBlockLightArray ()
toBinary ()
Static Public Member Functions
static fromBinary ($data, LevelProvider $provider=null)
Public Attributes
const SECTION_COUNT = 8
Detailed Description
Definition at line 24 of file Chunk.php.
Member Function Documentation
pocketmine\level\format\FullChunk::addEntity (Entity $entity) inherited
Parameters
Entity $entity
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::addTile (Tile $tile) inherited
Parameters
Tile $tile
Implemented in pocketmine\level\format\generic\BaseFullChunk.
static pocketmine\level\format\FullChunk::fromBinary ($data, LevelProvider $provider = null) static inherited
Parameters
string $data
LevelProvider $provider
Returns
FullChunk
Implemented in pocketmine\level\format\mcregion\Chunk, and pocketmine\level\format\anvil\Chunk.
pocketmine\level\format\FullChunk::getBiomeColor ($x, $z) inherited
Parameters
int $x
int $z
Returns
int[] RGB bytes
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::getBiomeColorArray () inherited
Returns
int[]
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::getBiomeId ($x, $z) inherited
Parameters
int $x 0-15
int $z 0-15
Returns
int 0-255
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::getBiomeIdArray () inherited
Returns
string[]
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::getBlock ($x, $y, $z, & $blockId, & $meta = null) inherited
Modifies $blockId and $meta
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int &$blockId
int &$meta
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::getBlockData ($x, $y, $z) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-15
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::getBlockId ($x, $y, $z) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-255
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::getBlockLight ($x, $y, $z) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-15
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::getBlockSkyLight ($x, $y, $z) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-15
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::getEntities () inherited
Returns
[]
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::getHighestBlockAt ($x, $z) inherited
Parameters
int $x 0-15
int $z 0-15
Returns
int 0-127
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::getProvider () inherited
Returns
LevelProvider
Implemented in pocketmine\level\format\generic\BaseFullChunk.
Referenced by pocketmine\event\level\ChunkEvent\__construct().
pocketmine\level\format\Chunk::getSection ($fY)
Parameters
int $fY 0-7
Returns
ChunkSection
Implemented in pocketmine\level\format\generic\BaseChunk.
pocketmine\level\format\Chunk::getSections ()
Returns
ChunkSection[]
Implemented in pocketmine\level\format\generic\BaseChunk.
pocketmine\level\format\FullChunk::getTiles () inherited
Returns
[]
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::getX () inherited
Returns
int
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::getZ () inherited
Returns
int
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::isLoaded () inherited
Returns
bool
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\Chunk::isSectionEmpty ($fY)
Tests whether a section (mini-chunk) is empty
Parameters
$fY 0-7, (Y / 16)
Returns
bool
Implemented in pocketmine\level\format\generic\BaseChunk.
pocketmine\level\format\FullChunk::load ($generate = true) inherited
Loads the chunk
Parameters
bool $generate If the chunk does not exist, generate it
Returns
bool
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::removeEntity (Entity $entity) inherited
Parameters
Entity $entity
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::removeTile (Tile $tile) inherited
Parameters
Tile $tile
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::setBiomeColor ($x, $z, $R, $G, $B) inherited
Parameters
int $x 0-15
int $z 0-15
int $R 0-255
int $G 0-255
int $B 0-255
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::setBiomeId ($x, $z, $biomeId) inherited
Parameters
int $x 0-15
int $z 0-15
int $biomeId 0-255
Implemented in pocketmine\level\format\generic\BaseFullChunk.
pocketmine\level\format\FullChunk::setBlock ($x, $y, $z, $blockId = null, $meta = null) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $blockId,if null, do not change
int $meta 0-15, if null, do not change
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::setBlockData ($x, $y, $z, $data) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $data 0-15
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::setBlockId ($x, $y, $z, $id) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $id 0-255
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::setBlockLight ($x, $y, $z, $level) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $level 0-15
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::setBlockSkyLight ($x, $y, $z, $level) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $level 0-15
Implemented in pocketmine\level\format\generic\BaseChunk, and pocketmine\level\format\mcregion\Chunk.
pocketmine\level\format\FullChunk::setProvider (LevelProvider $provider) inherited
Parameters
LevelProvider $provider
Implemented in pocketmine\level\format\generic\BaseFullChunk.
Referenced by pocketmine\level\format\anvil\Anvil\setChunk(), and pocketmine\level\format\mcregion\McRegion\setChunk().
pocketmine\level\format\Chunk::setSection ($fY, ChunkSection $section)
Parameters
int $fY 0-7
ChunkSection $section
Returns
boolean
Implemented in pocketmine\level\format\generic\BaseChunk.
pocketmine\level\format\FullChunk::unload ($save = true, $safe = true) inherited
Parameters
bool $save
bool $safe If false, unload the chunk even if players are nearby
Returns
bool
Implemented in pocketmine\level\format\generic\BaseFullChunk.
The documentation for this interface was generated from the following file:
Chunk.php