PocketMine-MP: pocketmine\level\generator\GenerationChunkManager Class Reference
pocketmine\level\generator\GenerationChunkManager Class Reference
Public Member Functions
__construct (GenerationManager $manager, $levelID, $seed, $class, array $options)
getSeed ()
getId ()
getChunk ($chunkX, $chunkZ)
getChangedChunks ()
cleanChangedChunks ()
cleanChangedChunk ($index)
doGarbageCollection ()
generateChunk ($chunkX, $chunkZ)
populateChunk ($chunkX, $chunkZ)
isChunkGenerated ($chunkX, $chunkZ)
isChunkPopulated ($chunkX, $chunkZ)
setChunkGenerated ($chunkX, $chunkZ)
setChunkPopulated ($chunkX, $chunkZ)
setChunk ($chunkX, $chunkZ, FullChunk $chunk)
getBlockIdAt ($x, $y, $z)
setBlockIdAt ($x, $y, $z, $id)
getBlockDataAt ($x, $y, $z)
setBlockDataAt ($x, $y, $z, $data)
shutdown ()
Protected Member Functions
requestChunk ($chunkX, $chunkZ)
Protected Attributes
$levelID
$chunks = []
$generator
$manager
$seed
$changes = []
Detailed Description
Definition at line 30 of file GenerationChunkManager.php.
Member Function Documentation
pocketmine\level\generator\GenerationChunkManager::getBlockDataAt ($x, $y, $z)
Gets the raw block metadata
Parameters
int $x
int $y
int $z
Returns
int 0-15
Implements pocketmine\level\ChunkManager.
Definition at line 241 of file GenerationChunkManager.php.
References pocketmine\level\generator\GenerationChunkManager\getChunk().
pocketmine\level\generator\GenerationChunkManager::getBlockIdAt ($x, $y, $z)
Gets the raw block id.
Parameters
int $x
int $y
int $z
Returns
int 0-255
Implements pocketmine\level\ChunkManager.
Definition at line 209 of file GenerationChunkManager.php.
References pocketmine\level\generator\GenerationChunkManager\getChunk().
pocketmine\level\generator\GenerationChunkManager::getChangedChunks ()
Returns
FullChunk[]
Definition at line 94 of file GenerationChunkManager.php.
pocketmine\level\generator\GenerationChunkManager::getChunk ($chunkX, $chunkZ)
Parameters
$chunkX
$chunkZ
Returns
FullChunk
Exceptions
ChunkException
Definition at line 81 of file GenerationChunkManager.php.
References pocketmine\level\Level\chunkHash().
Referenced by pocketmine\level\generator\GenerationChunkManager\getBlockDataAt(), pocketmine\level\generator\GenerationChunkManager\getBlockIdAt(), pocketmine\level\generator\GenerationChunkManager\setBlockDataAt(), and pocketmine\level\generator\GenerationChunkManager\setBlockIdAt().
pocketmine\level\generator\GenerationChunkManager::getId ()
Returns
int
Definition at line 69 of file GenerationChunkManager.php.
pocketmine\level\generator\GenerationChunkManager::getSeed ()
Returns
int
Definition at line 62 of file GenerationChunkManager.php.
pocketmine\level\generator\GenerationChunkManager::setBlockDataAt ($x, $y, $z, $data)
Sets the raw block metadata.
Parameters
int $x
int $y
int $z
int $data 0-15
Implements pocketmine\level\ChunkManager.
Definition at line 257 of file GenerationChunkManager.php.
References pocketmine\level\generator\GenerationChunkManager\getChunk().
pocketmine\level\generator\GenerationChunkManager::setBlockIdAt ($x, $y, $z, $id)
Sets the raw block id.
Parameters
int $x
int $y
int $z
int $id 0-255
Implements pocketmine\level\ChunkManager.
Definition at line 225 of file GenerationChunkManager.php.
References pocketmine\level\generator\GenerationChunkManager\getChunk().
pocketmine\level\generator\GenerationChunkManager::setChunk ($chunkX, $chunkZ, FullChunk $chunk)
Parameters
int $chunkX
int $chunkZ
FullChunk $chunk
Definition at line 192 of file GenerationChunkManager.php.
References pocketmine\level\Level\chunkHash().
The documentation for this class was generated from the following file:
GenerationChunkManager.php