PocketMine-MP: pocketmine\plugin\RegisteredListener Class Reference
pocketmine\plugin\RegisteredListener Class Reference
Public Member Functions
__construct (Listener $listener, EventExecutor $executor, $priority, Plugin $plugin, $ignoreCancelled, TimingsHandler $timings)
getListener ()
getPlugin ()
getPriority ()
callEvent (Event $event)
isIgnoringCancelled ()
Detailed Description
Definition at line 29 of file RegisteredListener.php.
Constructor & Destructor Documentation
pocketmine\plugin\RegisteredListener::__construct (Listener $listener, EventExecutor $executor, $priority, Plugin $plugin, $ignoreCancelled, TimingsHandler $timings)
Parameters
Listener $listener
EventExecutor $executor
int $priority
Plugin $plugin
boolean $ignoreCancelled
TimingsHandler $timings
Definition at line 58 of file RegisteredListener.php.
Member Function Documentation
pocketmine\plugin\RegisteredListener::callEvent (Event $event)
Parameters
Event $event
Definition at line 91 of file RegisteredListener.php.
References pocketmine\event\Event\isCancelled(), and pocketmine\plugin\RegisteredListener\isIgnoringCancelled().
pocketmine\plugin\RegisteredListener::getListener ()
Returns
Listener
Definition at line 70 of file RegisteredListener.php.
pocketmine\plugin\RegisteredListener::getPlugin ()
Returns
Plugin
Definition at line 77 of file RegisteredListener.php.
pocketmine\plugin\RegisteredListener::getPriority ()
Returns
int
Definition at line 84 of file RegisteredListener.php.
pocketmine\plugin\RegisteredListener::isIgnoringCancelled ()
Returns
bool
Definition at line 107 of file RegisteredListener.php.
Referenced by pocketmine\plugin\RegisteredListener\callEvent().
The documentation for this class was generated from the following file:
RegisteredListener.php