PocketMine-MP: ThreadedLoggerAttachment Class Reference
ThreadedLoggerAttachment Class Reference
Public Member Functions
call ($level, $message)
addAttachment (\ThreadedLoggerAttachment $attachment)
removeAttachment (\ThreadedLoggerAttachment $attachment)
removeAttachments ()
getAttachments ()
chunk ($size)
count ()
getTerminationInfo ()
isRunning ()
isTerminated ()
isWaiting ()
lock ()
merge ($from, $overwrite=true)
notify ()
offsetGet ($offset)
offsetSet ($offset, $value)
offsetExists ($offset)
offsetUnset ($offset)
pop ()
run ()
shift ()
synchronized (\Closure $function, $args=null)
unlock ()
wait ($timeout)
log ($level, $message)
Protected Attributes
$attachment = null
Detailed Description
Definition at line 22 of file ThreadedLoggerAttachment.php.
Member Function Documentation
ThreadedLoggerAttachment::addAttachment (\ThreadedLoggerAttachment $ attachment)
Parameters:
ThreadedLoggerAttachment $attachment
Definition at line 41 of file ThreadedLoggerAttachment.php.
Referenced by removeAttachment().
ThreadedLoggerAttachment::call ($ level, $ message) [final]
Parameters:
mixed $level
string $message
Definition at line 31 of file ThreadedLoggerAttachment.php.
References LoggerAttachment\log().
Threaded::chunk ($ size) [inherited]
Fetches a chunk of the objects properties table of the given size
Parameters:
int $size The number of items to fetch
array An array of items from the objects member table
Definition at line 83 of file pthreads.php.
Threaded::count () [inherited]
{}
Definition at line 89 of file pthreads.php.
ThreadedLoggerAttachment::getAttachments ()
Returns:
[]
Definition at line 73 of file ThreadedLoggerAttachment.php.
Referenced by AttachableThreadedLogger\removeAttachment(), and removeAttachment().
Threaded::getTerminationInfo () [inherited]
Retrieves terminal error information from the referenced object
array|bool array containing the termination conditions of the referenced object
Definition at line 98 of file pthreads.php.
Threaded::isRunning () [inherited]
Tell if the referenced object is executing
bool A boolean indication of state
Definition at line 107 of file pthreads.php.
Threaded::isTerminated () [inherited]
Tell if the referenced object exited, suffered fatal errors, or threw uncaught exceptions during execution
bool A boolean indication of state
Definition at line 116 of file pthreads.php.
Threaded::isWaiting () [inherited]
Tell if the referenced object is waiting for notification
bool A boolean indication of state
Definition at line 125 of file pthreads.php.
Threaded::lock () [inherited]
Lock the referenced objects property table
bool A boolean indication of state
Definition at line 134 of file pthreads.php.
LoggerAttachment::log ($ level, $ message) [inherited]
Parameters:
mixed $level
string $message
Referenced by call().
Threaded::merge ($ from, $ overwrite = true) [inherited]
Merges data into the current object
Parameters:
mixed $from The data to merge
bool $overwrite Overwrite existing keys flag, by default true
bool A boolean indication of success
Definition at line 146 of file pthreads.php.
Threaded::notify () [inherited]
Send notification to the referenced object
bool A boolean indication of success
Definition at line 155 of file pthreads.php.
Threaded::offsetExists ($ offset) [inherited]
{}
Definition at line 173 of file pthreads.php.
Threaded::offsetGet ($ offset) [inherited]
{}
Definition at line 161 of file pthreads.php.
Threaded::offsetSet ($ offset, $ value) [inherited]
{}
Definition at line 167 of file pthreads.php.
Threaded::offsetUnset ($ offset) [inherited]
{}
Definition at line 179 of file pthreads.php.
Threaded::pop () [inherited]
Pops an item from the objects property table
mixed The last item from the objects properties table
Definition at line 188 of file pthreads.php.
ThreadedLoggerAttachment::removeAttachment (\ThreadedLoggerAttachment $ attachment)
Parameters:
ThreadedLoggerAttachment $attachment
Definition at line 52 of file ThreadedLoggerAttachment.php.
References addAttachment(), and getAttachments().
Threaded::run () [inherited]
The programmer should always implement the run method for objects that are intended for execution.
void The methods return value, if used, will be ignored
Reimplemented in pocketmine\utils\MainLogger, raklib\server\RakLibServer, pocketmine\level\generator\GenerationThread, pocketmine\network\rcon\RCONInstance, pocketmine\command\CommandReader, pocketmine\scheduler\AsyncTask, and pocketmine\scheduler\AsyncWorker.
Definition at line 197 of file pthreads.php.
Threaded::shift () [inherited]
Shifts an item from the objects properties table
mixed The first item from the objects properties table
Definition at line 206 of file pthreads.php.
Threaded::synchronized (\Closure $ function, $ args = null) [inherited]
Executes the block while retaining the synchronization lock for the current context.
Parameters:
\Closure $function The block of code to execute
mixed $args ... Variable length list of arguments to use as function arguments to the block
mixed The return value from the block
Definition at line 218 of file pthreads.php.
Threaded::unlock () [inherited]
Unlock the referenced objects storage for the calling context
bool A boolean indication of success
Definition at line 227 of file pthreads.php.
Threaded::wait ($ timeout) [inherited]
Waits for notification from the Stackable
Parameters:
int $timeout An optional timeout in microseconds
bool A boolean indication of success
Definition at line 238 of file pthreads.php.
The documentation for this class was generated from the following file:
ThreadedLoggerAttachment.php