PocketMine-MP: pocketmine\scheduler\TaskHandler Class Reference
pocketmine\scheduler\TaskHandler Class Reference
Public Member Functions
__construct ($timingName, Task $task, $taskId, $delay=-1, $period=-1)
isCancelled ()
getNextRun ()
setNextRun ($ticks)
getTaskId ()
getTask ()
getDelay ()
isDelayed ()
isRepeating ()
getPeriod ()
cancel ()
remove ()
run ($currentTick)
getTaskName ()
Public Attributes
$timings
$timingName = null
Protected Attributes
$task
$taskId
$delay
$period
$nextRun
$cancelled = false
Detailed Description
Definition at line 26 of file TaskHandler.php.
Constructor & Destructor Documentation
pocketmine\scheduler\TaskHandler::__construct ($timingName, Task $task, $taskId, $delay = -1, $period = -1)
Parameters
string $timingName
Task $task
int $taskId
int $delay
int $period
Definition at line 58 of file TaskHandler.php.
References pocketmine\event\Timings\getPluginTaskTimings().
Member Function Documentation
pocketmine\scheduler\TaskHandler::getDelay ()
Returns
int
Definition at line 105 of file TaskHandler.php.
pocketmine\scheduler\TaskHandler::getNextRun ()
Returns
int
Definition at line 77 of file TaskHandler.php.
pocketmine\scheduler\TaskHandler::getPeriod ()
Returns
int
Definition at line 126 of file TaskHandler.php.
pocketmine\scheduler\TaskHandler::getTask ()
Returns
Task
Definition at line 98 of file TaskHandler.php.
Referenced by pocketmine\event\Timings\getPluginTaskTimings().
pocketmine\scheduler\TaskHandler::getTaskId ()
Returns
int
Definition at line 91 of file TaskHandler.php.
pocketmine\scheduler\TaskHandler::getTaskName ()
Returns
string
Definition at line 153 of file TaskHandler.php.
Referenced by pocketmine\event\Timings\getPluginTaskTimings().
pocketmine\scheduler\TaskHandler::isCancelled ()
Returns
bool
Definition at line 70 of file TaskHandler.php.
pocketmine\scheduler\TaskHandler::isDelayed ()
Returns
bool
Definition at line 112 of file TaskHandler.php.
pocketmine\scheduler\TaskHandler::isRepeating ()
Returns
bool
Definition at line 119 of file TaskHandler.php.
pocketmine\scheduler\TaskHandler::run ($currentTick)
Parameters
int $currentTick
Definition at line 146 of file TaskHandler.php.
pocketmine\scheduler\TaskHandler::setNextRun ($ticks)
Parameters
int $ticks
Definition at line 84 of file TaskHandler.php.
The documentation for this class was generated from the following file:
TaskHandler.php