PocketMine-MP: pocketmine\permission\PermissibleBase Class Reference
pocketmine\permission\PermissibleBase Class Reference
Public Member Functions
__construct (ServerOperator $opable)
isOp ()
setOp ($value)
isPermissionSet ($name)
hasPermission ($name)
addAttachment (Plugin $plugin, $name=null, $value=null)
removeAttachment (PermissionAttachment $attachment)
recalculatePermissions ()
clearPermissions ()
getEffectivePermissions ()
Detailed Description
Definition at line 29 of file PermissibleBase.php.
Constructor & Destructor Documentation
pocketmine\permission\PermissibleBase::__construct (ServerOperator $opable)
Parameters
ServerOperator $opable
Definition at line 49 of file PermissibleBase.php.
Member Function Documentation
pocketmine\permission\PermissibleBase::addAttachment (Plugin $plugin, $name = null, $value = null)
//TODO: tick scheduled attachments
Parameters
Plugin $plugin
string $name
bool $value
Returns
PermissionAttachment
Exceptions
PluginException
Implements pocketmine\permission\Permissible.
Definition at line 126 of file PermissibleBase.php.
References pocketmine\plugin\Plugin\getDescription(), and pocketmine\permission\PermissibleBase\recalculatePermissions().
pocketmine\permission\PermissibleBase::getEffectivePermissions ()
Returns
PermissionAttachmentInfo[]
Implements pocketmine\permission\Permissible.
Definition at line 219 of file PermissibleBase.php.
pocketmine\permission\PermissibleBase::hasPermission ($name)
Parameters
Permission | string $name
Returns
bool
Implements pocketmine\permission\Permissible.
Definition at line 96 of file PermissibleBase.php.
References pocketmine\Server\getInstance(), pocketmine\permission\PermissibleBase\isOp(), and pocketmine\permission\PermissibleBase\isPermissionSet().
pocketmine\permission\PermissibleBase::isOp ()
Returns
bool
Implements pocketmine\permission\ServerOperator.
Definition at line 61 of file PermissibleBase.php.
Referenced by pocketmine\permission\PermissibleBase\hasPermission(), and pocketmine\permission\PermissibleBase\recalculatePermissions().
pocketmine\permission\PermissibleBase::isPermissionSet ($name)
Parameters
Permission | string $name
Returns
bool
Implements pocketmine\permission\Permissible.
Definition at line 87 of file PermissibleBase.php.
References pocketmine\permission\Permission\getName().
Referenced by pocketmine\permission\PermissibleBase\hasPermission().
pocketmine\permission\PermissibleBase::recalculatePermissions ()
Returns
void
Implements pocketmine\permission\Permissible.
Definition at line 166 of file PermissibleBase.php.
References pocketmine\Server\getInstance(), and pocketmine\permission\PermissibleBase\isOp().
Referenced by pocketmine\permission\PermissibleBase\addAttachment(), and pocketmine\permission\PermissibleBase\removeAttachment().
pocketmine\permission\PermissibleBase::removeAttachment (PermissionAttachment $attachment)
Parameters
PermissionAttachment $attachment
Exceptions
\Exception
Implements pocketmine\permission\Permissible.
Definition at line 149 of file PermissibleBase.php.
References pocketmine\permission\PermissionAttachment\getRemovalCallback(), and pocketmine\permission\PermissibleBase\recalculatePermissions().
pocketmine\permission\PermissibleBase::setOp ($value)
Parameters
bool $value
Exceptions
\Exception
Implements pocketmine\permission\ServerOperator.
Definition at line 74 of file PermissibleBase.php.
The documentation for this class was generated from the following file:
PermissibleBase.php