PocketMine-MP: pocketmine\utils\MainLogger Class Reference
pocketmine\utils\MainLogger Class Reference
Public Member Functions
__construct ($logFile, $hasANSI=false, $logDebug=false)
emergency ($message)
alert ($message)
critical ($message)
error ($message)
warning ($message)
notice ($message)
info ($message)
debug ($message)
setLogDebug ($logDebug)
log ($level, $message)
shutdown ()
run ()
addAttachment (\ThreadedLoggerAttachment $attachment)
removeAttachment (\ThreadedLoggerAttachment $attachment)
removeAttachments ()
getAttachments ()
detach ()
getCreatorId ()
getThreadId ()
isJoined ()
isStarted ()
join ()
kill ()
start ($options=PTHREADS_INHERIT_ALL)
chunk ($size)
count ()
getTerminationInfo ()
isRunning ()
isTerminated ()
isWaiting ()
lock ()
merge ($from, $overwrite=true)
notify ()
offsetGet ($offset)
offsetSet ($offset, $value)
offsetExists ($offset)
offsetUnset ($offset)
pop ()
shift ()
synchronized (\Closure $function, $args=null)
unlock ()
wait ($timeout)
Static Public Member Functions
static getLogger ()
static getCurrentThread ()
static getCurrentThreadId ()
static globally (Callable $block, $args=null)
Static Public Attributes
static $logger = null
Protected Member Functions
send ($message, $level=-1)
Protected Attributes
$logFile
$logStream
$shutdown
$hasANSI
$logDebug
$attachment = null
Detailed Description
Definition at line 26 of file MainLogger.php.
Constructor & Destructor Documentation
pocketmine\utils\MainLogger::__construct ($ logFile, $ hasANSI = false, $ logDebug = false)
Parameters:
string $logFile
bool $hasANSI
bool $logDebug
Exceptions:
\RuntimeException
Definition at line 43 of file MainLogger.php.
Member Function Documentation
AttachableThreadedLogger::addAttachment (\ThreadedLoggerAttachment $ attachment) [inherited]
Parameters:
ThreadedLoggerAttachment $attachment
Definition at line 30 of file AttachableThreadedLogger.php.
Referenced by AttachableThreadedLogger\removeAttachment().
pocketmine\utils\MainLogger::alert ($ message)
Action must me taken immediately
Parameters:
string $message
Implements Logger.
Definition at line 67 of file MainLogger.php.
Threaded::chunk ($ size) [inherited]
Fetches a chunk of the objects properties table of the given size
Parameters:
int $size The number of items to fetch
array An array of items from the objects member table
Definition at line 83 of file pthreads.php.
Threaded::count () [inherited]
{}
Definition at line 89 of file pthreads.php.
pocketmine\utils\MainLogger::critical ($ message)
Critical conditions
Parameters:
string $message
Implements Logger.
Definition at line 71 of file MainLogger.php.
pocketmine\utils\MainLogger::debug ($ message)
Detailed debug information.
Parameters:
string $message
Implements Logger.
Definition at line 91 of file MainLogger.php.
Thread::detach () [inherited]
Detaches a thread
Returns:
bool A boolean indication of success
Definition at line 257 of file pthreads.php.
pocketmine\utils\MainLogger::emergency ($ message)
System is unusable
Parameters:
string $message
Implements Logger.
Definition at line 63 of file MainLogger.php.
pocketmine\utils\MainLogger::error ($ message)
Runtime errors that do not require immediate action but should typically be logged and monitored.
Parameters:
string $message
Implements Logger.
Definition at line 75 of file MainLogger.php.
AttachableThreadedLogger::getAttachments () [inherited]
Returns:
[]
Definition at line 62 of file AttachableThreadedLogger.php.
Thread::getCreatorId () [inherited]
Will return the identity of the Thread that created the referenced Thread
int A numeric identity
Definition at line 266 of file pthreads.php.
static Thread::getCurrentThread () [static, inherited]
Will return the instance of currently executing thread
Returns:
static
Definition at line 274 of file pthreads.php.
static Thread::getCurrentThreadId () [static, inherited]
Will return the identity of the currently executing thread
int
Definition at line 283 of file pthreads.php.
static pocketmine\utils\MainLogger::getLogger () [static]
Returns:
MainLogger
Definition at line 59 of file MainLogger.php.
Threaded::getTerminationInfo () [inherited]
Retrieves terminal error information from the referenced object
array|bool array containing the termination conditions of the referenced object
Definition at line 98 of file pthreads.php.
Thread::getThreadId () [inherited]
Will return the identity of the referenced Thread
int
Definition at line 292 of file pthreads.php.
static Thread::globally (Callable $ block, $ args = null) [static, inherited]
Will execute the Callable in the global scope
Parameters:
Callable $block The code to execute
... $args Variable length list of arguments to pass to the Callable upon execution
bool A boolean indication of success
Definition at line 350 of file pthreads.php.
pocketmine\utils\MainLogger::info ($ message)
Inersting events.
Parameters:
string $message
Implements Logger.
Definition at line 87 of file MainLogger.php.
Thread::isJoined () [inherited]
Tell if the referenced Thread has been joined by another context
bool A boolean indication of state
Definition at line 301 of file pthreads.php.
Threaded::isRunning () [inherited]
Tell if the referenced object is executing
bool A boolean indication of state
Definition at line 107 of file pthreads.php.
Thread::isStarted () [inherited]
Tell if the referenced Thread has been started
bool A boolean indication of state
Definition at line 310 of file pthreads.php.
Threaded::isTerminated () [inherited]
Tell if the referenced object exited, suffered fatal errors, or threw uncaught exceptions during execution
bool A boolean indication of state
Definition at line 116 of file pthreads.php.
Threaded::isWaiting () [inherited]
Tell if the referenced object is waiting for notification
bool A boolean indication of state
Definition at line 125 of file pthreads.php.
Thread::join () [inherited]
Causes the calling context to wait for the referenced Thread to finish executing
bool A boolean indication of state
Definition at line 319 of file pthreads.php.
Thread::kill () [inherited]
Kills the referenced thread, dangerously !
http://www.php.net/manual/en/thread.kill.php
Definition at line 327 of file pthreads.php.
Threaded::lock () [inherited]
Lock the referenced objects property table
bool A boolean indication of state
Definition at line 134 of file pthreads.php.
pocketmine\utils\MainLogger::log ($ level, $ message)
Logs with an arbitrary level.
Parameters:
mixed $level
string $message
Implements Logger.
Definition at line 105 of file MainLogger.php.
Threaded::merge ($ from, $ overwrite = true) [inherited]
Merges data into the current object
Parameters:
mixed $from The data to merge
bool $overwrite Overwrite existing keys flag, by default true
bool A boolean indication of success
Definition at line 146 of file pthreads.php.
pocketmine\utils\MainLogger::notice ($ message)
Normal but significant events.
Parameters:
string $message
Implements Logger.
Definition at line 83 of file MainLogger.php.
Threaded::notify () [inherited]
Send notification to the referenced object
bool A boolean indication of success
Definition at line 155 of file pthreads.php.
Threaded::offsetExists ($ offset) [inherited]
{}
Definition at line 173 of file pthreads.php.
Threaded::offsetGet ($ offset) [inherited]
{}
Definition at line 161 of file pthreads.php.
Threaded::offsetSet ($ offset, $ value) [inherited]
{}
Definition at line 167 of file pthreads.php.
Threaded::offsetUnset ($ offset) [inherited]
{}
Definition at line 179 of file pthreads.php.
Threaded::pop () [inherited]
Pops an item from the objects property table
mixed The last item from the objects properties table
Definition at line 188 of file pthreads.php.
AttachableThreadedLogger::removeAttachment (\ThreadedLoggerAttachment $ attachment) [inherited]
Parameters:
ThreadedLoggerAttachment $attachment
Definition at line 41 of file AttachableThreadedLogger.php.
References AttachableThreadedLogger\addAttachment(), and ThreadedLoggerAttachment\getAttachments().
pocketmine\utils\MainLogger::run ()
The programmer should always implement the run method for objects that are intended for execution.
void The methods return value, if used, will be ignored
Reimplemented from Threaded.
Definition at line 156 of file MainLogger.php.
pocketmine\utils\MainLogger::setLogDebug ($ logDebug)
Parameters:
bool $logDebug
Definition at line 101 of file MainLogger.php.
Threaded::shift () [inherited]
Shifts an item from the objects properties table
mixed The first item from the objects properties table
Definition at line 206 of file pthreads.php.
Thread::start ($ options = PTHREADS_INHERIT_ALL) [inherited]
Will start a new Thread to execute the implemented run method
Parameters:
int $options An optional mask of inheritance constants, by default PTHREADS_INHERIT_ALL
bool A boolean indication of success
Reimplemented in pocketmine\scheduler\AsyncWorker.
Definition at line 338 of file pthreads.php.
Threaded::synchronized (\Closure $ function, $ args = null) [inherited]
Executes the block while retaining the synchronization lock for the current context.
Parameters:
\Closure $function The block of code to execute
mixed $args ... Variable length list of arguments to use as function arguments to the block
mixed The return value from the block
Definition at line 218 of file pthreads.php.
Threaded::unlock () [inherited]
Unlock the referenced objects storage for the calling context
bool A boolean indication of success
Definition at line 227 of file pthreads.php.
Threaded::wait ($ timeout) [inherited]
Waits for notification from the Stackable
Parameters:
int $timeout An optional timeout in microseconds
bool A boolean indication of success
Definition at line 238 of file pthreads.php.
pocketmine\utils\MainLogger::warning ($ message)
Exceptional occurrences that are not errors.
Example: Use of deprecated APIs, poor use of an API, undesirable things that are not necessarily wrong.
Parameters:
string $message
Implements Logger.
Definition at line 79 of file MainLogger.php.
The documentation for this class was generated from the following file:
MainLogger.php