PocketMine-MP: pocketmine\level\Position Class Reference
pocketmine\level\Position Class Reference
Public Member Functions
__construct ($x=0, $y=0, $z=0, Level $level=null)
getLevel ()
setLevel (Level $level)
isValid ()
setStrong ()
setWeak ()
getSide ($side, $step=1)
__toString ()
setComponents ($x, $y, $z)
getX ()
getY ()
getZ ()
getFloorX ()
getFloorY ()
getFloorZ ()
getRight ()
getUp ()
getForward ()
getSouth ()
getWest ()
add ($x, $y=0, $z=0)
subtract ($x=0, $y=0, $z=0)
multiply ($number)
divide ($number)
ceil ()
floor ()
round ()
abs ()
distance (Vector3 $pos)
distanceSquared (Vector3 $pos)
maxPlainDistance ($x=0, $z=0)
length ()
lengthSquared ()
normalize ()
dot (Vector3 $v)
cross (Vector3 $v)
getIntermediateWithXValue (Vector3 $v, $x)
getIntermediateWithYValue (Vector3 $v, $y)
getIntermediateWithZValue (Vector3 $v, $z)
Static Public Member Functions
static fromObject (Vector3 $pos, Level $level=null)
static getOppositeSide ($side)
Public Attributes
$level = null
const SIDE_DOWN = 0
const SIDE_UP = 1
const SIDE_NORTH = 2
const SIDE_SOUTH = 3
const SIDE_WEST = 4
const SIDE_EAST = 5
$x
$y
$z
Detailed Description
Definition at line 27 of file Position.php.
Constructor & Destructor Documentation
pocketmine\level\Position::__construct ($x = 0, $y = 0, $z = 0, Level $level = null)
Parameters
int $x
int $y
int $z
Level $level
Definition at line 38 of file Position.php.
Member Function Documentation
pocketmine\math\Vector3::add ($x, $y = 0, $z = 0) inherited
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 94 of file Vector3.php.
Referenced by pocketmine\math\Vector3\subtract(), and pocketmine\level\Level\useBreakOn().
pocketmine\math\Vector3::getIntermediateWithXValue (Vector3 $v, $x) inherited
Returns a new vector with x value equal to the second parameter, along the line between this vector and the passed in vector, or null if not possible.
Parameters
Vector3 $v
float $x
Returns
Vector3
Definition at line 241 of file Vector3.php.
pocketmine\math\Vector3::getIntermediateWithYValue (Vector3 $v, $y) inherited
Returns a new vector with y value equal to the second parameter, along the line between this vector and the passed in vector, or null if not possible.
Parameters
Vector3 $v
float $y
Returns
Vector3
Definition at line 268 of file Vector3.php.
pocketmine\math\Vector3::getIntermediateWithZValue (Vector3 $v, $z) inherited
Returns a new vector with z value equal to the second parameter, along the line between this vector and the passed in vector, or null if not possible.
Parameters
Vector3 $v
float $z
Returns
Vector3
Definition at line 295 of file Vector3.php.
pocketmine\level\Position::getLevel ()
Returns
Level
Definition at line 52 of file Position.php.
Referenced by pocketmine\level\Level\addEntity(), pocketmine\level\Level\addTile(), pocketmine\block\Block\getMetadata(), pocketmine\tile\Chest\getPair(), pocketmine\block\Block\getSide(), pocketmine\Player\getSpawn(), pocketmine\block\Block\hasMetadata(), pocketmine\block\Block\onBreak(), pocketmine\entity\Projectile\onUpdate(), pocketmine\block\Block\place(), pocketmine\level\Level\removeEntity(), pocketmine\block\Block\removeMetadata(), pocketmine\level\Level\removeTile(), pocketmine\Player\save(), pocketmine\block\Block\setMetadata(), and pocketmine\Player\spawnTo().
pocketmine\level\Position::getSide ($side, $step = 1)
Returns a side Vector
Parameters
int $side
int $step
Returns
Position
Exceptions
LevelException
Definition at line 104 of file Position.php.
References pocketmine\level\Position\isValid().
pocketmine\level\Position::isValid ()
Checks if this object has a valid reference to a Level
Returns
bool
Definition at line 66 of file Position.php.
Referenced by pocketmine\level\Position\getSide(), and pocketmine\block\Block\getSide().
pocketmine\math\Vector3::normalize () inherited
Returns
Vector3
Definition at line 211 of file Vector3.php.
pocketmine\level\Position::setComponents ($x, $y, $z)
Parameters
$x
$y
$z
Returns
Position
Definition at line 123 of file Position.php.
pocketmine\level\Position::setStrong ()
Marks the level reference as strong so it won't be collected by the garbage collector.
Deprecated:
Returns
bool
Definition at line 78 of file Position.php.
pocketmine\level\Position::setWeak ()
Marks the level reference as weak so it won't have effect against the garbage collector decision.
Deprecated:
Returns
bool
Definition at line 90 of file Position.php.
pocketmine\math\Vector3::subtract ($x = 0, $y = 0, $z = 0) inherited
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 109 of file Vector3.php.
References pocketmine\math\Vector3\add().
The documentation for this class was generated from the following file:
Position.php