PocketMine-MP: pocketmine\inventory\Transaction Interface Reference
pocketmine\inventory\Transaction Interface Reference
Public Member Functions
getInventory ()
getSlot ()
getSourceItem ()
getTargetItem ()
getCreationTime ()
Detailed Description
Definition at line 26 of file Transaction.php.
Member Function Documentation
pocketmine\inventory\Transaction::getCreationTime ()
Returns
float
Implemented in pocketmine\inventory\BaseTransaction.
Referenced by pocketmine\inventory\SimpleTransactionGroup\addTransaction().
pocketmine\inventory\Transaction::getInventory ()
Returns
Inventory
Implemented in pocketmine\inventory\BaseTransaction.
Referenced by pocketmine\inventory\SimpleTransactionGroup\addTransaction().
pocketmine\inventory\Transaction::getSlot ()
Returns
int
Implemented in pocketmine\inventory\BaseTransaction.
Referenced by pocketmine\inventory\SimpleTransactionGroup\addTransaction().
pocketmine\inventory\Transaction::getSourceItem ()
Returns
Item
Implemented in pocketmine\inventory\BaseTransaction.
pocketmine\inventory\Transaction::getTargetItem ()
Returns
Item
Implemented in pocketmine\inventory\BaseTransaction.
The documentation for this interface was generated from the following file:
Transaction.php