PocketMine-MP: pocketmine\event\block\BlockPlaceEvent Class Reference
pocketmine\event\block\BlockPlaceEvent Class Reference
Public Member Functions
__construct (Player $player, Block $blockPlace, Block $blockReplace, Block $blockAgainst, Item $item)
getPlayer ()
getItem ()
getBlockReplaced ()
getBlockAgainst ()
getBlock ()
getEventName ()
isCancelled ()
setCancelled ($value=true)
getHandlers ()
isCancelled ()
setCancelled ($forceCancel=false)
Static Public Attributes
static $handlerList = null
Protected Attributes
$player
$item
$blockReplace
$blockAgainst
$block
$eventName = null
Detailed Description
Called when a player places a block
Definition at line 32 of file BlockPlaceEvent.php.
Member Function Documentation
pocketmine\event\Event::getEventName () final inherited
Returns
string
Definition at line 43 of file Event.php.
References pocketmine\event\Event\$eventName.
pocketmine\event\Event::getHandlers () inherited
Returns
HandlerList
Definition at line 77 of file Event.php.
pocketmine\event\block\BlockPlaceEvent::getItem ()
Gets the item in hand
Returns
mixed
Definition at line 62 of file BlockPlaceEvent.php.
pocketmine\event\Event::isCancelled () inherited
Returns
bool
Exceptions
BadMethodCallException
Definition at line 52 of file Event.php.
Referenced by pocketmine\plugin\RegisteredListener\callEvent(), and pocketmine\event\Event\setCancelled().
pocketmine\event\Event::setCancelled ($value = true) inherited
Parameters
bool $value
Returns
bool
Exceptions
BadMethodCallException
Definition at line 67 of file Event.php.
References pocketmine\event\Event\isCancelled().
Member Data Documentation
pocketmine\event\Event::$eventName = null protected inherited
Any callable event must declare the static variable
public static $handlerList = null;
Not doing so will deny the proper event initialization
Definition at line 37 of file Event.php.
Referenced by pocketmine\event\Event\getEventName().
The documentation for this class was generated from the following file:
BlockPlaceEvent.php