PocketMine-MP: pocketmine\inventory\PlayerInventory Class Reference
pocketmine\inventory\PlayerInventory Class Reference
Public Member Functions
__construct (Human $player)
getSize ()
getHotbarSlotIndex ($index)
setHotbarSlotIndex ($index, $slot)
getHeldItemIndex ()
setHeldItemIndex ($index)
getItemInHand ()
setItemInHand (Item $item)
getHeldItemSlot ()
setHeldItemSlot ($slot)
sendHeldItem ($target)
onSlotChange ($index, $before, $source=null)
getHotbarSize ()
getArmorItem ($index)
setArmorItem ($index, Item $item)
getHelmet ()
getChestplate ()
getLeggings ()
getBoots ()
setHelmet (Item $helmet)
setChestplate (Item $chestplate)
setLeggings (Item $leggings)
setBoots (Item $boots)
setItem ($index, Item $item, $source=null)
clear ($index, $source=null)
getArmorContents ()
clearAll ()
setArmorContents (array $items)
sendContents ($target)
getHolder ()
getMaxStackSize ()
getName ()
getTitle ()
getItem ($index)
getContents ()
setContents (array $items)
contains (Item $item)
all (Item $item)
remove (Item $item)
first (Item $item)
firstEmpty ()
canAddItem (Item $item)
getViewers ($source=null)
setMaxStackSize ($size)
open (Player $who)
close (Player $who)
onOpen (Player $who)
onClose (Player $who)
sendSlot ($index, $target)
getType ()
addItem ()
removeItem ()
Public Attributes
const MAX_STACK = 64
Protected Attributes
$itemInHandIndex = 0
$hotbar
$type
$maxStackSize = Inventory::MAX_STACK
$size
$name
$title
$slots = []
$viewers = []
$holder
Detailed Description
Definition at line 35 of file PlayerInventory.php.
Member Function Documentation
pocketmine\inventory\Inventory::addItem () inherited
Stores the given Items in the inventory. This will try to fill existing stacks and empty slots as well as it can.
Returns the Items that did not fit
Parameters
Item ...$item
Returns
Item[]
pocketmine\inventory\BaseInventory::all (Item $item) inherited
Will return all the Items that has the same id and metadata (if not null). Won't check amount
Parameters
Item $item
Returns
Item[]
Implements pocketmine\inventory\Inventory.
Definition at line 164 of file BaseInventory.php.
References pocketmine\inventory\BaseInventory\getContents().
pocketmine\inventory\BaseInventory::canAddItem (Item $item) inherited
Checks if a given Item can be added to the inventory
Parameters
Item $item
Returns
bool
Implements pocketmine\inventory\Inventory.
Definition at line 207 of file BaseInventory.php.
References pocketmine\inventory\BaseInventory\getItem().
pocketmine\inventory\PlayerInventory::clear ($index, $source = null)
Will clear a specific slot
Parameters
int $index
Player $source
Returns
bool
Implements pocketmine\inventory\Inventory.
Definition at line 225 of file PlayerInventory.php.
References pocketmine\inventory\PlayerInventory\getHolder(), pocketmine\Server\getInstance(), pocketmine\inventory\BaseInventory\getViewers(), pocketmine\inventory\PlayerInventory\onSlotChange(), and pocketmine\inventory\PlayerInventory\sendContents().
Referenced by pocketmine\inventory\PlayerInventory\clearAll(), pocketmine\inventory\PlayerInventory\setArmorContents(), and pocketmine\inventory\PlayerInventory\setItem().
pocketmine\inventory\PlayerInventory::clearAll ()
Clears all the slots
Implements pocketmine\inventory\Inventory.
Definition at line 262 of file PlayerInventory.php.
References pocketmine\inventory\PlayerInventory\clear().
pocketmine\inventory\BaseInventory::contains (Item $item) inherited
Checks if the inventory contains any Item with the same material data. It will check id, amount, and metadata (if not null)
Parameters
Item $item
Returns
bool
Implements pocketmine\inventory\Inventory.
Definition at line 149 of file BaseInventory.php.
References pocketmine\inventory\BaseInventory\getContents().
pocketmine\inventory\BaseInventory::first (Item $item) inherited
Will return the first slot has the same id and metadata (if not null) as the Item. -1 if not found, will check amount
Parameters
Item $item
Returns
int
Implements pocketmine\inventory\Inventory.
Definition at line 185 of file BaseInventory.php.
References pocketmine\inventory\BaseInventory\getContents().
pocketmine\inventory\BaseInventory::firstEmpty () inherited
Returns the first empty slot, or -1 if not found
Returns
int
Implements pocketmine\inventory\Inventory.
Definition at line 197 of file BaseInventory.php.
References pocketmine\inventory\BaseInventory\getItem().
pocketmine\inventory\PlayerInventory::getArmorContents ()
Returns
Item[]
Definition at line 252 of file PlayerInventory.php.
References pocketmine\inventory\BaseInventory\getItem().
pocketmine\inventory\BaseInventory::getContents () inherited
Returns
Item[]
Implements pocketmine\inventory\Inventory.
Definition at line 100 of file BaseInventory.php.
Referenced by pocketmine\inventory\BaseInventory\all(), pocketmine\inventory\BaseInventory\clearAll(), pocketmine\inventory\BaseInventory\contains(), pocketmine\inventory\BaseInventory\first(), and pocketmine\inventory\BaseInventory\remove().
pocketmine\inventory\PlayerInventory::getHolder ()
Returns
Human
Implements pocketmine\inventory\Inventory.
Definition at line 384 of file PlayerInventory.php.
Referenced by pocketmine\inventory\PlayerInventory\clear(), pocketmine\inventory\PlayerInventory\onSlotChange(), pocketmine\inventory\PlayerInventory\sendContents(), pocketmine\inventory\PlayerInventory\sendHeldItem(), and pocketmine\inventory\PlayerInventory\setItem().
pocketmine\inventory\BaseInventory::getItem ($index) inherited
Parameters
int $index
Returns
Item
Implements pocketmine\inventory\Inventory.
Definition at line 96 of file BaseInventory.php.
Referenced by pocketmine\inventory\BaseInventory\canAddItem(), pocketmine\inventory\BaseInventory\firstEmpty(), pocketmine\inventory\PlayerInventory\getArmorContents(), pocketmine\inventory\FurnaceInventory\getFuel(), pocketmine\inventory\FurnaceInventory\getResult(), pocketmine\inventory\FurnaceInventory\getSmelting(), pocketmine\inventory\PlayerInventory\sendContents(), pocketmine\inventory\BaseInventory\sendContents(), pocketmine\inventory\BaseInventory\sendSlot(), pocketmine\inventory\BaseInventory\setItem(), and pocketmine\inventory\PlayerInventory\setItem().
pocketmine\inventory\BaseInventory::getType () inherited
Returns
InventoryType
Implements pocketmine\inventory\Inventory.
Definition at line 427 of file BaseInventory.php.
Referenced by pocketmine\inventory\ContainerInventory\onOpen().
pocketmine\inventory\BaseInventory::getViewers ($source = null) inherited
Gets all the Players viewing the inventory Players will be viewing their inventory at all times, even when not open.
Parameters
Player $source
Returns
Player[]
Implements pocketmine\inventory\Inventory.
Definition at line 333 of file BaseInventory.php.
Referenced by pocketmine\inventory\PlayerInventory\clear(), pocketmine\inventory\BaseInventory\clear(), pocketmine\inventory\ChestInventory\onClose(), pocketmine\inventory\ChestInventory\onOpen(), pocketmine\inventory\PlayerInventory\onSlotChange(), pocketmine\inventory\BaseInventory\onSlotChange(), pocketmine\inventory\BaseInventory\setItem(), and pocketmine\inventory\PlayerInventory\setItem().
pocketmine\inventory\BaseInventory::onClose (Player $who) inherited
Parameters
Player $who
Implements pocketmine\inventory\Inventory.
Definition at line 371 of file BaseInventory.php.
pocketmine\inventory\BaseInventory::onOpen (Player $who) inherited
Parameters
Player $who
Implements pocketmine\inventory\Inventory.
Definition at line 367 of file BaseInventory.php.
Referenced by pocketmine\inventory\BaseInventory\open().
pocketmine\inventory\PlayerInventory::onSlotChange ($index, $before, $source = null)
Parameters
int $index
Item $before
Player $source
Implements pocketmine\inventory\Inventory.
Definition at line 147 of file PlayerInventory.php.
References pocketmine\inventory\PlayerInventory\getHolder(), and pocketmine\inventory\BaseInventory\getViewers().
Referenced by pocketmine\inventory\PlayerInventory\clear(), and pocketmine\inventory\PlayerInventory\setItem().
pocketmine\inventory\BaseInventory::open (Player $who) inherited
Tries to open the inventory to a player
Parameters
Player $who
Returns
bool
Implements pocketmine\inventory\Inventory.
Definition at line 353 of file BaseInventory.php.
References pocketmine\Player\getServer(), and pocketmine\inventory\BaseInventory\onOpen().
pocketmine\inventory\BaseInventory::remove (Item $item) inherited
Will remove all the Items that has the same id and metadata (if not null)
Parameters
Item $item
Implements pocketmine\inventory\Inventory.
Definition at line 176 of file BaseInventory.php.
References pocketmine\inventory\BaseInventory\clear(), and pocketmine\inventory\BaseInventory\getContents().
pocketmine\inventory\Inventory::removeItem () inherited
Removes the given Item from the inventory. It will return the Items that couldn't be removed.
Parameters
Item ...$item
Returns
Item[]
pocketmine\inventory\PlayerInventory::sendContents ($target)
Parameters
Player|Player[] $target
Implements pocketmine\inventory\Inventory.
Definition at line 324 of file PlayerInventory.php.
References pocketmine\inventory\PlayerInventory\getHolder(), and pocketmine\inventory\BaseInventory\getItem().
Referenced by pocketmine\inventory\PlayerInventory\clear(), pocketmine\inventory\PlayerInventory\sendHeldItem(), and pocketmine\inventory\PlayerInventory\setItem().
pocketmine\inventory\PlayerInventory::sendHeldItem ($target)
Parameters
Player|Player[] $target
Definition at line 123 of file PlayerInventory.php.
References pocketmine\inventory\PlayerInventory\getHolder(), and pocketmine\inventory\PlayerInventory\sendContents().
pocketmine\inventory\BaseInventory::sendSlot ($index, $target) inherited
Parameters
int $index
Player|Player[] $target
Implements pocketmine\inventory\Inventory.
Definition at line 408 of file BaseInventory.php.
References pocketmine\inventory\BaseInventory\getItem().
Referenced by pocketmine\inventory\BaseInventory\onSlotChange().
pocketmine\inventory\PlayerInventory::setArmorContents (array $items)
Parameters
Item[] $items
Definition at line 307 of file PlayerInventory.php.
References pocketmine\inventory\PlayerInventory\clear(), and pocketmine\inventory\PlayerInventory\setItem().
pocketmine\inventory\BaseInventory::setContents (array $items) inherited
Parameters
Item[] $items
Implements pocketmine\inventory\Inventory.
Definition at line 107 of file BaseInventory.php.
References pocketmine\inventory\BaseInventory\clear(), and pocketmine\inventory\BaseInventory\setItem().
Referenced by pocketmine\inventory\BaseInventory\__construct().
pocketmine\inventory\PlayerInventory::setItem ($index, Item $item, $source = null)
Puts an Item in a slot. If a plugin refuses the update or $index is invalid, it'll return false If a source Player is specified, it won't send a Inventory update to it
Parameters
int $index
Item $item
Player $source
Returns
bool
Implements pocketmine\inventory\Inventory.
Definition at line 199 of file PlayerInventory.php.
References pocketmine\inventory\PlayerInventory\clear(), pocketmine\inventory\PlayerInventory\getHolder(), pocketmine\Server\getInstance(), pocketmine\inventory\BaseInventory\getItem(), pocketmine\inventory\BaseInventory\getViewers(), pocketmine\inventory\PlayerInventory\onSlotChange(), and pocketmine\inventory\PlayerInventory\sendContents().
Referenced by pocketmine\inventory\PlayerInventory\setArmorContents(), and pocketmine\inventory\PlayerInventory\setItemInHand().
pocketmine\inventory\PlayerInventory::setItemInHand (Item $item)
Parameters
Item $item
Returns
bool
Definition at line 95 of file PlayerInventory.php.
References pocketmine\inventory\PlayerInventory\setItem().
pocketmine\inventory\BaseInventory::setMaxStackSize ($size) inherited
Parameters
int $size
Implements pocketmine\inventory\Inventory.
Definition at line 349 of file BaseInventory.php.
The documentation for this class was generated from the following file:
PlayerInventory.php