PocketMine-MP: pocketmine\plugin\Plugin Interface Reference
pocketmine\plugin\Plugin Interface Reference
Public Member Functions
onLoad ()
onEnable ()
isEnabled ()
onDisable ()
isDisabled ()
getDataFolder ()
getDescription ()
getResource ($filename)
saveResource ($filename, $replace=false)
getResources ()
getConfig ()
saveConfig ()
saveDefaultConfig ()
reloadConfig ()
getServer ()
getName ()
getLogger ()
getPluginLoader ()
onCommand (CommandSender $sender, Command $command, $label, array $args)
Detailed Description
It is recommended to use PluginBase for the actual plugin
Definition at line 34 of file Plugin.php.
Member Function Documentation
pocketmine\plugin\Plugin::getConfig ()
Returns
Implemented in pocketmine\plugin\PluginBase.
pocketmine\plugin\Plugin::getDataFolder ()
Gets the plugin's data folder to save files and configuration
Implemented in pocketmine\plugin\PluginBase.
pocketmine\plugin\Plugin::getDescription ()
Returns
PluginDescription
Implemented in pocketmine\plugin\PluginBase.
Referenced by pocketmine\permission\PermissionAttachment\__construct(), pocketmine\plugin\PluginLogger\__construct(), pocketmine\permission\PermissibleBase\addAttachment(), pocketmine\plugin\PharPluginLoader\disablePlugin(), pocketmine\plugin\PluginManager\disablePlugin(), pocketmine\plugin\PharPluginLoader\enablePlugin(), pocketmine\plugin\PluginManager\enablePlugin(), pocketmine\plugin\PluginManager\isPluginEnabled(), pocketmine\plugin\PluginManager\parseYamlCommands(), and pocketmine\plugin\PluginManager\registerEvent().
pocketmine\plugin\Plugin::getLogger ()
Returns
PluginLogger
Implemented in pocketmine\plugin\PluginBase.
pocketmine\plugin\Plugin::getPluginLoader ()
Returns
PluginLoader
Implemented in pocketmine\plugin\PluginBase.
Referenced by pocketmine\plugin\PluginManager\disablePlugin(), and pocketmine\plugin\PluginManager\enablePlugin().
pocketmine\plugin\Plugin::getResource ($filename)
Gets an embedded resource in the plugin file.
Implemented in pocketmine\plugin\PluginBase.
pocketmine\plugin\Plugin::getResources ()
Returns all the resources incrusted in the plugin
Implemented in pocketmine\plugin\PluginBase.
pocketmine\plugin\Plugin::getServer ()
Returns
Implemented in pocketmine\plugin\PluginBase.
pocketmine\command\CommandExecutor::onCommand (CommandSender $sender, Command $command, $label, array $args) inherited
Parameters
CommandSender $sender
Command $command
string $label
string[] $args
Returns
boolean
Implemented in pocketmine\plugin\PluginBase.
pocketmine\plugin\Plugin::onDisable ()
Called when the plugin is disabled Use this to free open things and finish actions
Implemented in pocketmine\plugin\PluginBase.
pocketmine\plugin\Plugin::onEnable ()
Called when the plugin is enabled
Implemented in pocketmine\plugin\PluginBase.
pocketmine\plugin\Plugin::onLoad ()
Called when the plugin is loaded, before calling onEnable()
Implemented in pocketmine\plugin\PluginBase.
pocketmine\plugin\Plugin::saveResource ($filename, $replace = false)
Saves an embedded resource to its relative location in the data folder
Parameters
string $filename
bool $replace
Implemented in pocketmine\plugin\PluginBase.
The documentation for this interface was generated from the following file:
Plugin.php