PocketMine-MP: pocketmine\Player Class Reference
pocketmine\Player Class Reference
Public Member Functions
isBanned ()
setBanned ($value)
isWhitelisted ()
setWhitelisted ($value)
getPlayer ()
getFirstPlayed ()
getLastPlayed ()
hasPlayedBefore ()
spawnTo (Player $player)
despawnFrom (Player $player)
getServer ()
getRemoveFormat ()
setRemoveFormat ($remove=true)
canSee (Player $player)
hidePlayer (Player $player)
showPlayer (Player $player)
isOnline ()
isOp ()
setOp ($value)
isPermissionSet ($name)
hasPermission ($name)
addAttachment (Plugin $plugin, $name=null, $value=null)
removeAttachment (PermissionAttachment $attachment)
recalculatePermissions ()
getEffectivePermissions ()
__construct (SourceInterface $interface, $clientID, $ip, $port)
removeAchievement ($achievementId)
hasAchievement ($achievementId)
isConnected ()
getDisplayName ()
setDisplayName ($name)
getNameTag ()
setNameTag ($name)
getAddress ()
getPort ()
isSleeping ()
unloadChunk ($x, $z)
getSpawn ()
checkACK ($identifier)
handleACK ($identifier)
sendChunk ($x, $z, $payload)
sendNextChunk ()
orderChunks ()
dataPacket (DataPacket $packet, $needACK=false)
directDataPacket (DataPacket $packet, $needACK=false)
sleepOn (Vector3 $pos)
setSpawn (Vector3 $pos)
stopSleep ()
checkSleep ()
awardAchievement ($achievementId)
getGamemode ()
setGamemode ($gm)
sendSettings ($nametags=true)
onUpdate ()
kick ($reason="")
sendMessage ($message)
close ($message="", $reason="generic reason")
save ()
getName ()
kill ()
setHealth ($amount)
attack ($damage, $source=EntityDamageEvent::CAUSE_MAGIC)
teleport (Vector3 $pos, $yaw=null, $pitch=null)
getWindowId (Inventory $inventory)
addWindow (Inventory $inventory, $forceId=null)
removeWindow (Inventory $inventory)
setMetadata ($metadataKey, MetadataValue $metadataValue)
getMetadata ($metadataKey)
hasMetadata ($metadataKey)
removeMetadata ($metadataKey, Plugin $plugin)
getInventory ()
getDrops ()
saveNBT ()
getData ()
heal ($amount)
entityBaseTick ()
getViewers ()
getHealth ()
setLastDamageCause ($type)
getLastDamageCause ()
getMaxHealth ()
setMaxHealth ($amount)
canCollideWith (Entity $entity)
updateMovement ()
getDirectionVector ()
scheduleUpdate ()
setOnFire ($seconds)
getDirection ()
extinguish ()
canTriggerWalking ()
getBoundingBox ()
fall ($fallDistance)
handleWaterMovement ()
handleLavaMovement ()
getEyeHeight ()
moveFlying ()
onCollideWithPlayer (Human $entityPlayer)
getPosition ()
collision ()
move ($dx, $dy, $dz)
setPositionAndRotation (Vector3 $pos, $yaw, $pitch, $force=false)
setRotation ($yaw, $pitch)
setPosition (Vector3 $pos, $force=false)
getMotion ()
setMotion (Vector3 $motion)
isOnGround ()
getID ()
spawnToAll ()
despawnFromAll ()
close ()
__toString ()
getLevel ()
setLevel (Level $level, $strong=false)
isValid ()
setStrong ()
setWeak ()
getSide ($side, $step=1)
distance (Vector3 $pos)
getX ()
getY ()
getZ ()
getFloorX ()
getFloorY ()
getFloorZ ()
getRight ()
getUp ()
getForward ()
getSouth ()
getWest ()
add ($x, $y=0, $z=0)
subtract ($x=0, $y=0, $z=0)
multiply ($number)
divide ($number)
ceil ()
floor ()
round ()
abs ()
distanceSquared (Vector3 $pos)
maxPlainDistance ($x=0, $z=0)
length ()
lengthSquared ()
normalize ()
dot (Vector3 $v)
cross (Vector3 $v)
Static Public Member Functions
static fromObject (Vector3 $pos, Level $level, $strong=false)
Public Attributes
const SURVIVAL = 0
const CREATIVE = 1
const ADVENTURE = 2
const SPECTATOR = 3
const VIEW = Player::SPECTATOR
const SURVIVAL_SLOTS = 36
const CREATIVE_SLOTS = 112
$spawned = false
$loggedIn = false
$gamemode
$lastBreak
$blocked = true
$achievements = []
$lastCorrect
$craftingType = 0
$loginData = []
$usedChunks = []
$width = 0.6
$length = 0.6
$height = 1.8
const NETWORK_ID = -1
$passenger = null
$vehicle = null
$chunkX
$chunkZ
$chunk
$lastX
$lastY
$lastZ
$motionX
$motionY
$motionZ
$lastMotionX
$lastMotionY
$lastMotionZ
$yaw
$pitch
$lastYaw
$lastPitch
$boundingBox
$onGround
$inBlock = false
$positionChanged
$motionChanged
$dead
$fallDistance
$ticksLived
$lastUpdate
$maxFireTicks
$fireTicks
$airTicks
$namedtag
$noDamageTicks
$closed = false
$level = null
$x
$y
$z
Static Public Attributes
static $entityCount = 1
static $needUpdate = []
Protected Member Functions
initEntity ()
getCreativeBlock (Item $item)
checkObstruction ($x, $y, $z)
updateFallState ($distanceThisTick, $onGround)
switchLevel (Level $targetLevel)
checkBlockCollision (&$list=array())
Protected Attributes
$interface
$windowCnt = 2
$windows
$windowIndex = []
$sendIndex = 0
$currentTransaction = null
$isCrafting = false
$lastMovement = 0
$forceMovement = false
$connected = true
$ip
$removeFormat = true
$port
$username
$iusername
$displayName
$startAction = false
$sleeping = false
$clientID = null
$loadQueue = []
$chunkACK = []
$chunkLoadTask
$hiddenPlayers = []
$tasks = []
$nameTag = "TESTIFICATE"
$inventory
$gravity = 0.08
$drag = 0.02
$hasSpawned = []
$id
$lastDamageCause = null
$age = 0
$isStatic = false
$isColliding = false
$inWater
$fireProof
$spawnTime
$server
Detailed Description
Main class that handles networking, recovery, and packet sending to the server part
Definition at line 104 of file Player.php.
Constructor & Destructor Documentation
pocketmine\Player::__construct (SourceInterface $interface, $clientID, $ip, $port)
Parameters
SourceInterface $interface
null $clientID
string $ip
integer $port
Definition at line 388 of file Player.php.
Member Function Documentation
pocketmine\math\Vector3::add ($x, $y = 0, $z = 0) inherited
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 90 of file Vector3.php.
Referenced by pocketmine\math\Vector3\subtract(), and pocketmine\level\Level\useBreakOn().
pocketmine\Player::addAttachment (Plugin $plugin, $name = null, $value = null)
Parameters
Plugin $plugin
string $name
bool $value
Returns
permission
Implements pocketmine\permission\Permissible.
Definition at line 349 of file Player.php.
pocketmine\Player::addWindow (Inventory $inventory, $forceId = null)
Returns the created/existing window id
Parameters
Inventory $inventory
int $forceId
Returns
int
Definition at line 2323 of file Player.php.
References pocketmine\inventory\Inventory\open().
pocketmine\Player::awardAchievement ($achievementId)
Parameters
string $achievementId
Returns
bool
Definition at line 912 of file Player.php.
pocketmine\Player::canSee (Player $player)
Parameters
Player $player
Returns
bool
Definition at line 265 of file Player.php.
References pocketmine\Player\getName().
Referenced by pocketmine\Player\spawnTo().
pocketmine\Player::checkACK ($identifier)
Parameters
int $identifier
Returns
bool
Definition at line 532 of file Player.php.
pocketmine\entity\Entity::checkBlockCollision (& $list = array()) protected inherited
Parameters
Block[] $list
Returns
Block[]
Definition at line 873 of file Entity.php.
References pocketmine\level\Position\getLevel().
pocketmine\Player::checkSleep ()
WARNING: Do not use this, it's only for internal use. Changes to this function won't be recorded on the version.
Definition at line 848 of file Player.php.
pocketmine\Player::close ($message = "", $reason = "generic reason")
Parameters
string $message Message to be broadcasted
string $reason Reason showed in console
Definition at line 2105 of file Player.php.
pocketmine\Player::dataPacket (DataPacket $packet, $needACK = false)
Sends an ordered DataPacket to the send buffer
Parameters
DataPacket $packet
bool $needACK
Returns
int|bool
Definition at line 747 of file Player.php.
Referenced by pocketmine\entity\Entity\despawnFrom(), pocketmine\inventory\ContainerInventory\onClose(), and pocketmine\inventory\ContainerInventory\onOpen().
pocketmine\Player::despawnFrom (Player $player)
Parameters
Player $player
Definition at line 233 of file Player.php.
Referenced by pocketmine\Player\hidePlayer().
pocketmine\Player::directDataPacket (DataPacket $packet, $needACK = false)
Parameters
DataPacket $packet
bool $needACK
Returns
bool|int
Definition at line 773 of file Player.php.
pocketmine\level\Position::distance (Vector3 $pos) inherited
Returns the distance between two points or objects
Parameters
Vector3 $pos
Returns
float
Definition at line 120 of file Position.php.
References pocketmine\level\Position\getLevel().
pocketmine\Player::getAddress ()
Gets the player IP address
Returns
string
Definition at line 479 of file Player.php.
Referenced by pocketmine\Server\removePlayer().
pocketmine\entity\Entity::getDirectionVector () inherited
Returns
Vector3
Definition at line 535 of file Entity.php.
pocketmine\Player::getDisplayName ()
Gets the "friendly" name to display of this player to use in the chat.
Returns
string
Definition at line 445 of file Player.php.
pocketmine\Player::getEffectivePermissions ()
Returns
permission[]
Implements pocketmine\permission\Permissible.
Definition at line 377 of file Player.php.
pocketmine\Player::getFirstPlayed ()
Returns
int|double
Implements pocketmine\IPlayer.
Definition at line 205 of file Player.php.
pocketmine\Player::getGamemode ()
Returns
int
Definition at line 936 of file Player.php.
pocketmine\entity\Entity::getHealth () inherited
Returns
int
Definition at line 282 of file Entity.php.
pocketmine\entity\Human::getInventory () inherited
Get the object related inventory
Returns
Inventory
Implements pocketmine\inventory\InventoryHolder.
Definition at line 49 of file Human.php.
pocketmine\entity\Entity::getLastDamageCause () inherited
Returns
int|EntityDamageEvent|null
Definition at line 318 of file Entity.php.
pocketmine\Player::getLastPlayed ()
Returns
int|double
Implements pocketmine\IPlayer.
Definition at line 209 of file Player.php.
pocketmine\level\Position::getLevel () inherited
Returns
Level
Definition at line 55 of file Position.php.
Referenced by pocketmine\level\Level\addEntity(), pocketmine\level\Level\addTile(), pocketmine\entity\Entity\checkBlockCollision(), pocketmine\level\Position\distance(), pocketmine\block\Block\getMetadata(), pocketmine\tile\Chest\getPair(), pocketmine\level\Position\getSide(), pocketmine\block\Block\getSide(), pocketmine\Player\getSpawn(), pocketmine\block\Block\hasMetadata(), pocketmine\level\Level\removeEntity(), pocketmine\block\Block\removeMetadata(), pocketmine\level\Level\removeTile(), pocketmine\Player\save(), pocketmine\block\Block\setMetadata(), and pocketmine\Player\spawnTo().
pocketmine\entity\Entity::getMaxHealth () inherited
Returns
int
Definition at line 325 of file Entity.php.
Referenced by pocketmine\entity\Entity\setHealth().
pocketmine\Player::getMetadata ($metadataKey)
Returns a list of previously set metadata values from the implementing object's metadata store.
Parameters
string $metadataKey
Returns
MetadataValue[]
Implements pocketmine\metadata\Metadatable.
Definition at line 2357 of file Player.php.
pocketmine\Player::getName ()
Gets the username
Returns
string
Implements pocketmine\command\CommandSender.
Definition at line 2171 of file Player.php.
Referenced by pocketmine\Player\canSee(), pocketmine\Player\hidePlayer(), and pocketmine\Player\showPlayer().
pocketmine\Player::getNameTag ()
Returns
string
Definition at line 459 of file Player.php.
pocketmine\Player::getPlayer ()
Returns
Player|null
Implements pocketmine\IPlayer.
Definition at line 201 of file Player.php.
pocketmine\Player::getPort ()
Returns
int
Definition at line 486 of file Player.php.
Referenced by pocketmine\Server\removePlayer().
pocketmine\Player::getRemoveFormat ()
Returns
bool
Definition at line 249 of file Player.php.
pocketmine\Player::getServer ()
Returns
Server
Implements pocketmine\command\CommandSender.
Definition at line 242 of file Player.php.
Referenced by pocketmine\inventory\BaseInventory\open().
pocketmine\level\Position::getSide ($side, $step = 1) inherited
Returns a side Vector
Parameters
int $side
int $step
Returns
Position
Exceptions
RuntimeException
Definition at line 105 of file Position.php.
References pocketmine\level\Position\getLevel(), and pocketmine\level\Position\isValid().
pocketmine\Player::getSpawn ()
Returns
Position
Definition at line 517 of file Player.php.
References pocketmine\level\Position\getLevel().
pocketmine\entity\Entity::getViewers () inherited
Returns
Player[]
Definition at line 244 of file Entity.php.
pocketmine\Player::getWindowId (Inventory $inventory)
Parameters
Inventory $inventory
Returns
int
Definition at line 2307 of file Player.php.
Referenced by pocketmine\inventory\ContainerInventory\onClose(), and pocketmine\inventory\ContainerInventory\onOpen().
pocketmine\Player::hasAchievement ($achievementId)
Parameters
string $achievementId
Returns
bool
Definition at line 419 of file Player.php.
pocketmine\Player::hasMetadata ($metadataKey)
Tests to see whether the implementing object contains the given metadata value in its metadata store.
Parameters
string $metadataKey
Returns
boolean
Implements pocketmine\metadata\Metadatable.
Definition at line 2361 of file Player.php.
pocketmine\Player::hasPermission ($name)
Parameters
permission\Permission | string $name
Returns
bool
Implements pocketmine\permission\Permissible.
Definition at line 338 of file Player.php.
pocketmine\Player::hasPlayedBefore ()
Returns
mixed
Implements pocketmine\IPlayer.
Definition at line 213 of file Player.php.
pocketmine\Player::hidePlayer (Player $player)
Parameters
Player $player
Definition at line 272 of file Player.php.
References pocketmine\Player\despawnFrom(), and pocketmine\Player\getName().
pocketmine\Player::isBanned ()
Returns
bool
Implements pocketmine\IPlayer.
Definition at line 177 of file Player.php.
pocketmine\Player::isConnected ()
Returns
bool
Definition at line 436 of file Player.php.
pocketmine\Player::isOnline ()
Returns
bool
Implements pocketmine\IPlayer.
Definition at line 296 of file Player.php.
Referenced by pocketmine\Player\showPlayer().
pocketmine\Player::isOp ()
Returns
bool
Implements pocketmine\permission\ServerOperator.
Definition at line 303 of file Player.php.
pocketmine\Player::isPermissionSet ($name)
Parameters
permission\Permission | string $name
Returns
bool
Implements pocketmine\permission\Permissible.
Definition at line 329 of file Player.php.
pocketmine\Player::isSleeping ()
Returns
bool
Definition at line 493 of file Player.php.
pocketmine\level\Position::isValid () inherited
Checks if this object has a valid reference to a Level
Returns
bool
Definition at line 71 of file Position.php.
Referenced by pocketmine\level\Position\getSide(), and pocketmine\block\Block\getSide().
pocketmine\Player::isWhitelisted ()
Returns
bool
Implements pocketmine\IPlayer.
Definition at line 189 of file Player.php.
pocketmine\Player::kick ($reason = "")
Kicks a player from the server
Parameters
string $reason
Returns
bool
Definition at line 2053 of file Player.php.
pocketmine\Player::orderChunks ()
WARNING: Do not use this, it's only for internal use. Changes to this function won't be recorded on the version.
Returns
bool
Definition at line 667 of file Player.php.
pocketmine\Player::recalculatePermissions ()
Returns
void
Implements pocketmine\permission\Permissible.
Definition at line 360 of file Player.php.
pocketmine\Player::removeAchievement ($achievementId)
Parameters
string $achievementId
Definition at line 408 of file Player.php.
pocketmine\Player::removeAttachment (PermissionAttachment $attachment)
Parameters
PermissionAttachment $attachment
Implements pocketmine\permission\Permissible.
Definition at line 356 of file Player.php.
pocketmine\Player::removeMetadata ($metadataKey, Plugin $owningPlugin)
Removes the given metadata value from the implementing object's metadata store.
Parameters
string $metadataKey
Plugin $owningPlugin
Returns
void
Implements pocketmine\metadata\Metadatable.
Definition at line 2365 of file Player.php.
pocketmine\Player::save ()
Handles player data saving
Definition at line 2144 of file Player.php.
References pocketmine\level\Position\getLevel().
pocketmine\Player::sendMessage ($message)
Sends a direct chat message to a player
Parameters
string $message
Implements pocketmine\command\CommandSender.
Definition at line 2071 of file Player.php.
pocketmine\Player::sendNextChunk ()
Sends, if available, the next ordered chunk to the client
WARNING: Do not use this, it's only for internal use. Changes to this function won't be recorded on the version.
Definition at line 579 of file Player.php.
pocketmine\Player::sendSettings ($nametags = true)
Sends all the option flags
WARNING: Do not use this, it's only for internal use. Changes to this function won't be recorded on the version.
Parameters
bool $nametags
Definition at line 998 of file Player.php.
pocketmine\Player::setBanned ($banned)
Parameters
bool $banned
Implements pocketmine\IPlayer.
Definition at line 181 of file Player.php.
pocketmine\Player::setDisplayName ($name)
Parameters
string $name
Definition at line 452 of file Player.php.
pocketmine\Player::setGamemode ($gm)
Sets the gamemode, and if needed, kicks the player TODO: Check if Mojang adds the ability to change gamemode without kicking players
Parameters
int $gm
Returns
bool
Definition at line 948 of file Player.php.
pocketmine\entity\Entity::setLastDamageCause ($type) inherited
Parameters
int | EntityDamageEvent $type
Definition at line 311 of file Entity.php.
pocketmine\entity\Entity::setMaxHealth ($amount) inherited
Parameters
int $amount
Definition at line 332 of file Entity.php.
pocketmine\Player::setMetadata ($metadataKey, MetadataValue $newMetadataValue)
Sets a metadata value in the implementing object's metadata store.
Parameters
string $metadataKey
MetadataValue $newMetadataValue
Returns
void
Implements pocketmine\metadata\Metadatable.
Definition at line 2353 of file Player.php.
pocketmine\Player::setNameTag ($name)
Parameters
string $name
Definition at line 466 of file Player.php.
pocketmine\Player::setOp ($value)
Parameters
bool $value
Implements pocketmine\permission\ServerOperator.
Definition at line 310 of file Player.php.
pocketmine\Player::setRemoveFormat ($remove = true)
Parameters
bool $remove
Definition at line 256 of file Player.php.
pocketmine\Player::setSpawn (Vector3 $pos)
Sets the spawnpoint of the player (and the compass direction) to a Vector3, or set it on another world with a Position object
Parameters
Vector3 | Position $pos
Definition at line 823 of file Player.php.
pocketmine\level\Position::setStrong () inherited
Marks the level reference as strong so it won't be collected by the garbage collector.
Returns
bool
Definition at line 81 of file Position.php.
pocketmine\level\Position::setWeak () inherited
Marks the level reference as weak so it won't have effect against the garbage collector decision.
Returns
bool
Definition at line 91 of file Position.php.
pocketmine\Player::setWhitelisted ($value)
Parameters
bool $value
Implements pocketmine\IPlayer.
Definition at line 193 of file Player.php.
pocketmine\Player::showPlayer (Player $player)
Parameters
Player $player
Definition at line 283 of file Player.php.
References pocketmine\Player\getName(), pocketmine\Player\isOnline(), and pocketmine\Player\spawnTo().
pocketmine\Player::sleepOn (Vector3 $pos)
Parameters
Vector3 $pos
Returns
boolean
Definition at line 798 of file Player.php.
pocketmine\Player::spawnTo (Player $player)
Parameters
Player $player
Definition at line 224 of file Player.php.
References pocketmine\Player\canSee(), and pocketmine\level\Position\getLevel().
Referenced by pocketmine\Player\showPlayer().
pocketmine\math\Vector3::subtract ($x = 0, $y = 0, $z = 0) inherited
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 105 of file Vector3.php.
References pocketmine\math\Vector3\add().
The documentation for this class was generated from the following file:
Player.php