PocketMine-MP: pocketmine\inventory\CraftingTransactionGroup Class Reference
pocketmine\inventory\CraftingTransactionGroup Class Reference
Public Member Functions
__construct (SimpleTransactionGroup $group)
addTransaction (Transaction $transaction)
getRecipe ()
getResult ()
canExecute ()
getMatchingRecipe ()
execute ()
getSource ()
getCreationTime ()
getInventories ()
getTransactions ()
hasExecuted ()
Protected Member Functions
matchItems (array &$needItems, array &$haveItems)
Protected Attributes
$input = []
$output = []
$recipe = null
$hasExecuted = false
$source = null
$inventories = []
$transactions = []
Detailed Description
Definition at line 28 of file CraftingTransactionGroup.php.
Member Function Documentation
pocketmine\inventory\CraftingTransactionGroup::addTransaction (Transaction $transaction)
Parameters
Transaction $transaction
Implements pocketmine\inventory\TransactionGroup.
Definition at line 46 of file CraftingTransactionGroup.php.
References pocketmine\inventory\SimpleTransactionGroup\matchItems().
pocketmine\inventory\CraftingTransactionGroup::canExecute ()
Returns
bool
Implements pocketmine\inventory\TransactionGroup.
Definition at line 71 of file CraftingTransactionGroup.php.
References pocketmine\inventory\CraftingTransactionGroup\getMatchingRecipe().
Referenced by pocketmine\inventory\CraftingTransactionGroup\execute().
pocketmine\inventory\CraftingTransactionGroup::execute ()
Returns
bool
Implements pocketmine\inventory\TransactionGroup.
Definition at line 90 of file CraftingTransactionGroup.php.
References pocketmine\inventory\CraftingTransactionGroup\canExecute(), pocketmine\Server\getInstance(), pocketmine\inventory\CraftingTransactionGroup\getMatchingRecipe(), pocketmine\inventory\SimpleTransactionGroup\getSource(), and pocketmine\inventory\SimpleTransactionGroup\hasExecuted().
pocketmine\inventory\SimpleTransactionGroup::getCreationTime () inherited
Returns
float
Implements pocketmine\inventory\TransactionGroup.
Definition at line 59 of file SimpleTransactionGroup.php.
pocketmine\inventory\SimpleTransactionGroup::getInventories () inherited
Returns
Inventory[]
Implements pocketmine\inventory\TransactionGroup.
Definition at line 63 of file SimpleTransactionGroup.php.
pocketmine\inventory\CraftingTransactionGroup::getMatchingRecipe ()
Returns
Recipe
Definition at line 82 of file CraftingTransactionGroup.php.
References pocketmine\Server\getInstance().
Referenced by pocketmine\inventory\CraftingTransactionGroup\canExecute(), and pocketmine\inventory\CraftingTransactionGroup\execute().
pocketmine\inventory\CraftingTransactionGroup::getRecipe ()
Gets the Items that have been used
Returns
Item[]
Definition at line 58 of file CraftingTransactionGroup.php.
Referenced by pocketmine\inventory\CraftingManager\matchTransaction().
pocketmine\inventory\CraftingTransactionGroup::getResult ()
Returns
Item
Definition at line 65 of file CraftingTransactionGroup.php.
Referenced by pocketmine\inventory\CraftingManager\matchTransaction().
pocketmine\inventory\SimpleTransactionGroup::getSource () inherited
Returns
Player
Definition at line 55 of file SimpleTransactionGroup.php.
Referenced by pocketmine\inventory\CraftingTransactionGroup\execute(), and pocketmine\inventory\SimpleTransactionGroup\execute().
pocketmine\inventory\SimpleTransactionGroup::getTransactions () inherited
Returns
Transaction[]
Implements pocketmine\inventory\TransactionGroup.
Definition at line 67 of file SimpleTransactionGroup.php.
pocketmine\inventory\SimpleTransactionGroup::hasExecuted () inherited
Returns
bool
Implements pocketmine\inventory\TransactionGroup.
Definition at line 160 of file SimpleTransactionGroup.php.
Referenced by pocketmine\inventory\CraftingTransactionGroup\execute(), and pocketmine\inventory\SimpleTransactionGroup\execute().
pocketmine\inventory\SimpleTransactionGroup::matchItems (array & $needItems, array & $haveItems) protected inherited
Parameters
Item[] $needItems
Item[] $haveItems
Returns
bool
Definition at line 94 of file SimpleTransactionGroup.php.
Referenced by pocketmine\inventory\CraftingTransactionGroup\addTransaction(), and pocketmine\inventory\SimpleTransactionGroup\canExecute().
The documentation for this class was generated from the following file:
CraftingTransactionGroup.php