PocketMine-MP: pocketmine\utils\Config Class Reference
pocketmine\utils\Config Class Reference
Public Member Functions
__construct ($file, $type=Config::DETECT, $default=[], &$correct=null)
reload ()
load ($file, $type=Config::DETECT, $default=[])
check ()
save ()
& __get ($k)
__set ($k, $v)
__isset ($k)
__unset ($k)
& get ($k)
& getPath ($path)
& setPath ($path, $value)
set ($k, $v=true)
setAll ($v)
exists ($k, $lowercase=false)
remove ($k)
getAll ($keys=false)
setDefaults (array $defaults)
Static Public Member Functions
static fixYAMLIndexes ($str)
Public Attributes
const DETECT = -1
const PROPERTIES = 0
const CNF = Config::PROPERTIES
const JSON = 1
const YAML = 2
const SERIALIZED = 4
const ENUM = 5
const ENUMERATION = Config::ENUM
Static Public Attributes
static $formats
Detailed Description
Class Config
Config Class for simple config manipulation of multiple formats.
Definition at line 30 of file Config.php.
Constructor & Destructor Documentation
pocketmine\utils\Config::__construct ($file, $type = Config::DETECT, $default = [], & $correct = null)
Parameters
string $file Path of the file to be loaded
int $type Config type to load, -1 by default (detect)
array $default Array with the default values, will be set if not existent
null &$correct Sets correct to true if everything has been loaded correctly
Definition at line 74 of file Config.php.
References pocketmine\utils\Config\load().
Member Function Documentation
& pocketmine\utils\Config::__get ($k)
Parameters
$k
Returns
boolean|mixed
Definition at line 208 of file Config.php.
pocketmine\utils\Config::__isset ($k)
Parameters
$k
Returns
boolean
Definition at line 225 of file Config.php.
References pocketmine\utils\Config\exists().
pocketmine\utils\Config::__set ($k, $v)
Parameters
$k
$v
Definition at line 216 of file Config.php.
References pocketmine\utils\Config\set().
pocketmine\utils\Config::__unset ($k)
Parameters
$k
Definition at line 232 of file Config.php.
pocketmine\utils\Config::check ()
Returns
boolean
Definition at line 167 of file Config.php.
pocketmine\utils\Config::exists ($k, $lowercase = false)
Parameters
$k
bool $lowercase If set, searches Config in single-case / lowercase.
Returns
boolean
Definition at line 307 of file Config.php.
Referenced by pocketmine\utils\Config\__isset().
static pocketmine\utils\Config::fixYAMLIndexes ($str) static
Parameters
$str
Returns
mixed
Definition at line 94 of file Config.php.
& pocketmine\utils\Config::get ($k)
Parameters
$k
Returns
boolean|mixed
Definition at line 241 of file Config.php.
pocketmine\utils\Config::getAll ($keys = false)
Parameters
bool $keys
Returns
array
Definition at line 329 of file Config.php.
& pocketmine\utils\Config::getPath ($path)
Parameters
string $path
Returns
mixed
Definition at line 256 of file Config.php.
pocketmine\utils\Config::load ($file, $type = Config::DETECT, $default = [])
Parameters
$file
int $type
array $default
Returns
bool
Definition at line 105 of file Config.php.
References pocketmine\utils\Config\save().
Referenced by pocketmine\utils\Config\__construct(), and pocketmine\utils\Config\reload().
pocketmine\utils\Config::reload ()
Removes all the changes in memory and loads the file again
Definition at line 82 of file Config.php.
References pocketmine\utils\Config\load().
pocketmine\utils\Config::remove ($k)
Parameters
$k
Definition at line 320 of file Config.php.
pocketmine\utils\Config::save ()
Returns
boolean
Definition at line 174 of file Config.php.
Referenced by pocketmine\utils\Config\load().
pocketmine\utils\Config::set ($k, $v = true)
Parameters
string $k key to be set
mixed $v value to set key
Definition at line 290 of file Config.php.
Referenced by pocketmine\utils\Config\__set().
pocketmine\utils\Config::setAll ($v)
Parameters
array $v
Definition at line 297 of file Config.php.
pocketmine\utils\Config::setDefaults (array $defaults)
Parameters
array $defaults
Definition at line 336 of file Config.php.
& pocketmine\utils\Config::setPath ($path, $value)
Parameters
string $path
mixed $value
Definition at line 273 of file Config.php.
Member Data Documentation
pocketmine\utils\Config::$formats static
Initial value:
= array(
        "properties" => Config::PROPERTIES,
        "cnf" => Config::CNF,
        "conf" => Config::CNF,
        "config" => Config::CNF,
        "json" => Config::JSON,
        "js" => Config::JSON,
        "yml" => Config::YAML,
        "yaml" => Config::YAML,
        "sl" => Config::SERIALIZED,
        "serialize" => Config::SERIALIZED,
        "txt" => Config::ENUM,
        "list" => Config::ENUM,
        "enum" => Config::ENUM,
    )
Definition at line 50 of file Config.php.
The documentation for this class was generated from the following file:
Config.php