PocketMine-MP: pocketmine\entity\Zombie Class Reference
pocketmine\entity\Zombie Class Reference
Public Member Functions
getName ()
spawnTo (Player $player)
getData ()
getDrops ()
saveNBT ()
attack ($damage, $source=EntityDamageEvent::CAUSE_MAGIC)
heal ($amount)
kill ()
entityBaseTick ()
getViewers ()
despawnFrom (Player $player)
getHealth ()
setHealth ($amount)
setLastDamageCause ($type)
getLastDamageCause ()
getMaxHealth ()
setMaxHealth ($amount)
canCollideWith (Entity $entity)
updateMovement ()
getDirectionVector ()
onUpdate ()
scheduleUpdate ()
setOnFire ($seconds)
getDirection ()
extinguish ()
canTriggerWalking ()
getBoundingBox ()
fall ($fallDistance)
handleWaterMovement ()
handleLavaMovement ()
getEyeHeight ()
moveFlying ()
onCollideWithPlayer (Human $entityPlayer)
getPosition ()
collision ()
move ($dx, $dy, $dz)
setPositionAndRotation (Vector3 $pos, $yaw, $pitch, $force=false)
setRotation ($yaw, $pitch)
setPosition (Vector3 $pos, $force=false)
getMotion ()
setMotion (Vector3 $motion)
isOnGround ()
teleport (Vector3 $pos, $yaw=null, $pitch=null)
getID ()
spawnToAll ()
despawnFromAll ()
close ()
setMetadata ($metadataKey, MetadataValue $metadataValue)
getMetadata ($metadataKey)
hasMetadata ($metadataKey)
removeMetadata ($metadataKey, Plugin $plugin)
__toString ()
getLevel ()
setLevel (Level $level, $strong=false)
isValid ()
setStrong ()
setWeak ()
getSide ($side, $step=1)
distance (Vector3 $pos)
getX ()
getY ()
getZ ()
getFloorX ()
getFloorY ()
getFloorZ ()
getRight ()
getUp ()
getForward ()
getSouth ()
getWest ()
add ($x, $y=0, $z=0)
subtract ($x=0, $y=0, $z=0)
multiply ($number)
divide ($number)
ceil ()
floor ()
round ()
abs ()
distanceSquared (Vector3 $pos)
maxPlainDistance ($x=0, $z=0)
length ()
lengthSquared ()
normalize ()
dot (Vector3 $v)
cross (Vector3 $v)
Static Public Member Functions
static fromObject (Vector3 $pos, Level $level, $strong=false)
Public Attributes
const NETWORK_ID = 32
$width = 0.6
$length = 0.6
$height = 1.8
$passenger = null
$vehicle = null
$chunkX
$chunkZ
$chunk
$lastX
$lastY
$lastZ
$motionX
$motionY
$motionZ
$lastMotionX
$lastMotionY
$lastMotionZ
$yaw
$pitch
$lastYaw
$lastPitch
$boundingBox
$onGround
$inBlock = false
$positionChanged
$motionChanged
$dead
$fallDistance
$ticksLived
$lastUpdate
$maxFireTicks
$fireTicks
$airTicks
$namedtag
$noDamageTicks
$closed = false
$level = null
$x
$y
$z
Static Public Attributes
static $entityCount = 1
static $needUpdate = []
Protected Member Functions
initEntity ()
checkObstruction ($x, $y, $z)
updateFallState ($distanceThisTick, $onGround)
switchLevel (Level $targetLevel)
checkBlockCollision (&$list=array())
Protected Attributes
$gravity = 0.08
$drag = 0.02
$hasSpawned = []
$id
$lastDamageCause = null
$age = 0
$isStatic = false
$isColliding = false
$inWater
$fireProof
$spawnTime
$server
Detailed Description
Definition at line 31 of file Zombie.php.
Member Function Documentation
pocketmine\math\Vector3::add ($x, $y = 0, $z = 0) inherited
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 90 of file Vector3.php.
Referenced by pocketmine\math\Vector3\subtract(), and pocketmine\level\Level\useBreakOn().
pocketmine\entity\Entity::checkBlockCollision (& $list = array()) protected inherited
Parameters
Block[] $list
Returns
Block[]
Definition at line 873 of file Entity.php.
References pocketmine\level\Position\getLevel().
pocketmine\entity\Entity::despawnFrom (Player $player) inherited
Parameters
Player $player
Definition at line 260 of file Entity.php.
References pocketmine\Player\dataPacket().
pocketmine\level\Position::distance (Vector3 $pos) inherited
Returns the distance between two points or objects
Parameters
Vector3 $pos
Returns
float
Definition at line 120 of file Position.php.
References pocketmine\level\Position\getLevel().
pocketmine\entity\Entity::getDirectionVector () inherited
Returns
Vector3
Definition at line 535 of file Entity.php.
pocketmine\entity\Entity::getHealth () inherited
Returns
int
Definition at line 282 of file Entity.php.
pocketmine\entity\Entity::getLastDamageCause () inherited
Returns
int|EntityDamageEvent|null
Definition at line 318 of file Entity.php.
pocketmine\level\Position::getLevel () inherited
Returns
Level
Definition at line 55 of file Position.php.
Referenced by pocketmine\level\Level\addEntity(), pocketmine\level\Level\addTile(), pocketmine\entity\Entity\checkBlockCollision(), pocketmine\level\Position\distance(), pocketmine\block\Block\getMetadata(), pocketmine\tile\Chest\getPair(), pocketmine\level\Position\getSide(), pocketmine\block\Block\getSide(), pocketmine\Player\getSpawn(), pocketmine\block\Block\hasMetadata(), pocketmine\level\Level\removeEntity(), pocketmine\block\Block\removeMetadata(), pocketmine\level\Level\removeTile(), pocketmine\Player\save(), pocketmine\block\Block\setMetadata(), and pocketmine\Player\spawnTo().
pocketmine\entity\Entity::getMaxHealth () inherited
Returns
int
Definition at line 325 of file Entity.php.
Referenced by pocketmine\entity\Entity\setHealth().
pocketmine\entity\Entity::getMetadata ($metadataKey) inherited
Returns a list of previously set metadata values from the implementing object's metadata store.
Parameters
string $metadataKey
Returns
MetadataValue[]
Implements pocketmine\metadata\Metadatable.
Definition at line 1072 of file Entity.php.
pocketmine\level\Position::getSide ($side, $step = 1) inherited
Returns a side Vector
Parameters
int $side
int $step
Returns
Position
Exceptions
RuntimeException
Definition at line 105 of file Position.php.
References pocketmine\level\Position\getLevel(), and pocketmine\level\Position\isValid().
pocketmine\entity\Entity::getViewers () inherited
Returns
Player[]
Definition at line 244 of file Entity.php.
pocketmine\entity\Entity::hasMetadata ($metadataKey) inherited
Tests to see whether the implementing object contains the given metadata value in its metadata store.
Parameters
string $metadataKey
Returns
boolean
Implements pocketmine\metadata\Metadatable.
Definition at line 1076 of file Entity.php.
pocketmine\level\Position::isValid () inherited
Checks if this object has a valid reference to a Level
Returns
bool
Definition at line 71 of file Position.php.
Referenced by pocketmine\level\Position\getSide(), and pocketmine\block\Block\getSide().
pocketmine\entity\Entity::removeMetadata ($metadataKey, Plugin $owningPlugin) inherited
Removes the given metadata value from the implementing object's metadata store.
Parameters
string $metadataKey
Plugin $owningPlugin
Returns
void
Implements pocketmine\metadata\Metadatable.
Definition at line 1080 of file Entity.php.
pocketmine\entity\Entity::setHealth ($amount) inherited
Sets the health of the Entity. This won't send any update to the players
Parameters
int $amount
Definition at line 291 of file Entity.php.
References pocketmine\entity\Entity\getMaxHealth().
pocketmine\entity\Entity::setLastDamageCause ($type) inherited
Parameters
int | EntityDamageEvent $type
Definition at line 311 of file Entity.php.
pocketmine\entity\Entity::setMaxHealth ($amount) inherited
Parameters
int $amount
Definition at line 332 of file Entity.php.
pocketmine\entity\Entity::setMetadata ($metadataKey, MetadataValue $newMetadataValue) inherited
Sets a metadata value in the implementing object's metadata store.
Parameters
string $metadataKey
MetadataValue $newMetadataValue
Returns
void
Implements pocketmine\metadata\Metadatable.
Definition at line 1068 of file Entity.php.
pocketmine\level\Position::setStrong () inherited
Marks the level reference as strong so it won't be collected by the garbage collector.
Returns
bool
Definition at line 81 of file Position.php.
pocketmine\level\Position::setWeak () inherited
Marks the level reference as weak so it won't have effect against the garbage collector decision.
Returns
bool
Definition at line 91 of file Position.php.
pocketmine\math\Vector3::subtract ($x = 0, $y = 0, $z = 0) inherited
Parameters
Vector3 | int $x
int $y
int $z
Returns
Vector3
Definition at line 105 of file Vector3.php.
References pocketmine\math\Vector3\add().
The documentation for this class was generated from the following file:
Zombie.php