PocketMine-MP: pocketmine\permission\PermissionAttachment Class Reference
pocketmine\permission\PermissionAttachment Class Reference
Public Member Functions
__construct (Plugin $plugin, Permissible $permissible)
getPlugin ()
setRemovalCallback (PermissionRemovedExecutor $ex)
getRemovalCallback ()
getPermissible ()
getPermissions ()
setPermission ($name, $value)
unsetPermission ($name)
remove ()
Detailed Description
Definition at line 26 of file PermissionAttachment.php.
Constructor & Destructor Documentation
pocketmine\permission\PermissionAttachment::__construct (Plugin $plugin, Permissible $permissible)
Parameters
Plugin $plugin
Permissible $permissible
Exceptions
Exception
Definition at line 47 of file PermissionAttachment.php.
References pocketmine\plugin\Plugin\getDescription().
Member Function Documentation
pocketmine\permission\PermissionAttachment::getPermissible ()
Returns
Permissible
Definition at line 80 of file PermissionAttachment.php.
pocketmine\permission\PermissionAttachment::getPermissions ()
Returns
bool[]
Definition at line 87 of file PermissionAttachment.php.
pocketmine\permission\PermissionAttachment::getPlugin ()
Returns
Plugin
Definition at line 59 of file PermissionAttachment.php.
pocketmine\permission\PermissionAttachment::getRemovalCallback ()
Returns
PermissionRemovedExecutor
Definition at line 73 of file PermissionAttachment.php.
Referenced by pocketmine\permission\PermissibleBase\removeAttachment().
pocketmine\permission\PermissionAttachment::remove ()
Returns
void
Definition at line 110 of file PermissionAttachment.php.
pocketmine\permission\PermissionAttachment::setPermission ($name, $value)
Parameters
string | Permission $name
bool $value
Definition at line 95 of file PermissionAttachment.php.
References pocketmine\permission\Permission\getName().
pocketmine\permission\PermissionAttachment::setRemovalCallback (PermissionRemovedExecutor $ex)
Parameters
PermissionRemovedExecutor $ex
Definition at line 66 of file PermissionAttachment.php.
pocketmine\permission\PermissionAttachment::unsetPermission ($name)
Parameters
string | Permission $name
Definition at line 103 of file PermissionAttachment.php.
References pocketmine\permission\Permission\getName().
The documentation for this class was generated from the following file:
PermissionAttachment.php