PocketMine-MP: pocketmine\level\generator\GenerationRequestManager Class Reference
pocketmine\level\generator\GenerationRequestManager Class Reference
Public Member Functions
__construct (Server $server)
openLevel (Level $level, $generator, array $options=[])
closeLevel (Level $level)
addNamespace ($namespace, $path)
requestChunk (Level $level, $chunkX, $chunkZ)
shutdown ()
Protected Member Functions
socketRead ($len)
sendChunk ($levelID, FullChunk $chunk)
handleRequest ($levelID, $chunkX, $chunkZ)
receiveChunk ($levelID, FullChunk $chunk)
Protected Attributes
$socket
$server
$generationThread
Detailed Description
Definition at line 29 of file GenerationRequestManager.php.
Constructor & Destructor Documentation
pocketmine\level\generator\GenerationRequestManager::__construct (Server $server)
Parameters
Server $server
Definition at line 40 of file GenerationRequestManager.php.
References pocketmine\Server\getLoader(), and pocketmine\Server\getLogger().
Member Function Documentation
pocketmine\level\generator\GenerationRequestManager::closeLevel (Level $level)
Parameters
Level $level
Definition at line 61 of file GenerationRequestManager.php.
References pocketmine\level\Level\getID().
pocketmine\level\generator\GenerationRequestManager::openLevel (Level $level, $generator, array $options = [])
Parameters
Level $level
string $generator
array $options
Definition at line 51 of file GenerationRequestManager.php.
References pocketmine\level\Level\getID(), pocketmine\level\Level\getSeed(), and pocketmine\utils\Binary\writeShort().
The documentation for this class was generated from the following file:
GenerationRequestManager.php