PocketMine-MP: pocketmine\level\format\anvil\Chunk Class Reference
pocketmine\level\format\anvil\Chunk Class Reference
Public Member Functions
__construct ($level, Compound $nbt)
isPopulated ()
setPopulated ($value=1)
isGenerated ()
setGenerated ($value=1)
getNBT ()
toBinary ()
getBlock ($x, $y, $z, &$blockId, &$meta=null)
setBlock ($x, $y, $z, $blockId=null, $meta=null)
getBlockId ($x, $y, $z)
setBlockId ($x, $y, $z, $id)
getBlockData ($x, $y, $z)
setBlockData ($x, $y, $z, $data)
getBlockSkyLight ($x, $y, $z)
setBlockSkyLight ($x, $y, $z, $data)
getBlockLight ($x, $y, $z)
setBlockLight ($x, $y, $z, $data)
getBlockIdColumn ($x, $z)
getBlockDataColumn ($x, $z)
getBlockSkyLightColumn ($x, $z)
getBlockLightColumn ($x, $z)
isSectionEmpty ($fY)
getSection ($fY)
setSection ($fY, ChunkSection $section)
load ($generate=true)
getBlockIdArray ()
getBlockDataArray ()
getBlockSkyLightArray ()
getBlockLightArray ()
getSections ()
getX ()
getZ ()
setX ($x)
setZ ($z)
getLevel ()
getProvider ()
setProvider (LevelProvider $provider)
getBiomeId ($x, $z)
setBiomeId ($x, $z, $biomeId)
getBiomeColor ($x, $z)
setBiomeColor ($x, $z, $R, $G, $B)
getHighestBlockAt ($x, $z)
addEntity (Entity $entity)
removeEntity (Entity $entity)
addTile (Tile $tile)
removeTile (Tile $tile)
getEntities ()
getTiles ()
isLoaded ()
unload ($save=true, $safe=true)
getBiomeIdArray ()
getBiomeColorArray ()
Static Public Member Functions
static fromBinary ($data, LevelProvider $provider=null)
Public Attributes
const SECTION_COUNT = 8
Protected Attributes
$nbt
$sections = []
$entities = []
$tiles = []
$biomeIds
$biomeColors
$level
$x
$z
$blocks
$data
$skyLight
$blockLight
$provider
Detailed Description
Definition at line 37 of file anvil/Chunk.php.
Member Function Documentation
pocketmine\level\format\generic\BaseFullChunk::addEntity (Entity $entity) inherited
Parameters
Entity $entity
Implements pocketmine\level\format\FullChunk.
Definition at line 210 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::addTile (Tile $tile) inherited
Parameters
Tile $tile
Implements pocketmine\level\format\FullChunk.
Definition at line 218 of file BaseFullChunk.php.
static pocketmine\level\format\anvil\Chunk::fromBinary ($data, LevelProvider $provider = null) static
Parameters
string $data
LevelProvider $provider
Returns
Chunk
Implements pocketmine\level\format\FullChunk.
Definition at line 134 of file anvil/Chunk.php.
pocketmine\level\format\generic\BaseFullChunk::getBiomeColor ($x, $z) inherited
Parameters
int $x
int $z
Returns
int[] RGB bytes
Implements pocketmine\level\format\FullChunk.
Definition at line 189 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getBiomeColorArray () inherited
Returns
int[]
Implements pocketmine\level\format\FullChunk.
Definition at line 280 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getBiomeId ($x, $z) inherited
Parameters
int $x 0-15
int $z 0-15
Returns
int 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 181 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getBiomeIdArray () inherited
Returns
string[]
Implements pocketmine\level\format\FullChunk.
Definition at line 276 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlock ($x, $y, $z, & $blockId, & $meta = null) inherited
Modifies $blockId and $meta
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int &$blockId
int &$meta
Implements pocketmine\level\format\FullChunk.
Definition at line 145 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlockData ($x, $y, $z) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 174 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlockId ($x, $y, $z) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 160 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlockLight ($x, $y, $z) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 202 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getBlockSkyLight ($x, $y, $z) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
Returns
int 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 188 of file BaseChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getEntities () inherited
Returns
[]
Implements pocketmine\level\format\FullChunk.
Definition at line 226 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseFullChunk::getHighestBlockAt ($x, $z) inherited
Parameters
int $x 0-15
int $z 0-15
Returns
int 0-127
Implements pocketmine\level\format\FullChunk.
Definition at line 199 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getLevel () inherited
Returns
LevelProvider
Deprecated:
Definition at line 166 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider().
pocketmine\level\format\anvil\Chunk::getNBT ()
Returns
Compound
Definition at line 124 of file anvil/Chunk.php.
pocketmine\level\format\generic\BaseFullChunk::getProvider () inherited
Returns
LevelProvider
Implements pocketmine\level\format\FullChunk.
Definition at line 173 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseChunk\__construct(), pocketmine\level\format\generic\BaseFullChunk\__construct(), pocketmine\level\format\generic\BaseFullChunk\getLevel(), pocketmine\level\format\generic\BaseFullChunk\isLoaded(), pocketmine\level\format\generic\BaseFullChunk\load(), pocketmine\level\format\generic\BaseChunk\load(), pocketmine\level\format\generic\BaseChunk\setBlock(), pocketmine\level\format\generic\BaseChunk\setBlockData(), pocketmine\level\format\generic\BaseChunk\setBlockId(), pocketmine\level\format\generic\BaseChunk\setBlockLight(), pocketmine\level\format\generic\BaseChunk\setBlockSkyLight(), and pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseChunk::getSection ($fY) inherited
Parameters
int $fY 0-7
Returns
ChunkSection
Implements pocketmine\level\format\Chunk.
Definition at line 256 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::getSections () inherited
Returns
ChunkSection[]
Implements pocketmine\level\format\Chunk.
Definition at line 315 of file BaseChunk.php.
pocketmine\level\format\generic\BaseFullChunk::getTiles () inherited
Returns
[]
Implements pocketmine\level\format\FullChunk.
Definition at line 230 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseFullChunk::getX () inherited
Returns
int
Implements pocketmine\level\format\FullChunk.
Definition at line 145 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\isLoaded(), pocketmine\level\format\generic\BaseFullChunk\load(), pocketmine\level\format\generic\BaseChunk\load(), and pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\generic\BaseFullChunk::getZ () inherited
Returns
int
Implements pocketmine\level\format\FullChunk.
Definition at line 149 of file BaseFullChunk.php.
Referenced by pocketmine\level\format\generic\BaseFullChunk\isLoaded(), pocketmine\level\format\generic\BaseFullChunk\load(), pocketmine\level\format\generic\BaseChunk\load(), and pocketmine\level\format\generic\BaseFullChunk\unload().
pocketmine\level\format\anvil\Chunk::isGenerated ()
Returns
bool
Implements pocketmine\level\format\FullChunk.
Definition at line 110 of file anvil/Chunk.php.
pocketmine\level\format\generic\BaseFullChunk::isLoaded () inherited
Returns
bool
Implements pocketmine\level\format\FullChunk.
Definition at line 234 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider(), pocketmine\level\format\generic\BaseFullChunk\getX(), and pocketmine\level\format\generic\BaseFullChunk\getZ().
pocketmine\level\format\anvil\Chunk::isPopulated ()
Returns
bool
Implements pocketmine\level\format\FullChunk.
Definition at line 96 of file anvil/Chunk.php.
pocketmine\level\format\generic\BaseChunk::isSectionEmpty ($fY) inherited
Tests whether a section (mini-chunk) is empty
Parameters
$fY 0-7, (Y / 16)
Returns
bool
Implements pocketmine\level\format\Chunk.
Definition at line 252 of file BaseChunk.php.
pocketmine\level\format\generic\BaseChunk::load ($generate = true) inherited
Loads the chunk
Parameters
bool $generate If the chunk does not exist, generate it
Returns
bool
Implements pocketmine\level\format\FullChunk.
Definition at line 272 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider(), pocketmine\level\format\generic\BaseFullChunk\getX(), and pocketmine\level\format\generic\BaseFullChunk\getZ().
pocketmine\level\format\generic\BaseFullChunk::removeEntity (Entity $entity) inherited
Parameters
Entity $entity
Implements pocketmine\level\format\FullChunk.
Definition at line 214 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::removeTile (Tile $tile) inherited
Parameters
Tile $tile
Implements pocketmine\level\format\FullChunk.
Definition at line 222 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::setBiomeColor ($x, $z, $R, $G, $B) inherited
Parameters
int $x 0-15
int $z 0-15
int $R 0-255
int $G 0-255
int $B 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 195 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseFullChunk::setBiomeId ($x, $z, $biomeId) inherited
Parameters
int $x 0-15
int $z 0-15
int $biomeId 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 185 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseChunk::setBlock ($x, $y, $z, $blockId = null, $meta = null) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $blockId,if null, do not change
int $meta 0-15, if null, do not change
Implements pocketmine\level\format\FullChunk.
Definition at line 149 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider().
pocketmine\level\format\generic\BaseChunk::setBlockData ($x, $y, $z, $data) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $data 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 178 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider().
pocketmine\level\format\generic\BaseChunk::setBlockId ($x, $y, $z, $id) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $id 0-255
Implements pocketmine\level\format\FullChunk.
Definition at line 164 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider().
pocketmine\level\format\generic\BaseChunk::setBlockLight ($x, $y, $z, $level) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $level 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 206 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider().
pocketmine\level\format\generic\BaseChunk::setBlockSkyLight ($x, $y, $z, $level) inherited
Parameters
int $x 0-15
int $y 0-127
int $z 0-15
int $level 0-15
Implements pocketmine\level\format\FullChunk.
Definition at line 192 of file BaseChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getProvider().
pocketmine\level\format\anvil\Chunk::setGenerated ($value = 1)
Parameters
int $value
Implements pocketmine\level\format\FullChunk.
Definition at line 117 of file anvil/Chunk.php.
pocketmine\level\format\anvil\Chunk::setPopulated ($value = 1)
Parameters
int $value
Implements pocketmine\level\format\FullChunk.
Definition at line 103 of file anvil/Chunk.php.
pocketmine\level\format\generic\BaseFullChunk::setProvider (LevelProvider $provider) inherited
Parameters
LevelProvider $provider
Implements pocketmine\level\format\FullChunk.
Definition at line 177 of file BaseFullChunk.php.
pocketmine\level\format\generic\BaseChunk::setSection ($fY, ChunkSection $section) inherited
Parameters
int $fY 0-7
ChunkSection $section
Returns
boolean
Implements pocketmine\level\format\Chunk.
Definition at line 260 of file BaseChunk.php.
pocketmine\level\format\generic\BaseFullChunk::unload ($save = true, $safe = true) inherited
Parameters
bool $save
bool $safe If false, unload the chunk even if players are nearby
Returns
bool
Implements pocketmine\level\format\FullChunk.
Definition at line 242 of file BaseFullChunk.php.
References pocketmine\level\format\generic\BaseFullChunk\getEntities(), pocketmine\level\format\generic\BaseFullChunk\getProvider(), pocketmine\level\format\generic\BaseFullChunk\getTiles(), pocketmine\level\format\generic\BaseFullChunk\getX(), and pocketmine\level\format\generic\BaseFullChunk\getZ().
The documentation for this class was generated from the following file:
anvil/Chunk.php